### DISCUSSION TITLE
author_profile in archive-taxonomy?

### DISCUSSION THREAD

**Discussion by rodrigograca31** [mmistakes/minimal-mistakes#2475] [Q&A]
https://github.com/mmistakes/minimal-mistakes/blob/c57dfd78b0f44cea7cdb39cd8653d206dc114c87/_layouts/archive-taxonomy.html#L3

Its just me or this line should not be here?

All other layout files dont specify `author_profile` ...

I don't know enough jekyll to know if there's a way to overwrite this without copying the entire `archive-taxonomy` file? but I want to set `author_profile` to true for this layout

**Comment by mmistakes** [comment]
https://mmistakes.github.io/minimal-mistakes/docs/configuration/#archive-settings

To apply [Front Matter defaults](https://jekyllrb.com/docs/configuration/front-matter-defaults/) to pages generated by the `jekyll-archives` plugin, you can specify a scope of an empty `path` and a `type` of either `tag` or `category`.

For example, the following configuration enables author profile on tag archives and disables comments on category archives.

```yaml
defaults:
  - scope:
      path: ""
      type: tag
    values:
      author_profile: true
  - scope:
      path: ""
      type: category
    values:
      comments: false
```

**Comment by rodrigograca31** [comment]
Thanks! For the record this is what I did:

```yaml
    - scope:
          path: ""
          type: category
      values:
          author_profile: true
    - scope:
          path: ""
          type: tag
      values:
          author_profile: true
```

but I still question why that page sets `author_profile` as false.... :question:
