### DISCUSSION TITLE
Can SCSS mixins be loaded before skins?

### DISCUSSION THREAD

**Discussion by aschrijver** [mmistakes/minimal-mistakes#2493] [Q&A]
I am adding my own custom skin and want to define custom button styles, like this:

```scss
.btn--primary.think {
  background-color: $think-color;

  &:hover {
    @include yiq-contrasted(mix(#000, $think-color, 20%));
  }
}
```
It does not work because the mixins are loaded after the skin, so I have to add this to `_buttons.scss` instead. It might be hard given the sequence stuff must be loaded, but maybe there is a way to have the mixins already available to skins?

**Comment by mmistakes** [comment]
Have you tried loading the mixins Sass partial in your skin partial?
If you `@import` it before you call the mixin with `@include` it should work. The only tricky part is getting the path to the mixin correct.

```scss
@import "../../mixins";

.btn--primary.think {
  background-color: $think-color;

  &:hover {
    @include yiq-contrasted(mix(#000, $think-color, 20%));
  }
}
```
