### DISCUSSION TITLE
Google Analytics not Showing any Data

### DISCUSSION THREAD

**Discussion by Destaq** [mmistakes/minimal-mistakes#2587] [Q&A] [answered]
I would like to use Google Analytics on my minimal-mistakes themed website. However, although I have followed the steps in the [documentation](https://mmistakes.github.io/minimal-mistakes/docs/configuration/#analytics), I am still receiving no data, even when sending test traffic.

I have configured the Google Analytics in the `_config.yml` file as so:
```
analytics:
  provider: "google"
  google:
    tracking_id: "UA-145818774-2"
    anonymize_ip: false # default
```
I am building the site with GitHub Pages and with a custom domain; repo is [here](https://github.com/Destaq/destaq.github.io). The Analytics has also been set up on my end as so:
![image](https://user-images.githubusercontent.com/61620873/86221357-18d6db80-bb85-11ea-813c-79b9d636b1ab.png)
I believe that I have followed all the steps necessary for setting up GA on my site, but there is still no data. I am writing the posts using kramdown in Markdown, and would appreciate any assistance setting up Google Analytics.
