### DISCUSSION TITLE
Hide masthead from splash page

### DISCUSSION THREAD

**Discussion by lhoupert** [mmistakes/minimal-mistakes#2594] [Q&A] [answered]
Hi, is there a parameter I missed that could hide the masthead on a specific page? 
I would like to do that on my home page (a spash-page).

Thank you!

**Comment by iBug** [comment, marked as answer]
Add some CSS to the page you want to hide masthead from. It could be as simple as

```css
body.layout--splash .masthead {
  display: none;
}
```

<https://mmistakes.github.io/minimal-mistakes/docs/stylesheets/>
