### DISCUSSION TITLE
Question: How can I reduce the font size and increase the column widths?

### DISCUSSION THREAD

**Discussion by ElectricRCAircraftGuy** [mmistakes/minimal-mistakes#2726] [Q&A]
I've read #2147, and it doesn't quite answer it for me. I've set `toc: true` and `classes: wide` in the front matter, and I still have all this whitespace to the left and right:

![image](https://user-images.githubusercontent.com/6842199/97848957-b3b40380-1ca6-11eb-9658-f279e068c70b.png)

How can I modify the css or sass or something to change this? I know very little about web page design. Also, where can I set the default font size for the entire site? I think it's all too big, as it's substantially bigger than most web sites and requires quite a bit of zooming out in the browser to look more like other sites.

**Comment by ElectricRCAircraftGuy** [comment]
Update: for font size I'm looking here: https://github.com/mmistakes/minimal-mistakes/issues/1514#issuecomment-362458573

**Comment by ElectricRCAircraftGuy** [comment]
And I'm going to dig through these ones too, starting here: https://github.com/mmistakes/minimal-mistakes/issues/1373#issuecomment-348000387.

**Comment by mmistakes** [comment]
The main column has a `max-width` set on it. If you want to change that you can do so in the CSS. https://github.com/mmistakes/minimal-mistakes/blob/master/_sass/minimal-mistakes/_page.scss#L17-L20

For anything related to changing font sizes, consult the many duplicate issues about it. I've covered that one in great detail more times than I care to count :wink:

**Comment by ElectricRCAircraftGuy** [comment]
I've already got my width set to 100% on that line you pointed to in your link, yet my output is still as I show in the image above. I've cloned your repo last night from latest master branch. Most of it is still default.

Note that this other person's Jekyll site (https://aneejian.com/) expands properly, and becomes about 3x wider than your site on the same monitor when the Chrome window is maximized to full screen.

**Comment by mmistakes** [comment]
It's all just CSS, and you can't really compare another person's Jekyll site as it uses a completely different stylesheet.
My suggestion would be to use your browser's web developer tools, inspect the element you want to style, look at the declarations and try changing them in browser.

Once you get it to do what you want, search in the theme for those lines and [customizethe CSS](https://mmistakes.github.io/minimal-mistakes/docs/stylesheets/#customizing).

Also something doesn't look right with your screenshot above. The table of contents should be floating to the right, yet in yours it's right above the main content. Perhaps you changed CSS elsewhere that broke that?

When I change the demo site's `max-width` to `100%` it spans the entire page just fine (see below).

![image](https://user-images.githubusercontent.com/1376749/97915494-8eafa700-1d1f-11eb-91d8-f5cdbf7bd13b.png)

**Comment by ElectricRCAircraftGuy** [comment]
Font size fixed. Here's what I did: https://github.com/mmistakes/minimal-mistakes/issues/1219#issuecomment-720921208

Still working on column width...

Note that the reason my ToC is on top is simply because I put `classes: wide` in the front matter, as I mentioned in the first post.

**Comment by ElectricRCAircraftGuy** [comment]
> When I change the demo site's max-width to 100% it spans the entire page just fine (see below).

Doing that manually works for me too, thank you. I've never done that before. I saw that the default value was `1280px` there. Searching the code base for `1280px` I found this line in `_variables.scss`:

```
$small: 600px !default;
$medium: 768px !default;
$medium-wide: 900px !default;
$large: 1024px !default;
$x-large: 1280px !default;
$max-width: $x-large !default;    // <======== the culprit! It sets max-width to x-large, which is 1280px!
```
So, I changed `$max-width: $x-large !default;` to `$max-width: 100% !default;` inside `_variables.scss`, and now it works fine. However, I'd like to override this in a different file somehow, so my changes stay more separated from your theme. I've tried a variety of things in `assets/css/main.scss`, but can't seem to get it. 

How can I override this variable in `_variables.scss` from this file (`assets/css/main.scss`) instead?

**Comment by ElectricRCAircraftGuy** [comment]
Expletives! :) 

In **assets/css/main.scss**, I tried this:

```css
---
# Only the main Sass file needs front matter (the dashes are enough)
---

@charset "utf-8";

main {
    max-width: $100%;
}

@import "minimal-mistakes/skins/{{ site.minimal_mistakes_skin | default: 'default' }}"; // skin
@import "minimal-mistakes"; // main partials
```

and this:

```css
---
# Only the main Sass file needs front matter (the dashes are enough)
---

@charset "utf-8";

@import "minimal-mistakes/skins/{{ site.minimal_mistakes_skin | default: 'default' }}"; // skin
@import "minimal-mistakes"; // main partials

main {
    max-width: $100%;
}
```

and this:

```css
---
# Only the main Sass file needs front matter (the dashes are enough)
---

@charset "utf-8";

max-width: $100%

@import "minimal-mistakes/skins/{{ site.minimal_mistakes_skin | default: 'default' }}"; // skin
@import "minimal-mistakes"; // main partials
```

and this:

```css
---
# Only the main Sass file needs front matter (the dashes are enough)
---

@charset "utf-8";

@import "minimal-mistakes/skins/{{ site.minimal_mistakes_skin | default: 'default' }}"; // skin
@import "minimal-mistakes"; // main partials

max-width: $100%
```

and this:

```css
---
# Only the main Sass file needs front matter (the dashes are enough)
---

@charset "utf-8";

@import "minimal-mistakes/skins/{{ site.minimal_mistakes_skin | default: 'default' }}"; // skin
@import "minimal-mistakes"; // main partials

max-width: $100%; // added semicolon
```

and they all failed!

----

FINALLY, THIS WORKED!

```css
---
# Only the main Sass file needs front matter (the dashes are enough)
---

@charset "utf-8";

max-width: $100%; // added semicolon

@import "minimal-mistakes/skins/{{ site.minimal_mistakes_skin | default: 'default' }}"; // skin
@import "minimal-mistakes"; // main partials
```

**Comment by ElectricRCAircraftGuy** [comment]
Alrighty, here's what I've got so far to fix both the font and the max width.

My new **assets/css/main.scss**:

```css
---
# Only the main Sass file needs front matter (the dashes are enough)
---

@charset "utf-8";

/*
GS: to override any SASS variables in "_variables.scss", you must place new values here, BEFORE
the `@import` statements, as that is the point where the variables are used!
See: https://github.com/mmistakes/minimal-mistakes/issues/2278#issuecomment-541484035
*/

/*
- Let's override the stinking `$max-width` variable in "_variables.scss", which controls the
  maximum width of the entire content on the screen, as it is currently set to `$x-large`, which
  is only 1280px, which is too small to take up the entire width on a standard
  1920 (px wide) x 1080 (px tall) display, and WAY TOO SMALL for a 3840 x 2160 4k display!
This is what is currently in "_variables.scss" under the "Breakpoints" section:

        $small: 600px !default;
        $medium: 768px !default;
        $medium-wide: 900px !default;
        $large: 1024px !default;
        $x-large: 1280px !default;
        $max-width: $x-large !default;

Override $max-width (don't forget the semicolon!):
*/
$max-width: 100%;


@import "minimal-mistakes/skins/{{ site.minimal_mistakes_skin | default: 'default' }}"; // skin
@import "minimal-mistakes"; // main partials


/*
GS: override any CSS with new CSS styles AFTER the `@import "minimal-mistakes";` line just above!
See: https://github.com/mmistakes/minimal-mistakes/issues/1219#issuecomment-326809412
Anything you place after this point will therefore "cascade and override" the previous CSS styles.
*/

/*
GS: Decrease font sizes of the entire website.
Defaults for small, medium, large, and x-large screens are:
16, 18, 20, and 22px, in that order. All other font sizes are "em"
[typography unit](https://en.wikipedia.org/wiki/Em_(typography)) multipliers of these pixel
(px) values, and are therefore relative to and changed by these singular pixel values.
See: https://github.com/mmistakes/minimal-mistakes/issues/1219#issuecomment-326809412
- It looks like the screen pixel sizes to move into each new "size" category are defined in
  the "Breakpoints" section of "_variables.scss"?
*/
html {
  font-size: 12px; // change to whatever

  @include breakpoint($small) {
    font-size: 12px; // change to whatever
  }

  @include breakpoint($medium) {
    font-size: 14px; // change to whatever
  }

  @include breakpoint($large) {
    font-size: 16px; // change to whatever
  }

  @include breakpoint($x-large) {
    font-size: 18px; // change to whatever
  }
}
```

Next thing to fix is the syntax highlighting so I can get light-colored github-like or stack overflow-like highlighting, which I prefer.

Taking a look here now: https://github.com/mmistakes/minimal-mistakes/issues/2278#issuecomment-541484035
