### DISCUSSION TITLE
I'm misssing the sidebar on my page

### DISCUSSION THREAD

**Discussion by daedalus2713** [mmistakes/minimal-mistakes#2746] [Q&A] [answered]
I can not enable the sidebar like this page: https://mmistakes.github.io/minimal-mistakes/post/post-future-date/:
My config.yml:
```yml
# themes
remote_theme             : "mmistakes/minimal-mistakes@4.21.0"
minimal_mistakes_skin    : "dark" # "default", "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Site settings
title                    : "DAEDALUS2713"
logo                     : "https://avatars3.githubusercontent.com/u/75079751?s=460&u=37dce84eac023e7ead3880fd13488bca0a8867d7&v=4"
name                     : "daedalus2713"
description              : "Personal blog"
repository               : "https://github.com/daedalus2713"

# Site Author
author:
  name             : "daedalus2713"
  avatar           : https://avatars3.githubusercontent.com/u/75079751?s=460&u=37dce84eac023e7ead3880fd13488bca0a8867d7&v=4
  bio              : "I am an **amazing** person."
  location         : "Somewhere"
  email            : "daedalus.2713@gmail.com"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/daedalus2713"

# plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-include-cache

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: false
      comments: # true
      share: false
      related: false

```
![image](https://user-images.githubusercontent.com/75079751/100823970-dc870e80-3487-11eb-9a08-a23e0d982737.png)

Can some one help me to enable it ?
