### DISCUSSION TITLE
how 1em is calculated in this theme

### DISCUSSION THREAD

**Discussion by luweizheng** [mmistakes/minimal-mistakes#2832] [Q&A] [answered]
sorry for this question which seems stupid...
I just wonder how 1em is calculated in this theme. 
Is is based on:

```css
html {
    font-size: 16px;
}
```

in _reset.scss? or a combination of the current browser users are using and the width of their screens?

in _page.scss I find code define the font size by:

```css
.page__content {
  p,
  li,
  dl {
    font-size: 1em;
  }
}
```

If I want to change the whole site's font-size, just override this property?

What is the best and quickest way to set the base font-size?
