### DISCUSSION TITLE
External link icon

### DISCUSSION THREAD

**Discussion by dlech** [mmistakes/minimal-mistakes#2934] [Show and tell]
This is a nice little hack to add external link icons to the navigation without modifying the theme.

```scss
.greedy-nav a[href^="https"]::after {
    font-family: "Font Awesome 5 Free"; 
    font-weight: 900;
    font-size: small;
    content: "\00a0\f35d";
    vertical-align: super;
}
```
