### DISCUSSION TITLE
social icons under profile don't allign

### DISCUSSION THREAD

**Discussion by RinkiyaKeDad** [mmistakes/minimal-mistakes#2973] [Q&A] [answered]
## Environment

- Minimal Mistakes version: 4.23.0
- Ruby gem or remote theme version: `minimal-mistakes-jekyll (4.23.0, 4.22.0)` -> output from `gem list`
- Jekyll version: 4.2.0
- Git repository URL: https://github.com/RinkiyaKeDad/rinkiyakedad.github.io
- GitHub Pages hosted (if yes provide URL to site): arshs.tech
- Operating system: MacOS 11.3.1

## Expected behavior
Social Icons under the profile should be alligned.

## Steps to reproduce the behavior
By default.
<img width="174" alt="Screen Shot 2021-05-24 at 11 41 05 AM" src="https://user-images.githubusercontent.com/56963264/119304975-ad5a9880-bc85-11eb-8c54-e11fa5622404.png">

**Comment by iBug** [comment, marked as answer]
You need to add `fa-fw` to the classes.

<https://fontawesome.com/how-to-use/on-the-web/styling/fixed-width-icons>

**Comment by RinkiyaKeDad** [comment]
I think I have done that. Here's the code from my `_config.yml`:

```
links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:arshsharma461@gmail.com"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/RinkiyaKeDad"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/RinkiyaKeDad"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/arsh4/"
    - label: "Dev.to"
      icon: "fab fa-dev"
      url: "https://dev.to/rinkiyakedad"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/rinkiya.ke.dad"
```
