### DISCUSSION TITLE
Allow nested entries in main navigation

### DISCUSSION THREAD

**Discussion by Andre601** [mmistakes/minimal-mistakes#3003] [Ideas]
Wehn using navigation I tried to setup the following structure:
```yaml
main:
  - title: "Home"
    url: /
  - title: "Downloads"
    url: /downloads/
  - title: "Panel"
    url: "https://secure.5zigreborn.eu/panel"
  - title: "Status"
    url: "https://status.5zigreborn.eu/"
  - title: "FAQ"
    url: /faq/
  - title: "Docs"
    url: "https://docs.5zigreborn.eu"
  - title: "Changelogs"
    children:
      - title: "v1.14.0"
        url: /changelogs/3.14.0
      - title: "v1.13.0"
        url: /changelogs/3.13.0
```

I wanted to do this because A) having changelogs directly added as nested entries in the nav makes it fit better imo and B) the [Layouts page](https://mmistakes.github.io/minimal-mistakes/docs/layouts/#custom-sidebar-navigation-menu) mentions that you can make nested entries for the sidebar.

While testing this with the main (top) navbar did I realize that you can't set nested entries, or at the very least it doesn't work the way I tried.

This is why I now want to suggest, to allow us defining nested entries which, when hovered over the parent section, would be revealed to us.
Maybe even allow us to have both the parent AND children link to sections, so that in my case above, I could link to the main download page, but also to sections of it like latest stable and latest dev/bleeding build.
