### DISCUSSION TITLE
Adding gallery caused page not found

### DISCUSSION THREAD

**Discussion by hhyleung** [mmistakes/minimal-mistakes#3031] [Q&A] [answered]
## Environment
- Minimal Mistakes version: remote theme
- Ruby gem or remote theme version: mmistakes/minimal-mistakes
- Jekyll version: remote theme
- Git repository URL: <https://github.com/hhyleung/hhyleung.github.io>
- GitHub Pages hosted (if yes provide URL to site): <https://hhyleung.github.io/photography>
- Operating system: MacOS

## Expected behavior
Having galleries on a page as described at <https://mmistakes.github.io/minimal-mistakes/post%20formats/post-gallery/>

## Steps to reproduce the behavior
Followed the documentation and arrived the code below. Upon commit the page became not found. Removing the galleries will recover the page, hence it is believed that the issue is due to the galleries.
```
---
title: "Photography"
layout: single
permalink: /photography.html
highlight:
  - url: /assets/images/edinburghSunrise.jpg
    image_path: /assets/images/edinburghSunrise.jpg
    alt: "Portobello Beach, Edinburgh, Scotland"
    title: "Portobello Beach, Edinburgh, Scotland"
  - url: /assets/images/doverCliff.jpg
    image_path: /assets/images/doverCliff.jpg
    alt: "White Cliffs of Dover, UK"
	title: "White Cliffs of Dover, UK"
wildlife:
  - url: /assets/images/yorkshireLamb.jpg
    image_path: /assets/images/yorkshireLamb.jpg
    alt: "Yorkshire Dales, UK"
    title: "Yorkshire Dales, UK"
  - url: /assets/images/glencoeDeer.jpg
    image_path: /assets/images/glencoeDeer.jpg
    alt: "Glencoe, Scotland"
    title: "Glencoe, Scotland"
  - url: /assets/images/callanderCoo.jpg
    image_path: /assets/images/callanderCoo.jpg
    alt: "Callander, Scotland"
	title: "Callander, Scotland"
landscape:
  - url: /assets/images/zennorCoast.jpg
    image_path: /assets/images/zennorCoast.jpg
    alt: "Zennor, Cornwall, UK"
    title: "Zennor, Cornwall, UK"
  - url: /assets/images/hunstantonCliff.jpg
    image_path: /assets/images/hunstantonCliff.jpg
    alt: "Hunstanton Cliffs, Norfolk, UK"
    title: "Hunstanton Cliffs, Norfolk, UK"
---

{% include gallery id="highlight" class="full" layout="half" %}
{% include gallery id="wildlife" class="full" %}
{% include gallery id="landscape" class="full" layout="half" %}
```
