### DISCUSSION TITLE
How to make text more mobile-friendly?

### DISCUSSION THREAD

**Discussion by Rainymood** [mmistakes/minimal-mistakes#3044] [Q&A] [answered]
Hi,

I love minimal mistakes and have been using it for multiple years.

I would love to know how to make the text more mobile-friendly. 

What I mean by this is illustrated in the next picture:

![image](https://user-images.githubusercontent.com/2186137/124494939-c04da600-ddb7-11eb-82f9-9b1bb15da14e.png)

On the left-hand side we see my website viewed on an iPhone X, on the right-hand side we see the website of [Brian Lovin](www.brianlovin.com). 

How do I make my text (only on mobile) look more like the text on the right?

I run minimal mistakes as a remote theme through Github pages and this is what my `assets/css/main.scss` looks like:

```css

html {
  font-size: 12px; // change to whatever

  @include breakpoint($small){
    font-size: 12px; // change to whatever
  }

  @include breakpoint($medium) {
    font-size: 14px; // change to whatever
  }

  @include breakpoint($large) {
    font-size: 16px; // change to whatever
  }

  @include breakpoint($x-large) {
    font-size: 18px; // change to whatever
  }
}
```

**Comment by Rainymood** [comment]
![image](https://user-images.githubusercontent.com/2186137/124496787-2affe100-ddba-11eb-8e22-40d31cee1631.png)

```css
element.style {
}
html {
    font-size: 20px;  // messing around with this
}
html {
    position: relative;
    min-height: 100%;
}
```

It turns out that messing around with `font-size` manually (i.e. putting it to 20) achieves (sort of) the effect that I desire. But how do I do this only on mobile?
