### DISCUSSION TITLE
home layout - thumbnail images

### DISCUSSION THREAD

**Discussion by pmatulis** [mmistakes/minimal-mistakes#3061] [Q&A] [answered]
I've got a page for displaying posts using the `home` layout:

``` yaml
---
layout: home
title: "Posts"
permalink: /posts/
entries_layout: grid
classes: wide
---
```

It's working, but I was wondering if it's possible to associate a thumbnail image to each post's index entry to help spice things up?
