### DISCUSSION TITLE
Heroku-hosted Staticman

### DISCUSSION THREAD

**Discussion by pmatulis** [mmistakes/minimal-mistakes#3066] [Q&A]
I'm all puffed out (research and testing fatigue) after reading dozens of internet blogs and GitHub bug reports on how to get my GitHub Pages Jekyll site (running Minimal Mistakes theme) and a Heroku-hosted Staticman to work. Although this may not be MM-specific there may be theme-specific configuration items involved.

Since I'm not using a GitHub app I understand I am constrained to using Staticman v2.

Somehow I need to provide my Heroku app endpoint in `_config.yml` but from the Minimal Mistakes documentation **for v2** I don't see how that can be achieved:

``` yaml
repository  : # GitHub username/repo-name
comments:
  provider  : "staticman_v2"
  staticman:
    branch    : "master"
```

Must I use a GitHub app (and Staticman v3) in order to get a Heroku-hosted Staticman to work?
