### DISCUSSION TITLE
Unable to resize the logo size in masthead

### DISCUSSION THREAD

**Discussion by Arash-Sabet** [mmistakes/minimal-mistakes#3149] [Q&A]
I have a 240x240 px logo but it's displayed too small! I tried to make sense of [this solution](https://github.com/mmistakes/minimal-mistakes/issues/2185) but I could not conclude anything! Could you please direct me to the exact place where I can make the necessary modifications?

I am using the latest version of minimal mistake and your help is appreciated.

**Comment by Arash-Sabet** [comment]
This is what I did but I'm not sure if it's the right approach:

```css
.site-logo img {
   max-height:12rem
}
```

**Comment by iBug** [comment]
This should work:

```css
.site-logo img {
  height: 2rem;
}
```
