### DISCUSSION TITLE
How can I change the color of the hamburger menu icon?

### DISCUSSION THREAD

**Discussion by boozedog** [mmistakes/minimal-mistakes#3244] [Q&A] [answered]
I've been messing around with $navicon-link-color-hover but that didn't work.

I'm trying to change the color of the hamburger icon ... any suggestions?

Thanks!

**Comment by mmistakes** [comment, marked as answer]
Here is the relevant CSS, https://github.com/mmistakes/minimal-mistakes/blob/641ca6f3d8cd8fb0ae24e4f77b2e62a44a65e53b/_sass/minimal-mistakes/_utilities.scss#L333-L352

The navicon lines are colored by filling in their background with the variable `$primary-color`. [Override that variable](https://mmistakes.github.io/minimal-mistakes/docs/stylesheets/#customizing) and it will change the icon's color.

Note: changing the primary color may have unintended results in the rest of the theme. If you just want to change the navicon color I'd suggest adding the following CSS to your local `assets/css/main.scss` file:

```scss
---
# Only the main Sass file needs front matter (the dashes are enough)
---

@charset "utf-8";

@import "minimal-mistakes/skins/{{ site.minimal_mistakes_skin | default: 'default' }}"; // skin
@import "minimal-mistakes"; // main partials

// Add custom CSS here
.navicon {
  background: $primary-color; // change color

  &:before,
  &:after {
    background: $primary-color; // change color
  }
}

.greedy-nav__toggle:hover {
  .navicon,
  .navicon:before,
  .navicon:after {
    background: mix(#000, $primary-color, 25%); // change color
  }
}
```
