### DISCUSSION TITLE
Comments not showing up on site hosted on github pages

### DISCUSSION THREAD

**Discussion by anotherlab** [mmistakes/minimal-mistakes#3303] [Q&A] [answered]
### What happened
- Minimal Mistakes version: 4.24.0
- Ruby gem or remote theme version:
- Jekyll version: 3.96.0
- Git repository URL: [anotherlab/anotherlab.github.io](https://github.com/anotherlab/anotherlab.github.io)
- Hosted on GitHub Pages (if yes provide URL to site): [anotherlab.github.io](https://anotherlab.github.io/)
- Operating system:

### Expected behavior
Added support to giscus in _config.yml

``` yaml
repository: "anotherlab/anotherlab.github.io"
comments:
  provider: "giscus"
  giscus:
    repo:                "anotherlab/anotherlab.github.io"
    repo-id:             "R_kgDOGhtM_w"
    category:            "Comments"
    category-id:         "DIC_kwDOGhtM_84CAZ93"
    mapping:             "pathname"
    reactions-enabled:    "1"
    theme:               "light"
    crossorigin:         "anonymous"    
```

Comments are enabled on posts 

``` yaml
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
```

Installed giscus app into my GitHub account and gave it access to my GitHub Pages repo. Comments are not showing up on my site.  I can see that the giscus script has been injected into the <body> of the posts

``` js
    <script>
  'use strict';

  (function () {
    var commentContainer = document.querySelector('#giscus-comments');

    if (!commentContainer) {
      return;
    }

    var script = document.createElement('script');
    script.setAttribute('src', 'https://giscus.app/client.js');
    script.setAttribute('data-repo', 'anotherlab/anotherlab.github.io');
    script.setAttribute('data-repo-id', '');
    script.setAttribute('data-category', '');
    script.setAttribute('data-category-id', '');
    script.setAttribute('data-mapping', 'pathname');
    script.setAttribute('data-reactions-enabled', '1');
    script.setAttribute('data-theme', 'light');
    script.setAttribute('crossorigin', 'anonymous');

    commentContainer.appendChild(script);
  })();
</script>
```

On the rendered pages for the posts, I am not seeing a div being added with an id of "giscus-comments". If I manually add one to a post, it will appear.  Is this div supposed to be auto-generated or should I add it to a layout file?
