### DISCUSSION TITLE
Conflict: tags shared by multiple files

### DISCUSSION THREAD

**Discussion by jlconlin** [mmistakes/minimal-mistakes#3324] [Q&A] [answered]
I'm trying to use `jekyll-archives` to help me generate tag pages. According to the [documentation](https://mmistakes.github.io/minimal-mistakes/docs/configuration/#archive-settings) I have the following in my `_config.yml`

```yml
plugins:
  - jekyll-archives
 
theme: minimal-mistakes-jekyll

tag_archive:
  type: jekyll-archives
  path: /tags/
category_archive:
  type: jekyll-archives
  path: /categories/

jekyll-archives:
  enabled:
    - categories
    - tags
  layouts:
    category: archive-taxonomy
    tag: archive-taxonomy
  permalinks:
    category: /categories/:name/
    tag: /tags/:name/
```

However, I get the following message (for every tag on my site):
```
          Conflict: The following destination is shared by multiple files.
                    The written file may end up with unexpected contents.
                    /path/to/jekyll/dir/_site/tags/manager/index.html
                     - tags/manager/index.html
                     - tags/manager/index.html
```
It seems that minimal-mistakes and Jekyll-archives are both trying to write to the same file and Jekyll isn't happy. 

I'm not sure what I'm doing wrong. Please advise.
