### DISCUSSION TITLE
How to set a separate header font?

### DISCUSSION THREAD

**Discussion by Davidyao217** [mmistakes/minimal-mistakes#3559] [Q&A]
I want to set a different font just for the title on the header overlay image on the splash layout (https://codepen.io/DirkWeber/pen/YzBYWY), but I can't figure out where the font is set.

Thanks!

**Comment by iBug** [comment]
You can just provide your own CSS overrides for the header overlay part like this.

```css
.layout--splash .page__hero--overlay {
  font-family: serif;
}
```
