### DISCUSSION TITLE
How to create separate tag pages?

### DISCUSSION THREAD

**Discussion by jlconlin** [mmistakes/minimal-mistakes#3664] [Q&A] [answered]
I would like to have a separate page generated for every tag in my blog. I'm sure this is easy to do, but I can't figure out the magic incantation.

I have the following in my `_config.yml`
```yml
theme: minimal-mistakes-jekyll

tag_archive:
  type: jekyll-archives
  path: /tags/
category_archive:
  type: jekyll-archives
  path: /categories/

jekyll-archives:
  enabled: []
  layouts:
    category: archive-taxonomy
    tag: archive-taxonomy
  permalinks:
    category: /categories/:name/
    tag: /tags/:name/
```

In `_pages/tags.md` I have:
```markdown
---
title: "Tags"
permalink: /tags/
layout: tags
regenerate: false
author_profile: true
---
```

Instead of getting different pages, I have just one very long page with links to different sections in the page. While this is nice, I would prefer to have different pages. Please advise.
