### DISCUSSION TITLE
How to avoid breadcrumb navigation with jekyll-archives being encoded into UrlEncode format?

### DISCUSSION THREAD

**Discussion by boh5** [mmistakes/minimal-mistakes#3816] [Q&A]
My `_config.yml` of breadcrumb navigation:
```yaml
breadcrumbs: true
category_archive:
  type: jekyll-archives
  path: /categories/
tag_archive:
  type: jekyll-archives
  path: /tags/
jekyll-archives:
  enabled:
    - categories
    - tags
  layouts:
    category: archive-taxonomy
    tag: archive-taxonomy
  permalinks:
    category: /categories/:name/
    tag: /tags/:name/
```
And My post have a chinese category and a english category
```liquid
categories:
  - 学习笔记
  - redis
```
But I get breadcrumb navigation like this
![img](https://i.imgur.com/oORdxIn.png)
The category page shows correctly
![img](https://i.imgur.com/8TZLo1L.png)
The english category shows correctly， but chinese category shows in url encode.
How could I avoid this? THX
