### DISCUSSION TITLE
Hide footer

### DISCUSSION THREAD

**Discussion by malpa222** [mmistakes/minimal-mistakes#3918] [Q&A]
Is there a setting in `_config.yml` to disable to footer? I don't really want it on my page, and I'm not sure how to override the default `.scss` file.

**Comment by LindseyB** [comment]
Unfortunately I think the only way to do this right now is with custom css, but it shouldn't be too hard, you just need to create the following file: 

`
assets/css/main.scss` 

with the following content: 

```scss
.footer {
  display: none;
}

@import "minimal-mistakes/skins/{{ site.minimal_mistakes_skin | default: 'default' }}"; // skin
@import "minimal-mistakes"; // main partials
```
