### DISCUSSION TITLE
How to have a RSS feed only for one Category

### DISCUSSION THREAD

**Discussion by hhlp** [mmistakes/minimal-mistakes#3957] [Q&A]
I've read the jenkyll-feed and I've found this configuration but not works for me

``` 
atom_feed:   ---->       also testing feed:
  categories:
    - Blog
  tags: false
``` 

Refrerences: https://github.com/jekyll/jekyll-feed

Regards.,
