### DISCUSSION TITLE
Better localization for multilingual sites

### DISCUSSION THREAD

**Discussion by DavidGomez-dev** [mmistakes/minimal-mistakes#4103] [Ideas]
Hi there,

I am wondering if would make more sense to localizing the labels based on a page variable, such as page.lang and fallback to site.locale

For example, instead of

`{{site.data.ui-text[site.locale].categories_label | default: "Categories:" }}`

using something like this

`{{site.data.ui-text[page.lang].categories_label | default: site.data.ui-text[site.locale].categories_label  }}`

So, this allows easily to have sites with same pages in different languages.

**Comment by nenge123** [comment]
you can ,

js add attr `lang`
```
<html lang="zh-hans">
....<p lang="en">hello</p><p lang="zh-hans">你好</p>
```

```css
html[lang=zh-hans]{
p:not([lang~=zh-hans]){
    display:none
}
}
html:not([lang~=zh-hans]){
p:[lang=zh-hans]{
    display:none
}
}
```
