### DISCUSSION TITLE
Does the top menu (masthead) support submenus?

### DISCUSSION THREAD

**Discussion by raubvogel** [mmistakes/minimal-mistakes#4193] [Q&A]
So I created a `test _data/navigation.yml` file 
```
main:
  - title: "About"
    url: /about/
  - title: "Stuff"
    children:
      - title: "Blog"
        url: /stuff/blog/
  - title: "Categories"
    url: /categories/
  - title: "Tags"
    url: /tags/
```
When I reload the site (I am testing it locally so I have to `jekyll serve` it again) I do not see the sub/children menu; clicking on `stuff` takes me back to the home page. So I looked into one of the generated pages (in `_site`); here is how the menu looks like there:
```
        <ul class="visible-links"><li class="masthead__menu-item">
              <a href="/about/">About</a>
            </li><li class="masthead__menu-item">
              <a href="">Stuff</a>
            </li><li class="masthead__menu-item">
              <a href="/categories/">Categories</a>
            </li><li class="masthead__menu-item">
              <a href="/tags/">Tags</a>
            </li></ul>
```
Note that `Stuff` has no url associated with it, which makes sense and explains why it is going to the homepage. But, no children menu
