### DISCUSSION TITLE
Sidebar nav does not appear

### DISCUSSION THREAD

**Discussion by DGrv** [mmistakes/minimal-mistakes#4515] [Q&A]
Hi,

I do not find why my sidebar is not appearing.

My goal is exactly like the example here https://mmistakes.github.io/minimal-mistakes/docs/quick-start-guide/

Here what I have:

_data/navigation.yml:

```
code:
  - title: bonjour
    children:
      - title: "Code"
        url: /code/code2/
      - title: "Batch"
        url: /code/batch/
      - title: "R"
        url: /code/r/
      - title: "FFmpeg"
        url: /code/ffmpeg/"
      - title: "Youtube-dl"
        url: /code/youtube-dl/
      - title: "Python"
        url: /code/python/
      - title: "Other"
        url: /code/other/

```

_config.yml

```
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  # _code
  - scope:
      path: ""
      type: code
    values:
      layout: single
      read_time: false
      author_profile: true
      share: false
      comments: false
      sidebar:
        nav: code
```

folder:

code/
    batch.md
    code2.md
    ffmpeg.md
    leaflet.md
    other.md
    python.md
    r.md
    youtube-dl.md

Repository here : https://github.com/DGrv/dorian.gravier.github.io

Any idea what I am doing wrong ?
