### DISCUSSION TITLE
Adding gallery support to my personal blog

### DISCUSSION THREAD

**Discussion by TrigonaMinima** [mmistakes/minimal-mistakes#4582] [Q&A]
I am looking into adding the gallery support from minimal-mistakes theme to my blog. I added the js, CSS to my assets. I also created the template under the `_layouts` directory. It is still not working. Could someone pls help me with the steps. I am not sure what I am missing in the process.

**Comment by daixtrose** [comment]
For me, it worked by creating a file with a canonical name (`2022-05-01-images-of-the-world.md`) in `_posts` with the following content (redacted):

```
---
title: "Images of the World Around Me"
date: 2022-05-01
categories:
  - nice and beautiful
tags:
  - fotos
gallery:
  - url: /assets/images/DSC_0211_DxO.jpg
    image_path: /assets/images/DSC_0211_DxO.jpg
    alt: "Tyrannosaurus Rex Skeleton"
    title: "Tyrannosaurus Rex"
  - url: /assets/images/IMG_0231_small.jpg
    image_path: /assets/images/IMG_0231_small.jpg
    alt: "Staircases"
    title: "Staircases"
# ... and so on
  - url: /assets/images/RTWH_Main_Building_DxO.jpg
    image_path: /assets/images/RTWH_Main_Building_DxO.jpg
    alt: "assets/images/RTWH_Main_Building_DxO.jpg"
    title: "assets/images/RTWH_Main_Building_DxO.jpg"  

---    

{% include gallery id="gallery" class="full" caption="some caption" %}
```

Does this help?
