### DISCUSSION TITLE
Font Awesome icon not appearing in footer

### DISCUSSION THREAD

**Discussion by raacampbell** [mmistakes/minimal-mistakes#4712] [Q&A] [answered]
I want to add an FA link icon before a link in my footer. So in `_config.yml` I have added:

```yaml
    - label: "My text here"
      icon: "fab fa-fw fa-link"
      url: "https://www.someurl.com/"
```
The link appears in my footer but the space where the icon ought to appear is empty. Out of desperation I tried adding the following to `_utilities.scss` but it didn't help.

```yaml
  /* HACK  */
  .fa-link {
    color: red;
  }
```

Any ideas what is going on?
