### DISCUSSION TITLE
Google Analytics problem

### DISCUSSION THREAD

**Discussion by sachinkmohan** [mmistakes/minimal-mistakes#4832] [Q&A]
Hi Michael & Community! 
Love the template totally! Thanks a ton!

I have a problem

https://github.com/sachinkmohan/easymalayalam-site/pull/1/files

I set it up as below

```
analytics:
  provider: "google-gtag" # false (default), "google", "google-universal", "google-gtag", "custom"
  google:
    tracking_id: "G-5PBY97M4CY"
    anonymize_ip: # true, false (default)
```
I thought `page.analytics` was causing issue. So I removed that part as in the PR.

But I am not able to see gtag on my website
![image](https://github.com/mmistakes/minimal-mistakes/assets/26414662/f9691e15-7c46-4bfa-855a-02bbd563a473)

What am I doing wrong? Could someone please help?
