### DISCUSSION TITLE
How can I create a custom layout?

### DISCUSSION THREAD

**Discussion by svaderia** [mmistakes/minimal-mistakes#4835] [Q&A] [answered]
I want a slightly modified version of the `home` layout. How can I achieve it? 
Since I want it just for a single page, I am okay to have a hacky way to modify the home layout.

(what I want is remove "Recent Posts" `<h3>` tag from the home layout)

**Comment by iBug** [comment, marked as answer]
If you just want to hide some elements, consider using [custom classes](https://mmistakes.github.io/minimal-mistakes/docs/layouts/#layout-based-and-user-defined-classes) on that page, and hide those elements with [custom CSS](https://mmistakes.github.io/minimal-mistakes/docs/stylesheets/#customizing).

E.g.

```yaml
---
layout: home
classes:
  - hide-recent-posts
---
```

```scss
.hide-recent-posts .archive__subtitle {
  display: none;
}
```
