### DISCUSSION TITLE
Is there a way to mix links and static content in sidebar?

### DISCUSSION THREAD

**Discussion by kief** [mmistakes/minimal-mistakes#4971] [Q&A]
I'm playing around with sidebars in minimal-mistakes, and from what I can work out, I can have _either_ [custom sidebar content](https://mmistakes.github.io/minimal-mistakes/docs/layouts/#custom-sidebar-content) _or_ a [custom sidebar navigation menu](https://mmistakes.github.io/minimal-mistakes/docs/layouts/#custom-sidebar-navigation-menu), but not both in the same page.

I could probably achieve what I want with just custom content, but I can't seem to include links as custom content. I tried this:

```
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      sidebar:
        - title: "A sidebar item"
          text: Text in the sidebar
        - title: "A sidebar link"
          url: https://github.com
```

But the result is "A sidebar link" appears, but is not a link. Is there syntax to make this work?

**Comment by kief** [comment]
Figured it out. I made it work like this:

```
      sidebar:
        - title: "A sidebar image"
          image: /images/side.png
        - title: "Links and things"
          nav: links
```
