### DISCUSSION TITLE
Centering titles?

### DISCUSSION THREAD

**Discussion by tollqnd** [mmistakes/minimal-mistakes#5153] [General]
Is there a way to centre the text of page titles? I'm referring to the "title" entry in the page frontmatter.

**Comment by iBug** [comment]
```css
.page__title {
  text-align: center;
}
```
