### ISSUE TITLE
Misaligned profile section

### ISSUE THREAD

**Issue by cosmincatalin** [mmistakes/minimal-mistakes#1008]
- [ ] This is a question about using the theme.
- [ ] This is a feature request.
- [x] I have updated all gems with `bundle update`.
- [x] I have tested locally with `bundle exec jekyll build`.
- [x] I believe this to be a bug with the theme --- not Jekyll, GitHub Pages or one of the bundled plugins.

---

## Environment informations

- **Minimal Mistakes version: 4.4.1** 
- **`jekyll` gem version: 3.4.3** 
- **Operating system: osX** 

---

## Expected behavior

The profile section should be placed under the main header and look the same in all browsers. It looks fine in Safari and Firefox, but not in Chrome posts, only in home. The profile section has a flash of movement as it positions itself underneath the header.

## Steps to reproduce the behavior

Chrome
<img width="428" alt="screen shot 2017-05-13 at 12 02 55" src="https://cloud.githubusercontent.com/assets/525590/26024617/467112f4-37d5-11e7-956c-323a87416d8c.png">

Firefox
<img width="331" alt="screen shot 2017-05-13 at 12 03 14" src="https://cloud.githubusercontent.com/assets/525590/26024619/578a7dd2-37d5-11e7-96ff-c5ed0c87494d.png">

Safari
<img width="326" alt="screen shot 2017-05-13 at 12 03 26" src="https://cloud.githubusercontent.com/assets/525590/26024620/5d653800-37d5-11e7-90c9-f4f17e2dd5a1.png">

`_config.yml`
```
encoding: UTF-8
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
highlighter: rouge
theme: minimal-mistakes-jekyll
gems:
  - jekyll-feed
  - jekyll-postfiles
exclude:
  - Gemfile
  - Gemfile.lock
permalink: /posts/:title/
read_time: true
defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      layout: "single"
      author_profile: true
      read_time: true
      comments: true
      share: true
author:
  name   : "John Doe"
  avatar : "/assets/images/IMG_0637.JPG"
  bio    : "My awesome biography constrained to a sentence or two goes here."
```
