### ISSUE TITLE
Reduce posts font size using _variables.scss

### ISSUE THREAD

**Issue by z0ph** [mmistakes/minimal-mistakes#1043]
Hi,

I'm trying to reduce the font size on my posts items using `_variables.scss` but it not applied properly. For me the font is too high.

![image](https://cloud.githubusercontent.com/assets/20846187/26668885/f62d6190-46ab-11e7-8603-6aa316369171.png)

[Detailled Screenshot](https://cl.ly/1r0i1U3V1s02/[72646bd2fdadc16deadd2ed6964bc709]_Image%202017-06-01%20at%209.26.05%20AM.png)

I've used this settings to review the change, but nothing happen on my posts items. The font it's still the same size (too big for me)

```css
/* type scale */
$type-size-1                : 0.50em !default;  // ~39.056px
$type-size-2                : 0.50em !default;  // ~31.248px
$type-size-3                : 0.50em !default;  // ~25.008px
$type-size-4                : 0.50em !default;  // ~20px
$type-size-5                : 0.50em !default;  // ~16px
$type-size-6                : 0.50em !default;  // ~12px
$type-size-7                : 0.50em !default;  // ~11px
$type-size-8                : 0.50em !default;  // ~10px
```
I've also tried to change `$doc-font-size` to `10`

I've tried to : 
`bundle exec jekyll clean`
`bundle exec jekyll build`

Without success yet. The font does not change in matters of size.

Maybe I made a minimal mistake :)

Thanks for your help.

- [X] This is a question about using the theme.
- [ ] This is a feature request.
- [X] I have updated all gems with `bundle update`.
- [X] I have tested locally with `bundle exec jekyll build`.
- [ ] I believe this to be a bug with the theme --- not Jekyll, GitHub Pages or one of the bundled plugins.
---

## Environment informations

- **Minimal Mistakes version: 4.4.1** 
- **`jekyll` gem version:** 
- **Operating system:** macOS

---

**Comment by mmistakes** [comment]
See [these lines](https://github.com/mmistakes/minimal-mistakes/blob/master/_sass/minimal-mistakes/_reset.scss#L11-L27) in `_reset.scss`. I'd leave the variable font sizes alone and instead adjust the sizes in the reset. The theme scales the font sizes up/down globally depending on the width of the screen.

```scss
html {
  /* apply a natural box layout model to all elements */
  box-sizing: border-box;
  background-color: $background-color;
  font-size: 16px;

  @include breakpoint($medium) {
    font-size: 18px;
  }

  @include breakpoint($large) {
    font-size: 20px;
  }

  @include breakpoint($x-large) {
    font-size: 22px;
  }
}
```
