### ISSUE TITLE
TOC - specify depth

### ISSUE THREAD

**Issue by Sciss** [mmistakes/minimal-mistakes#108]
I love the "toc" feature. Is it possible to filter out sections below a certain hierarchy level. For example, I can see that everything from `<h1>` to `<h4>` appears in the TOC (also, without any visual difference between these levels). I would like to specify the exclusion of `<h3>` or `<h4>`.

**Comment by RAlexeev** [comment]
Hello!

As I understood, to make visible hierarchy (more than 2 levels, as it is now) in Table Of Content in posts I should to edit `_sass/_navigation.scss`.
Could you show how to edit css to make TOC in this way? If it's not take a lot of time. Or in this case may be easy to use Javascript solution?

Thank you in advance!

**Comment by mmistakes** [comment]
You can do everything you want with CSS. You'll need to play with the `.toc__menu` styles in `_navigation.scss`. 

Just by adding `li > ul { padding-left: 1rem; }` and reducing the padding on `li ul > li a` I got it working.

```scss
.toc__menu {
  margin: 0;
  padding: 0;
  width: 100%;
  list-style: none;
  font-size: 0.8rem;

  a {
    display: block;
    padding: 0.5rem 1rem;
    color: $gray;
    font-size: $type-size-7;
    font-weight: bold;
    line-height: 1.5;
    border-bottom: 1px solid $border-color;

    &:hover {
      color: #000;
      background: $lighter-gray;
    }
  }

  > li:last-child {
    a {
      border-bottom: none;
    }
  }

  li ul > li a {
    padding-left: 1rem;
    font-weight: normal;
  }

  li > ul {
    padding-left: 1rem;
  }

  /* hide sub sub links on small screens*/
  li > ul li {
    display: none;

    @include breakpoint($medium) {
      display: block;
    }
  }
}
```

![toc](https://cloud.githubusercontent.com/assets/1376749/22828640/67755c32-ef6c-11e6-82c3-6fe9b11a5dd7.jpg)
