### ISSUE TITLE
Upgrade-friendly way of adjusting font sizes globally

### ISSUE THREAD

**Issue by ohadschn** [mmistakes/minimal-mistakes#1219]
It seems the recommended way of adjusting font sizes is [overriding `_reset.scss`](https://github.com/mmistakes/minimal-mistakes/issues/1043#issuecomment-305472620). However that file is pretty big and any override risks missing out on potential theme upgrades.

I was thinking maybe extract the [relevant lines](https://github.com/mmistakes/minimal-mistakes/blob/master/_sass/minimal-mistakes/_reset.scss#L11-L27) to their own CSS, or somehow expose the font sizes as variables (without overriding all of `_variables.scss` for similar reasons)?

Related: https://github.com/mmistakes/minimal-mistakes/issues/167, https://github.com/mmistakes/minimal-mistakes/issues/1184.

**Comment by mmistakes** [comment]
The way Jekyll handles `_sass` files you have to actually override the entire folder for it to accept any of your changes. So even if you override `_reset.scss` it won't take. And as you pointed out that's a large file and probably something you don't want to mess with if possible.

There's actually a simpler solution. Because of the way CSS works, you can add all of your custom overrides or "new" CSS to a single file, [`assets/css/main.scss`](https://github.com/mmistakes/minimal-mistakes/blob/master/assets/css/main.scss). 

This file has 2 lines, and the chances of it changing are slim to none since all it does is import another Sass partial that contains all of the theme's components and modules.

So what you can do is add any overriding/new CSS after the `@import minimal-mistakes;`, in your case:

```scss
@import "minimal-mistakes";

html {
  font-size: 16px; // change to whatever

  @include breakpoint($medium) {
    font-size: 18px; // change to whatever
  }

  @include breakpoint($large) {
    font-size: 20px; // change to whatever
  }

  @include breakpoint($x-large) {
    font-size: 22px; // change to whatever
  }
}
```

These will cascade and override the font-sizes declared earlier in the CSS.

**Comment by ohadschn** [comment]
Great stuff. BTW what is the difference between this and `type-size-X`?

**Comment by mmistakes** [comment]
Setting a font-size in pixels on the base `html` element is a common way of laying the foundation for responsive typography. Google around and you'll find some articles/blog posts that explain it better than I could.

The `type-size-x` variables are just `em` based sizes that act as multipliers of the base font sizes set in pixels.

For example when the screen size is less than `$medium` you have a base size of `16px`. If you set an element with `$type-size-4` or `1.25em` it's essentially doing `16 x 1.25` to give you `20px` size.

**Comment by ohadschn** [comment]
Ah, I see. So if one wants to make everything smaller categorically across the entire site, indeed it makes sense to alter the base pixel size as above, rather than change all the multipliers...

**Comment by mmistakes** [comment]
You got it.

**Comment by MV10** [comment]
@mmistakes I gather this won't work on a Github Pages site using `remote_template`?

> There's actually a simpler solution. Because of the way CSS works, you can add all of your custom overrides or "new" CSS to a single file, assets/css/main.scss.

**Comment by mmistakes** [comment]
@MV10 yes this should work. Your issue might be how styles are cascading and specificity depending on what you're trying to do . What does the content of your `/assets/css/main.scss` look like?

If you override any variables found in `_sass/_variables.scss` by placing them in your `main.scss` without the `!default` they will override.

And if you're adding CSS to `main.scss` it needs to appear after the includes so it overrides anything in the bundled CSS. That's how the "cascade" in CSS works, what comes last overrides what came before it.

**Comment by MV10** [comment]
Exactly as you demonstrated earlier but with different px sizes.

```scss
--- 
# Only the main Sass file needs front matter (the dashes are enough) 
--- 

@charset "utf-8";

@import "minimal-mistakes/skins/{{ site.minimal_mistakes_skin | default: 'default' }}"; // skin
@import "minimal-mistakes"; // main partials

// https://github.com/mmistakes/minimal-mistakes/issues/1219#issuecomment-326809412
html {
    font-size: 12px; // originally 16px
    @include breakpoint($medium) {
        font-size: 14px; // originally 18px
    }

    @include breakpoint($large) {
        font-size: 16px; // originally 20px
    }

    @include breakpoint($x-large) {
        font-size: 18px; // originally 22px
    }
}
```

![1](https://user-images.githubusercontent.com/794270/34490266-59938a34-efad-11e7-9dbf-5228259436a0.jpg)
