### ISSUE TITLE
Does the theme support tags?

### ISSUE THREAD

**Issue by darrenhaken** [mmistakes/minimal-mistakes#1230]
It would be nice if the post listing showed a list of tags underneath the post. Is there a way to support this?

**Comment by mmistakes** [comment]
The theme already does this and has for some time. It also displays a list of categories a post belongs to.

You can look at any of the [sample posts](https://mmistakes.github.io/minimal-mistakes/year-archive/) on the demo site to see them in action.

![image](https://user-images.githubusercontent.com/1376749/30162206-e09b3954-93a1-11e7-8f61-af9db23c8567.png)

**Comment by darrenhaken** [comment]
How do I add this to the blog? The samples show the rendered output not the source.

FYI I have included the Jekyll-archive gem and the following in the config.yml

```
#Archive settings
category_archive:
  type: jekyll-archives
  path: /categories/
tag_archive:
  type: jekyll-archives
  path: /tags/
jekyll-archives:
  enabled:
    - categories
    - tags
  layouts:
    category: archive-taxonomy
    tag: archive-taxonomy
  permalinks:
    category: /categories/:name/
    tag: /tags/:name/
```
The /tags page shows a directory structure from Jekyll but does not have a styled page. 
If I browse to a specific tag I can see a rendered page listing the articles.
