### ISSUE TITLE
Responsive header overlay images (srcset etc.)

### ISSUE THREAD

**Issue by ohadschn** [mmistakes/minimal-mistakes#1303]
Header images tend to be very large, often measuring several megabytes in size. Using [responsive images](https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Responsive_images), they can be reduced by significant factors for smaller displays (which tend to have slower connection too), [potentially to the tune of 90%](https://alistapart.com/article/responsive-images-in-practice).

Support for this could be added by something like
```yml
header:
  overlay_image: /assets/images/unsplash-image-1.jpg
  overlay_image_mid: /assets/images/unsplash-image-1-mid.jpg
  overlay_image_small: /assets/images/unsplash-image-1-small.jpg
```

(Of course if `mid`/`small` aren't specified, the behavior would stay the same as it is now)
