### ISSUE TITLE
Ability to disable left sidebar in single layout

### ISSUE THREAD

**Issue by kbl** [mmistakes/minimal-mistakes#1322]
[x] This is a question about using the theme.

## Environment informations
- **Minimal Mistakes version:** 4.6.0
- **Jekyll version:** 3.6.0
- **GitHub Pages hosted:** no
- **Operating system:** ubuntu 17.04

## Expected behavior
I'd like to remove the left column in single page layout whatsoever. I know that it's possible by removing author's bio etc. but then page content is really narrow. What I would like to achieve is to have "2 columns" - left, wider for ~2/3 of the page width for an article and right where toc is being inserted. How can I achieve such behaviour?

I've been fiddling with scss - I've been able to achieve it on some resolutions (mobile, x-large), but other looked just bad :( (large, 4k).

**Comment by mmistakes** [comment]
Have a search through the closed issues for things like "grid", "layout", "wide", etc.

I've covered this numerous times before with detailed directions on the Sass you need to modify to widen the main content container.

**Comment by mmistakes** [comment]
Related: #1265, #1155, #1298, #623, #384, #74

**Comment by kbl** [comment]
Thank you, indeed I must have been blind. If anybody is interested following changes did the job:
https://github.com/SamouczekProgramisty/samouczekprogramisty.github.io/commit/9f9c082568226b3b123bfd868bb3bee86e6960c5
https://github.com/SamouczekProgramisty/samouczekprogramisty.github.io/commit/f129d68e65018102727092b35d637186b36d4490

**Comment by charleshan** [comment]
Looks like lots of people are looking to do this. Maybe we could add a enable/disable sidebar feature.

**Comment by StefanoCecere** [comment]
indeed.. an "full-wide" class to be used when the author left column is disabled.

**Comment by JustinGrote** [comment]
For anyone coming here from google like I did, I just copied the `_sass/minimal-mistakes.scss` to my project and added this to the top of the file (preserving all the includes below it:
```css
article.page {
    float: left;
    width: 100%;
}
```

And changed my _config.yml defaults to not show author_profile on posts (`author_profile: false`)
```
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: false
      read_time: true
      comments: true
      share: true
      related: true
```

And now my article posts are "full wide"

@mmistakes, your documentation https://mmistakes.github.io/minimal-mistakes/docs/stylesheets/ says you have to copy the complete _sass folder, however I just changed the one file and it seems to all be working fine with Github Pages and Jekyll 3.8.5. Is this information still accurate?
