### ISSUE TITLE
Disqus-problem: Cannot read property 'appendChild' of null

### ISSUE THREAD

**Issue by exetico** [mmistakes/minimal-mistakes#1400]
- [x] This is a question about using the theme.
- [ ] This is a feature request.
- [ ] I believe this to be a bug with the theme.
- [x] I have updated all gems with `bundle update`.
- [x] I have tested locally with `bundle exec jekyll build`.

## Environment informations
- **Minimal Mistakes version:**  Gemfile.lock: `minimal-mistakes-jekyll (4.8.0)`
- **Jekyll version:** `jekyll 3.6.2`
- **GitHub Pages hosted:** No - Tested with localbuild, and hosted.
- **Operating system:** Linux (Both Linux Mint and Debian)
---
## Expected behavior

I'm trying to add Disqus to my site, but i recieve the same error as #318 where no solution is provided. I have tried with a lot of comment-configs just to make sure that i'm doing it right.

I recieve the following error in Chrome Debug Console:
```
embed.js:28 Uncaught TypeError: Cannot read property 'appendChild' of null
    at n (embed.js:28)
    at Object.p [as isSerif] (embed.js:28)
    at h.i.toJSON (embed.js:28)
    at Object.c.loadEmbed [as _loadEmbed] (embed.js:29)
    at embed.js:29
```
My config looks like:
```
comments:
  provider: disqus
  disqus:
    shortname: $$SHORTNAMETYPEDHERE$$ (Tested with, and without " ")

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: false
      read_time: true
      comments: true
      share: true
      related: true
      sidebar:
        nav: "docs"
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      comments: false
      author_profile: false
      sidebar:
        nav: "docs"
```

My site is made by creating a jekyll-site and use the few basic steps provided. The bulid is also tested on another version og Jekyll and Ruby, with no luck. Same error here.

## Screenshots
![image](https://user-images.githubusercontent.com/3549445/33999264-514e8d14-e0ea-11e7-91ed-c98ad92a5016.png)

# Sample file (and steps)
[test.tar.gz](https://github.com/mmistakes/minimal-mistakes/files/1559766/test.tar.gz)
The steps is a bit like..
```
jekyll new test
nano Gemfile
nano _config.yml
bundle install
nano _posts/2017-12-14-welcome-to-jekyll.markdown
mv index.md index.html
jekyll serve --host=localhost
```
It's tested in a few ways - buy i'm facing the same error everytime.

What am i doing wrong?

Btw - Thanks for the AWESOME BUILD :heart:
