### ISSUE TITLE
Adding `caption` attribute to `Feature Row` component

### ISSUE THREAD

**Issue by lmserrano** [mmistakes/minimal-mistakes#1440]
It would be nice to be able to use the `caption` attribute in the `Feature Row` component.

- [ ] This is a question about using the theme.
- [x] This is a feature request.
- [ ] I believe this to be a bug with the theme.
  - [ ] I have updated all gems with `bundle update`.
  - [ ] I have tested locally with `bundle exec jekyll build`.

----

Also, congratulations for all you've achieved with this theme, and thank you for all the work you've been continuously putting into it!

**Comment by mmistakes** [comment]
Thanks.

What would be the purpose of a caption on the feature row? Just to include a byline/credit under the image?

**Comment by lmserrano** [comment]
Yes, exactly. I wanted to use it to credit images similarly with what can be done with other components of your theme, without mixing it with the excerpt field.

**Comment by mmistakes** [comment]
This has been added and will be available in an upcoming release of the theme.

By adding `image_caption` to a feature row item you can caption the image.

```yaml
feature_row:
  - image_path: assets/images/unsplash-gallery-image-1-th.jpg
    alt: "placeholder image 1"
    title: "Placeholder 1"
    excerpt: "This is some sample content that goes here with **Markdown** formatting."
```
