### ISSUE TITLE
`minimal-mistakes-jekyll.gemspec`: invalid byte sequence in US-ASCII. Bundler cannot continue.

### ISSUE THREAD

**Issue by z0ph** [mmistakes/minimal-mistakes#1454]
Hi,

I've got an issue trying to `bundle install` with minimal-mistakes gemspec file:

```
[Container] 2018/01/06 14:18:38 Running command bundle install

[!] There was an error parsing `Gemfile`: 
[!] There was an error while loading `minimal-mistakes-jekyll.gemspec`: invalid byte sequence in US-ASCII. Bundler cannot continue.

# from /codebuild/output/src221007531/src/github.com/z0ph/blog/minimal-mistakes-jekyll.gemspec:14
# -------------------------------------------
# 
> spec.files = `git ls-files -z`.split("\x0").select do |f|
# f.match(%r{^(assets|_(data|includes|layouts|sass)/|(LICENSE|README|CHANGELOG)((\.(txt|md|markdown)|$)))}i)
# -------------------------------------------
. Bundler cannot continue.
```

I'm using this version of Ruby : 
`aws/codebuild/ruby:2.3.1`

And I'm running this build sequence : 

```
version: 0.1

phases:
  install:
    commands:
      - gem install jekyll bundler
  pre_build:
    commands:
      - bundle install
  build:
    commands:
      - echo "******** Building Jekyll site ********"
      - bundle exec jekyll build
      - echo "******** Uploading to S3 ********"
      - aws s3 sync _site/ s3://xxx
```

I've tried to iconv and recode the file, but it's in UTF-8.
And i've tried to add 

````
export LANG="C.UTF-8"
export LC_ALL="C.UTF-8"
````

Before the bundle install, without success

Thanks for your help,
zoph
