### ISSUE TITLE
Syntax highlighting - inconsistent line number spacing

### ISSUE THREAD

**Issue by MV10** [mmistakes/minimal-mistakes#1467]
I've noticed the horizontal padding between the line numbers and the code varies. What controls this? (I'm not sure if this is controlled by the theme, Jekyll, Liquid, or Ruby, so I'll start at the top!)

Normal-looking spacing:

![image](https://user-images.githubusercontent.com/794270/34897320-7b2a4c6c-f7bb-11e7-86cb-dbd05c14fe9d.png)

Crowded spacing (just a couple paragraphs down on the same page):

![image](https://user-images.githubusercontent.com/794270/34897354-a0a61fb6-f7bb-11e7-9eab-6e7fc677e468.png)

I see nothing unusual in the markdown:

![image](https://user-images.githubusercontent.com/794270/34897415-e1c45c6a-f7bb-11e7-893d-8a979142367e.png)

![image](https://user-images.githubusercontent.com/794270/34897437-f87a9596-f7bb-11e7-8ff7-749879a4ce9d.png)

**Comment by mmistakes** [comment]
It's controlled [via CSS](https://github.com/mmistakes/minimal-mistakes/blob/master/_sass/minimal-mistakes/_syntax.scss#L36).

You have this live somewhere? The theme styles place a rule to the right of the numbers that I'm not seeing in any of your screenshots.

I have several test examples and haven't seen the numbers get crowded like your examples above.

https://mmistakes.github.io/minimal-mistakes/markup-syntax-highlighting/

**Comment by MV10** [comment]
Live: https://mcguirev10.com
Repo: https://github.com/MV10/mv10.github.io

I know it's CSS, I wasn't sure where the styling gets applied. But good call, I meant to ask about the rule, too. I do also have this in the main.scss to add scrolling and some smaller body font sizes:

```css
pre.highlight {
    margin: 0;
    padding: 1em;
    max-height: 500px;
    overflow-y: scroll;
}
```

Looking at the calculated styles in chrome debug, the normal-looking one ends up with almost twice the PX width of the crowded version.

**Comment by mmistakes** [comment]
@MV10 The styling is different because the HTML output is different from using `{% highlight linenos %}`.

If you look at the HTML there are two columns: one for the line numbers the other the actual code. When using `{% highlight linenos %}` those class names are `.gutter` and `.code`

When globally enabling line numbers via Kramdown/Rouge like you have they're `.rouge-gutter` and `.rouge-code`, which is why the styling is off.

What probably needs to happen is for me to modify [`_includes/_syntax.scss`](https://github.com/mmistakes/minimal-mistakes/blob/master/_sass/minimal-mistakes/_syntax.scss#L33-L46) slightly to include these `.rouge-` specific classes. Unless there's a config you can set to tell them to use `.gutter` and `.code` instead of the `rouge-` prefixed ones.

```scss
    /* line numbers*/
    &.gutter,
    &.rouge-gutter {
      padding-right: 1em;
      width: 1em;
      color: $base04;
      border-right: 1px solid $base04;
      text-align: right;
    }

    /* code */
    &.code,
    &.rouge-code {
      padding-left: 1em;
    }
```
