### ISSUE TITLE
permalink after page filename

### ISSUE THREAD

**Issue by retorquere** [mmistakes/minimal-mistakes#1475]
- [x] This is a question about using the theme.
- [ ] This is a feature request.
- [ ] I believe this to be a bug with the theme.
  - [x] I have updated all gems with `bundle update`.
  - [x] I have tested locally with `bundle exec jekyll build`.

---

## Environment informations

- **GitHub Pages hosted:** yes
- **Operating system:** 

Is it possible to add a `permalink:` entry to the defaults for pages such that every `.md` file will just have the filename as the permalink?

**Comment by Sciss** [comment]
Have you tried something like

```
# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    value:
      permalink: /:basename/
```

?

**Comment by mmistakes** [comment]
You can set `permalink` to whatever you want, the theme doesn't care.

This is a Jekyll core feature, if you need help with setting that up its best to read the official [permalink docs](https://jekyllrb.com/docs/permalinks/) and ask any questions on the [Jekyll Talk forums](https://talk.jekyllrb.com/).

Closing as this isn't a theme issue.

**Comment by mmistakes** [comment]
`permalink: /:title/` will take any post or page and output just the title.

```
/_posts/2018-01-15-your-post.md  ~>  /your-post/index.html
about.md  ~>  /about/index.html
```

**Comment by retorquere** [comment]
thanks for the tips, and fair enough on this being a Jekyll question.

**Comment by retorquere** [comment]
I hesitate to ask now... but setting it as suggested by @Sciss I consistently don't get the css assets. I do get the js assets. Removing the permalink there gets me the css assets back. Otherwise it works flawlessly.

**Comment by mmistakes** [comment]
Pretty sure `permalink: /:basename/` isn't a valid key. I tried it and it throws all kinds of Ruby errors and Jekyll doesn't build.

Use `permalink: /:title/` instead like I suggested above.

```yaml
# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    value:
      permalink: /:title/
```

**Comment by Sciss** [comment]
Yes, sorry it seems `:basename` only works for "pages" but not "documents".

**Comment by retorquere** [comment]
I only have pages; my _config looks like

```
remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-default-layout
  - jekyll-github-metadata
  - jekyll-optional-front-matter
  - jekyll-readme-index
  - jekyll-redirect-from
  - jekyll-relative-links
  - jekyll-remote-theme
  - jekyll-titles-from-headings

include: ["_pages"]

defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
      permalink: /:title/

_titles_from_headings:
  enabled:     true
  strip_title: false
  collections: false
```

if I use `:title` I get a single directory called `:title` that has:

* index.css
* index.html
* index.js
* index.yml

if I use `:basename` I get a directory per page each with an `index.html` as expected, but no css in the assets dir.

If I omit the permalink, the site is generated as expected in the `_pages` output directory, but I'd really prefer to have the pages appear in the root.
