### ISSUE TITLE
Creating Collections: Unable to run bundle exec jekyll serve

### ISSUE THREAD

**Issue by havesomeleeway** [mmistakes/minimal-mistakes#1492]
- [x] This is a question about using the theme.
- [ ] This is a feature request or enhancement.
- [ ] I believe this to be a bug with the theme.
  - [x] I am using the latest version of the theme.
  - [x] I have updated all gems with `bundle update`.
  - [x] I have tested locally with `bundle exec jekyll build`.

---

## Environment informations

- **Jekyll version:** 3.6.2
- **GitHub Pages hosted:** yes

---

## Expected behavior

I'm trying to add a collection known as `_ux_design`. I am hoping that I can use this to show case a series of posts where I showcase some of the work that I've done.

So far, this is what I have done.

### At config.yml
```
  # ux_design
  - scope:
      path: ""
      type: ux_design
    values:
      layout: splash
      author_profile: false
share: true
```

```
# Collections
collections:
  ux_design:
    output: true
    permalink: /:collection/:path/
```

### At navigation.yml

```
main:
  - title: "About Me"
    url: /about/
  - title: "UX Design"
    url: /ux_design/
```
___

I have also created a folder called `_ux_design` with a file `test.md` within the folder.
![screen shot 2018-01-20 at 2 38 34 pm](https://user-images.githubusercontent.com/25948209/35180667-9f6bf2da-fdef-11e7-8cd8-fdf5e57422b3.png)

___

## Problem

When I try to run `bundle exec jekyll serve`, this error is returned
```
jekyll 3.6.2 | Error:  (/Users/leewei/havesomeleeway.github.io/_config.yml): did not find expected key while parsing a block mapping at line 1 column 1
```

I pushed my `_config.yml` into yamllint.com and as the error message indicates, there is an issue with line 1 column 1. 

This is line 1 column 1 of my `_config.yml`:
`remote_theme: "mmistakes/minimal-mistakes"`

I'm not sure why this is happening as I was able to run this locally before creating collections.

**Comment by mmistakes** [comment]
For starters your collection YAML is incorrect. `share: true` isn't indented properly, it should be indented exactly at the same level as the line above it.

```yaml
  # ux_design
  - scope:
      path: ""
      type: ux_design
    values:
      layout: splash
      author_profile: false
      share: true
```

I've seen this error before in the jekyll/jekyll issues and it always has to do with some bad line of YAML. Even though it passed linting there might be something in there it doesn't like.

Or it's your environment and/or an encoding issue with the file. Without a link to a public repo with the issue I can do a quick test to see if anything jumps out to me.

Either way I'm almost positive it isn't a theme issue you might want to search the [Jekyll issues](https://github.com/jekyll/jekyll/issues) or their [forum](https://talk.jekyllrb.com/) for help.

If it is determined it is a bug with the theme feel free to reopen.
