### ISSUE TITLE
No CSS in posts

### ISSUE THREAD

**Issue by ekofi** [mmistakes/minimal-mistakes#1503]
- [x] This is a question about using the theme.
- [ ] This is a feature request or enhancement.
- [ ] I believe this to be a bug with the theme.
  - [x] I am using the latest version of the theme.
  - [ ] I have updated all gems with `bundle update`.
  - [ ] I have tested locally with `bundle exec jekyll build`.

---

## Environment informations

  Please include theme version, Jekyll version, whether you are hosting with
  GitHub Pages, and the operating system you are on or tested with.

- **Minimal Mistakes version:*v4.9.0* 
- **Jekyll version:*3.7.2*
- **GitHub Pages hosted:*yes*
- **Operating system:*Windows* 

---

## Expected behavior

  No CSS in posts

## Steps to reproduce the behavior
-config
![my config](https://user-images.githubusercontent.com/30902468/35474352-3fff3ece-039e-11e8-9166-fdf6011d4dfe.png)
-post's config
![my post's config](https://user-images.githubusercontent.com/30902468/35474354-51f6c048-039e-11e8-8eaf-64a5a49d7ae7.png)
-no css or layout
![ka-boom! no css](https://user-images.githubusercontent.com/30902468/35474359-5edd1faa-039e-11e8-9f8d-56497aa5f979.png)

**Comment by mmistakes** [comment]
Doesn't look like you've set `url` in _config.yml properly.

Be sure that matches the location of your production site so the CSS, JS, and other assets resolve to the correct paths.

**Comment by ekofi** [comment]
@mmistakes i just forked minimal mistakes. i read quick-start guide and delete them:
.editorconfig
.gitattributes

Update:  I send another post, but it doesnt seem.

**Comment by mmistakes** [comment]
1. Check your `default` configs as it looks wrong to me. Remove the `_posts` line (or comment it out), it should be the following:

```yaml
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: # true
      share: true
      related: true
```

2. I don't advise forking the theme. Since you're hosting with GitHub Pages you should follow the "remote theme" instructions. 

3. You have quite a few of the theme's development only files still in your repo that should be removed:

https://mmistakes.github.io/minimal-mistakes/docs/quick-start-guide/#remove-the-unnecessary

4. Your `Gemfile` is going to give you problems as its the development version... another reason forking the theme directly isn't a good idea. It should [resemble this instead](https://github.com/mmistakes/minimal-mistakes/blob/master/docs/Gemfile). I suggest reading over the docs and follow them for how to edit/create a valid `Gemfile` for running a GitHub Pages friendly version of Jekyll locally.

https://mmistakes.github.io/minimal-mistakes/docs/installation/#install-dependencies

**Comment by ekofi** [comment]
Thanks, problem solved.

**Comment by pgyogesh** [comment]
I'm also facing something similar issue.

My Repo: https://github.com/pgyogesh/blog
Blog: http://pgyogesh.com/blog/

-Yogesh

**Comment by hkalant** [comment]
@pgyogesh The layout in your posts' front-matter should be `layout: single`, not `layout: post`.

Better yet, you can define the layout once in `config.yml` as following:

```
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: # true
      share: true
      related: true
```

So you don't have to include it in every single post.
