### ISSUE TITLE
Looking for best place to put small html menu file

### ISSUE THREAD

**Issue by Andy-ABTec** [mmistakes/minimal-mistakes#1524]
Hi, I'm messing around with adding a drop-down menu to one of the masthead items. I'm trying to make it template friendly with thoughts of a PR down the line.

I'm off to a fairly good start viz: https://andy-abtec.github.io/minimal-test/ which obviously needs its CSS sorting out but it's a beginning (repo is: https://github.com/Andy-ABTec/minimal-test).

I modified masthead.html to include slugified id tags for the menu entries (the only change to the template code so far). I'm using jQuery to pull in a small html file (manual-chapters.html) from "assets/html/" which seemed like the best place to put it, however I have a problem, the html file needs hrefs which include {{ site.url }} and/or {{ site.baseurl }} to work correctly.

My dilemma is that if I include empty front matter in the file its content disappears from the existing masthead menu, if I just include the tags they aren't translated so my only option is to include the full path in the file which isn't exactly portable,

Any idea how I can fix this? Move the file somewhere else? Or should I be looking at "yamlizing" the menu content and then passing it on the fly to get the right refs (that'll be a whole new learning curve!) .

Any tips/ideas more than welcome!

**Comment by mmistakes** [comment]
Probably not a good idea to build something like navigation with JavaScript. It will cease to work if the user has it disabled and isn't as accessible.

I would use an include and build it from a data file just like I'm currently doing. If you're looking to do a dropdown it can be done pretty easily. I purposely didn't use that pattern for this theme as it complicates things, but generating the HTML needed for it is pretty easy.

An example of one of those is as follows.

**Drop-Down Navigation Data File:**

```
# example /_data/navigation.yml
- title: "About"
  href: "/about/"
  children:
    - childtitle: "Biography"
      childhref: "/about/bio/"
    - childtitle: "Resume"
      childhref: "/about/resume/"

- title: "Portfolio"
  href: "/portfolio/"
  children:
    - childtitle: "Design"
      childhref: "/portfolio/design/"
    - childtitle: "Illustration"
      childhref: "/portfolio/illustration/"
    - childtitle: "Development"
      childhref: "/portfolio/development/"
```

**Drop-Down Navigation HTML and Liquid:**

```html
<ul>
  {% for nav in site.data.navigation %}
    {% if nav.children != null %}
      <li><a href="{{ nav.href }}">{{ nav.title }}</a>
        <ul class="child">
        {% for child in nav.children %}
          <li><a href="{{ child.childhref }}">{{ child.childtitle }}</a></li>
        {% endfor %}
        </ul>
        {% else %}
      <li><a href="{{ nav.href }}">{{ nav.title }}</a>{% endif %}</li>
  {% endfor %}
</ul>
```

Which will produce the following HTML:

```html
<ul>
  <li><a href="/about/">About</a>
    <ul class="child">
      <li><a href="/about/bio/">Biography</a></li>
      <li><a href="/about/resume/">Resume</a></li>
    </ul>
  </li>
  <li><a href="/portfolio/">Portfolio</a>
    <ul class="child">
      <li><a href="/portfolio/design/">Design</a></li>
      <li><a href="/portfolio/illustration/">Illustration</a></li>
      <li><a href="/portfolio/development/">Development</a></li>
    </ul>
  </li>
</ul>
```

Then you can style and/or add JavaScript to make the dropdowns hide/reveal child links.
