### ISSUE TITLE
emoji is displaying not in original size in # Site Author section

### ISSUE THREAD

**Issue by kyxap** [mmistakes/minimal-mistakes#1554]
- [x] This is a question about using the theme.
- [ ] This is a feature request or enhancement.
- [x] I believe this to be a bug with the theme.
  - [ ] I am using the latest version of the theme.
  - [ ] I have updated all gems with `bundle update`.
  - [ ] I have tested locally with `bundle exec jekyll build`.

---

## Environment informations

- **Minimal Mistakes version:**  4.10.0
- **Jekyll version:** n/a
- **GitHub Pages hosted:** yes
- **Operating system:** n/a 

---

## Expected behavior

Want to use original img size of emoji in # Site Author section.

Img resized. Please check screenshot:
![image](https://user-images.githubusercontent.com/3080529/36685057-14abe236-1ad7-11e8-8250-e36b35c63313.png)

Html:
```html
<p class="author__bio" itemprop="description">
        QA Automation Engineer, Originally from Kyiv, Ukraine <img class="emoji" title=":ukraine:" alt=":ukraine:" src="https://assets-cdn.github.com/images/icons/emoji/unicode/1f1fa-1f1e6.png" height="20" width="20">
      </p>
```

## Steps to reproduce the behavior

Add emoji to Site Author column like (by editing the *_config.yml*):
```yml
# Site Author
author:
  name             : "Roman Kukharuk"
  avatar           : "/assets/images/bio-photo.jpg"
  bio              : "QA Automation Engineer, Originally from Kyiv, Ukraine :ukraine:"
```

**Comment by kyxap** [comment]
@mmistakes html added. seems like `height="20" width="20"` ignored.

**Comment by mmistakes** [comment]
HTML attributes aren't going to fix it as this line is stretching it:

```css
.sidebar img {
    width: 100%;
}
```

Either add inline CSS to your emoji `img` elements

```html
<img src="whatever.png" style="width: 20px; height: 20px;">
```

Or use the `.emoji` class and add to the global stylesheet.

```css
.sidebar img.emoji {
    width: 20px;
    height: 20px;
}
```

**Comment by kyxap** [comment]
Fixed with adding this into `_sidebar.scss` > `.sidebar` :
````css
  img.emoji {
     width: 20px;
     height: 20px;
  }
````
Not sure why there `100% width` for all images on side bar, maybe it can be deleted? 
Bc without this emoji will work out of the box.
