### ISSUE TITLE
Disqus comments not displaying

### ISSUE THREAD

**Issue by ronamosa** [mmistakes/minimal-mistakes#1562]
- [x] This is a question about using the theme.
- [ ] This is a feature request or enhancement.
- [ ] I believe this to be a bug with the theme.
  - [ ] I am using the latest version of the theme.
  - [ ] I have updated all gems with `bundle update`.
  - [x] I have tested locally with `bundle exec jekyll build`.

---

## Environment informations

- **Minimal Mistakes version:** 
- **Jekyll version:**3.7.2
- **GitHub Pages hosted:** no
- **Operating system:** Linux

---

## Expected behavior
Disqus comments to appear on my blog posts.

## Steps to reproduce the behavior
1. Go to https://cloudbuilder.io/career/Life-Starts-at-Systems-Engineer/
2. See the comments are not loaded even though the `view source-code` shows the disqus <script> is loaded but using the web developer tools (F12) and see:
```
Uncaught TypeError: Cannot read property 'appendChild' of null
    at k (embed.js:28)
    at Object.l [as isSerif] (embed.js:28)
    at h.i.toJSON (embed.js:28)
    at Object.c.loadEmbed [as _loadEmbed] (embed.js:29)
    at embed.js:29
```

## Troubleshooting steps taken

I did a search of closed issues and read every one that had Disqus, and checked the following:

1. my Disqus account is setup and verified the shortname = 'cloudbuilder'

2. my _config.yml
```
comments:
  provider               : "disqus"
  disqus:
    shortname            : "cloudbuilder" 
```
set defaults to
```
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true # true
      share: true
      related: true
```

also at the top of my post Front matter:
```
---
title: "Life starts at Systems Engineer"
header:
  overlay_image: /assets/images/life-starts-systems-engineer.jpg
  og_image: /assets/images/life-starts-systems-engineer.jpg
excerpt: "\"The Matrix is a system, Neo. That system is our enemy.\""
categories:
  - Career
tags:
  - Systems
  - Engineer
  - ITIL
  - Projects
last_modified_at: 2018-02-24T14:25:19-04:00
comments: true
---
```

Other possibly relevant info:
I'm running `bundle exec jekyll build` and then pushing the _site folder to my AWS hosted s3 static site.

Sorry I don't have a public repo for you to have a look at, I can provide any files you need to have a look at on request!

Thanks for a great theme, hopefully I haven't butchered it too much.

**Comment by mmistakes** [comment]
Have you set `JEKYLL_ENV=production`?

> Comments are disabled by default in `development`. To enable when testing/building locally be sure to set `JEKYLL_ENV=production` to [force the environment](http://jekyllrb.com/docs/configuration/#specifying-a-jekyll-environment-at-build-time) to production.

**Comment by ronamosa** [comment]
crap sorry that was it. I did a : 

$ JEKYLL_ENV=production jekyll build

and then pushed the static to my s3 bucket and it loaded.

I've run into another issue but I'll open a separate ticket for that. thank you!

**Comment by sheldonhull** [comment]
If appropriate I can open a new item, but I had the same exact issue. 
I've done every step mentioned above, excepting including comments:true in each post. Instead I included in single layout, which didn't fix this. 

In addition, my Netlify build script is 

```toml
[build]
  command = "JEKYLL_ENV=production jekyll build && jekyll algolia"
  publish = "_site"
```

Didn't want to open a new issue if this exact same issue is what I'm experiencing. I tested local with production variable in docker, and also have tried with the command and environmental variable from Netlify, but no result.

**Comment by mmistakes** [comment]
@sheldonhull Not sure what else to tell you as I don't use Docker or Netlify. The issue does seem to be related to them and setting environment variables.

[This is the line in the theme](https://github.com/mmistakes/minimal-mistakes/blob/master/_layouts/single.html#L66) that sets that condition. 

```html
{% if jekyll.environment == 'production' and site.comments.provider and page.comments %}
  {% include comments.html %}
{% endif %}
```

It only shows comments when Jekyll's environment is set to `production`, `comments.provider` is set in _config.yml, and the post has `comments: true` in its YAML Front Matter.

If you're having trouble properly setting `production` then my suggestion would be to remove the condition in the theme.

**Comment by RichStone** [comment]
Hey, 
I have also added everything as described in the documentation but the comment just does not appear: 

[https://richstone.github.io/blog/test](url)

Setting `JEKYLL_ENV=production bundle exec jekyll build/serve` in my mac terminal does not help as well. 

shortname is indeed datagooide (with typo in it)

**Comment by mmistakes** [comment]
@RichStone Check your config file. You have two `default` keys in `_config.yml`... the first set of defaults that assigns `comments: true` to all your posts is being replaced with the second set you're using for pages.

```yaml
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true

defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
```

It should be this instead (note there's only one `default` key with all post/page scopes indented under it:

```yaml
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
```

![screen shot 2018-07-29 at 7 43 07 pm](https://user-images.githubusercontent.com/1376749/43371832-a39af578-9367-11e8-85e2-9755cc4e9d2c.png)
