### ISSUE TITLE
Less an issue more a question about sidebar links

### ISSUE THREAD

**Issue by ktavabi** [mmistakes/minimal-mistakes#1568]
- [x] This is a question about using the theme.
- [ ] This is a feature request or enhancement.
- [ ] I believe this to be a bug with the theme.
  - [x] I am using the latest version of the theme.
  - [x] I have updated all gems with `bundle update`.
  - [x] I have tested locally with `bundle exec jekyll build`.

---

## Environment informations
- **Minimal Mistakes version:** 4.10.0 
- **Jekyll version:** 3.7.3
- **GitHub Pages hosted:** yes
- **Operating system:** OSX

---

## Expected behavior

  Given social network IDs are provided in `_config.yml` and `about.md` header as such...
```
---
layout: single
title: About
permalink: /about/
author_profile: True
share: false
---
```
I am expecting to see a list of social network links in the sidebar on my rendered `about.md` page. 
[Here](https://github.com/ktavabi/ktavabi.github.io.git) is my forked site.

P.S. Is the following correct for configuring front matter in `_config.yml`
```
# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: # true
      share: true
      related: true
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
      share: false
```

**Comment by mmistakes** [comment]
Don’t think your default front matter in `_config.yml` is correct for “Pages”, having just `scope` isn’t enough. You need to specify the path where your pages reside.

```yaml 
- scope:
    path: "_pages"
    type: pages
```

If that doesn’t work then just add the author profile front matter flag directly to `about.md`

```yaml 
author_profile: true
```

Closing as this is a more of a “how do I use Jekyll” question that is better asked on their help site.

ref: https://jekyllrb.com/docs/configuration/#front-matter-defaults
