### ISSUE TITLE
a collection can't work in a custom folder.

### ISSUE THREAD

**Issue by goshinh** [mmistakes/minimal-mistakes#1580]
- [x] This is a question about using the theme.
- [ ] This is a feature request or enhancement.
- [ ] I believe this to be a bug with the theme.
  - [ ] I am using the latest version of the theme.
  - [ ] I have updated all gems with `bundle update`.
  - [ ] I have tested locally with `bundle exec jekyll build`.

---

## Environment informations

- **Minimal Mistakes version:** lasted
- **Jekyll version:**lasted
- **GitHub Pages hosted:** yes
- **Operating system:** Ubuntu 16.04

---

## Expected behavior

The `to-list-collectionTest.md`is expected to show the list of `collectionTest`But it doesn't work.
How is this not working?

## Steps to reproduce the behavior

**_config.yml**
```
collections:
   collectionTest:
      output: true
      permalink:  /:collection/:path/
  ...
defaults:
  # _collectionTest
     - scope:
        path: ""
        type: collectionTest
      values:
        layout: single
        author_profile: true
        share: false
```
**Directory Structure:**
```
├── ...
├── _pages
│   ├── to-list-collectionTest.md
├── myfolder
│   ├── _collectionTest
│   │   ├── 00-samplefile.md
```
**to-list-collectionTest.md:**
```
---
layout: archive
title: "CollectionTest-List"
permalink: /listcolletion/
author_profile: true
---
This is a page to list collection.

<ul>
  {% for item in site.collectionTest %}
  <ul>
    <a href="{{ item.url | prepend: item.baseurl }}">{{ item.title }}</a>
  </ul>
```
**00-samplefile.md**
```
---
tiltle: showme
---
```
