### ISSUE TITLE
Improve author link flexibility

### ISSUE THREAD

**Issue by mmistakes** [mmistakes/minimal-mistakes#1581]
Deprecate existing "hard-coded" author link Liquid spaghetti with something more flexible... similar to how [footer links](https://github.com/mmistakes/so-simple-theme#footer-links) are defined in **So Simple theme**.

```yaml
author:
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: mailto:your.name@email.com
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://your-website.com"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/username"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
      url: "https://facebook.com/username"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/username"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/username"
```

This would allow users to define what links they'd like, what they link to, their order, and use any of the icons available with [Font Awesome](https://fontawesome.com/icons?d=gallery).
