### ISSUE TITLE
Issue with post layout

### ISSUE THREAD

**Issue by pgyogesh** [mmistakes/minimal-mistakes#1596]
- [X] This is a question about using the theme.
- [ ] This is a feature request or enhancement.
- [ ] I believe this to be a bug with the theme.
  - [X] I am using the latest version of the theme.
  - [ ] I have updated all gems with `bundle update`.
  - [ ] I have tested locally with `bundle exec jekyll build`.

---

## Environment informations

- **Minimal Mistakes version:** 
- **Jekyll version:**
- **GitHub Pages hosted:** yes
- **Operating system:** MacOS

---

## Expected behavior

Post Layout like below:
https://mmistakes.github.io/minimal-mistakes/jekyll/post-exclude-search/

## Steps to reproduce the behavior

Visit:

http://pgyogesh.com/blog/greenplum/python/parallel-restore-using-python/

My Repo:  https://github.com/pgyogesh/blog

**Comment by hkalant** [comment]
@pgyogesh The layout in your posts' front-matter should be `layout: single`, not `layout: post`.

Better yet, you can define the layout once in `config.yml` as following:

```
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: # true
      share: true
      related: true
```

So you don't have to include it in every single post.
