### ISSUE TITLE
disqus comment

### ISSUE THREAD

**Issue by battlerhythm** [mmistakes/minimal-mistakes#1679]
## Description

Hi, I have look through related issues in previous but I couldn't solve my problem
It doesn't show

## Environment

- Minimal Mistakes version: forke date: 9th May
- Git repository URL: https://github.com/battlerhythm/battlerhythm.github.io
- GitHub Pages hosted (if yes provide URL to site): Yes, https://battlerhythm.github.io

---

## Expected behavior

Disqus suppose to be shown but it's not

## Steps to reproduce the behavior

I did following as the guide saying
and None of posts has comment: false

``` yml
comments:
  provider               : "disqus" # false (default), "disqus", "discourse", "facebook", "google-plus", "staticman", "staticman_v2" "custom"
  disqus:
    shortname            : "jmoh" # https://help.disqus.com/customer/portal/articles/466208-what-s-a-shortname-

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
```
