### ISSUE TITLE
Overriding default styles - how to use main.scss?

### ISSUE THREAD

**Issue by cbarina** [mmistakes/minimal-mistakes#1709]
## Description
Trying to update part of .sidebar__right, presumably through main.scss

## Environment
Hosting with GitHub Pages, https://github.com/cbarina/rexpat

## Expected behavior
I think I have a bit of css to modify for .sidebar__right - I'm just not sure if I'm editing properly to do this. 
Specifically, I just want to use this bit:

```
@media (min-width: 80em)
.sidebar__right {
    width: 300px;
    margin-right: -300px;
    float: right;
    position: sticky;
}
```

## Steps to reproduce the behavior

1. I reviewed this documentation and created a copy of assets/css/main.scss in my repo.
  Then provide a complete log by running `bundle exec jekyll build --trace --verbose` 
  and include this output in the filed issue.
2. I inserted the code as shown above, then pushed to gitHub
3. ...nothing! 😄 

What am I doing wrong?

**Comment by mmistakes** [comment]
The way you've done it is correct, but the way you've written your media query is wrong... it's missing the `{ }` around `.sidebar__right`

That's likely why it's not being included in the stylesheet and you don't see any change on your site. Change it to this and it should work:

```css
@media (min-width: 80em) {
  .sidebar__right {
      width: 300px;
      margin-right: -300px;
      float: right;
      position: sticky;
  }
}
```
