### ISSUE TITLE
navtoogle or navtoggle in scss?

### ISSUE THREAD

**Issue by logista** [mmistakes/minimal-mistakes#175]
I was trying to modify the color of the `menu` button, and found its class is `.navtoogle` (which is also what it's called in the javascripts)

But `page.scss` also has `.navtoggle`

``` css
.no-js .nav .navtoggle {
	display: none;
}
```

I'm *assuming* this wants to be `.navtoogle` to match?
