### ISSUE TITLE
What is the syntax for _config.yml scope path?

### ISSUE THREAD

**Issue by szgaljic** [mmistakes/minimal-mistakes#1795]
## Description

_config.yml scope path syntax doesn't seem to work no matter what I try. I am trying to configure two different side bars two different sections of my site from _config.yml but I can't get the pathing to work.

Please see my stackoverflow here. [https://stackoverflow.com/questions/51938521/jekyll-front-matter-path-doesnt-work](https://stackoverflow.com/questions/51938521/jekyll-front-matter-path-doesnt-work)

The only way I can get this to work is by hand adding the sidebar to each page in front matter.

```
sidebar:
  nav: intro
```

I'm not sure what I'm doing wrong.

## Environment

- Minimal Mistakes version:
- Ruby gem or remote theme version:
- Jekyll version:
- Git repository URL:
- Operating system:
- GitHub Pages hosted (if yes provide URL to site):

---

**Comment by mmistakes** [comment]
It's not working because your paths are wrong. I don't know if Jekyll's docs have examples, but I'm pretty sure the path's are relative to root folder.

To make try these paths instead you need to add `_pages/` before the folder names you're currently using.

```
defaults:
  - scope:
      path: _pages/intro
      type: pages
    values:
      layout: single
      classes: wide
      sidebar:
        nav: "intro" 
  - scope:
      path: _pages/core
      type: pages
    values:
      layout: single
      classes: wide
      sidebar:
        nav: "core"
```
