### ISSUE TITLE
How to center the Title in each feature_row column?

### ISSUE THREAD

**Issue by zenkbaries** [mmistakes/minimal-mistakes#1858]
Hi.

I've been working on building a website using your theme (4.13) for last few weeks now. 

My questions is about feature_row. How do I make the title of each feature column to be centered?

```YAML
feature_row:
  - image_path: /assets/images/code.png
    alt: "coding"
    title: "Blog"
```

I checked the documentation and still not finding anything on how to center the 'title' text.. I must have missed something. Been on it for two days now. I know this is a simple question and I fear that the answer is there somewhere in the documentation. I just couldn't find it.

thanks (in advance just in case)

**Comment by mmistakes** [comment]
https://mmistakes.github.io/minimal-mistakes/docs/helpers/#feature-row

You'll use `type="center"`
Here's the sourcecode for [some examples](https://mmistakes.github.io/minimal-mistakes/splash-page/)

https://github.com/mmistakes/minimal-mistakes/blob/master/docs//_pages/splash-page.md

**Comment by zenkbaries** [comment]
I realized I didn't give you a full code. (I used partial code which caused confusion.)  Here is the full code I use.

```yml
feature_row:
  - image_path: /assets/images/code.png
    alt: "coding"
    title: "Blog"        # I want this centered
    url: "/coding/"
  - image_path: /assets/images/portfolios.png
    alt: "Portfolios of codes"
    title: "Portfolios"        # I want this centered
    url: "/portfolios/"
  - image_path: /assets/images/code_me.png
    alt: "Resume"
    title: 'Resume'      # I want this centered
    url: "/me/"
```
I wanted those title from each 'feature' to be centered.(see code above) Not have the whole feature centered as you gave me the example in your previous answer.
