### ISSUE TITLE
Setup a page with most recent posts

### ISSUE THREAD

**Issue by arvera** [mmistakes/minimal-mistakes#1931]
So I have:

- [X] Read through the theme's documentation at *https://mmistakes.github.io/minimal-mistakes/docs/quick-start-guide/*
- [X] I also *search all issues at https://github.com/mmistakes/minimal-mistakes/issues*
- [X] I lastly tried *Ask for help at https://talk.jekyllrb.com/* but that gives `404`
  
After exhausting all of these I then ask my question below:

## Questions:
1) **Using the home page**, whenever someone clicks on posts the sidebar goes away, but I prefer the bio sidebar to stay. According to: https://mmistakes.github.io/minimal-mistakes/docs/layouts/ it should be a matter of just having 
   ```
    # Defaults
   defaults:
     # _posts
     - scope:
         path: ""
         type: posts
       values:
         author_profile: true
   ```
see https://github.com/arvera/blog/blob/master/_config.yml

2) Also the TOC is not showing.. maybe I am missing something.. Ohh I just re-read it I think the TOC is auto-generated from the HTML elements in the POST? hmm I thought it was a TOC of the page posts, as in all the posts that are showing in one page

3) The search example is not working... I wanted to see how it would work, do I need to hook it up to google search or solr, or something else?
