### ISSUE TITLE
Site Author Details

### ISSUE THREAD

**Issue by ritayadav** [mmistakes/minimal-mistakes#1946]
I am using an old version. In that, we had many options for site author like google_plus, keybase, pinterest, dribbble, flickr, linkedin etc. 
![1](https://user-images.githubusercontent.com/21067142/48624947-e5f2ca80-e9d5-11e8-8604-bbcf0df489c1.PNG)
I have mentioned the screenshot but in the new version, I have not found that.

![2](https://user-images.githubusercontent.com/21067142/48625119-5e598b80-e9d6-11e8-9a6e-b9e1321a1114.PNG)

 Please help me to mention that details in the new version

**Comment by mmistakes** [comment]
You actually have more options now. Any FontAwesome icon is available for use and you can order the links however you want as well. It's just configured differently. You need to specify author links now (icon, URL, label).

An example:

```yaml
author:
  name: "Your Name"
  avatar: "/assets/images/bio-photo.jpg"
  bio: "I am an amazing person."
  location: "Somewhere"
  links:
    - label: "Made Mistakes"
      icon: "fas fa-fw fa-link"
      url: "https://mademistakes.com"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/mmistakes"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/mmistakes"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/mmistakes"
```

See the site author documentation for more info: https://mmistakes.github.io/minimal-mistakes/docs/configuration/#site-author
