### ISSUE TITLE
please add sublinks in navigation.yml support

### ISSUE THREAD

**Issue by ykfq** [mmistakes/minimal-mistakes#1960]
Hi,
I'm trying to add a sublink (or a dropdown list) to the navigation items but I can't get it work, please help.

My code in `_data/navigation.yml`
```
  - title: "Collections"
    sublinks:
      - title: Docker
        url: /docker/
      - title: Kubernetes
        url: /kubernetes/
      - title: OpenStack
        url: /openstack/
```
with hoped effect like this:
![image](https://user-images.githubusercontent.com/20741596/48790845-372ef100-ed2b-11e8-9ed6-6908937bb524.png)

Is it possible to achive it ? If yes, give me some guide please; if not , hope to add this feature in the future.
Thanks a lot.
