### ISSUE TITLE
Using jekyll-archives as per the instructions results in blank category and tag archives pages

### ISSUE THREAD

**Issue by asarkar** [mmistakes/minimal-mistakes#1984]
Following the instructions in [Taxonomy archives](https://mmistakes.github.io/minimal-mistakes/docs/layouts/), I don't see any posts listed under `/categories`:

**_config.yml**

```
category_archive:
  type: jekyll-archives
  path: /categories/
tag_archive:
  type: jekyll-archives
  path: /tags/
jekyll-archives:
  enabled:
    - categories
    - tags
    - year
  layouts: archive-taxonomy
  permalinks:
    category: /categories/:name/
    tag: /tags/:name/
```

**Gemfile**
```
gem "jekyll-archives"
```

But when I go to `categories`, I see the following; clicking on individual category link takes me to a blank page that lists the category name, but no posts.
![categories](https://user-images.githubusercontent.com/1302775/49361850-de981600-f691-11e8-81c3-9faf2a44f54c.jpg)

Even if the links worked, I hate the ugly index page. I think the documentations needs to be clearer about using Jekyll archives plugin vs Liquid. Currently, the instructions go back and forth, and for muggles like me, it's confusing.

I have not copied the [category-archive.md](https://github.com/mmistakes/minimal-mistakes/blob/master/docs/_pages/category-archive.md) to `_pages` because I got the impression that it's not needed when using  jekyll-archives.
