### ISSUE TITLE
Being able to have a sidebar nav and title block

### ISSUE THREAD

**Issue by lsolesen** [mmistakes/minimal-mistakes#1986]
## Environment

- Minimal Mistakes version: 4.14.1
- Ruby gem or remote theme version:
- Jekyll version:
- Git repository URL: https://github.com/vih/historie
- GitHub Pages hosted (if yes provide URL to site): 
- Operating system:

## Expected behavior

Include sidebar navigation also when specified.

## Steps to reproduce the behavior

This code:

https://github.com/vih/historie/blob/songs-sidebar/_pages/songs-archive.md

Gives this result:

https://5c06798e0097d408a537bc14--vih-historie.netlify.com/sange/

Without the sidebar.

**Comment by mmistakes** [comment]
Your YAML is off. Try this:

```yaml
sidebar:
  title: "Vejle Idrætshøjskoles Sange"
  image: "//images.weserv.nl/?url=https://drive.google.com/uc?id=10k7zuB8CRXnnKxBye_kIzKdBnO5uKGwi&w=300&a=attention&t=square"
  image_alt: "Vejle Idrætshøjskoles Sange"
  text: "De officielle sange er indspillet 2018 af Mille Sigsgaard Christensen, Charlotte Støjberg og Kristian Enevoldsen. **Køb den eller stream den fra din foretrukne musiktjeneste.**, fx [Google Play](https://play.google.com/music/listen#/album/Birdaib4zktzgwthhtd4uxlafta), [Itunes](https://itunes.apple.com/album/-/id1444457441), [Deezer](https://www.deezer.com/da/album/79792202), [Tidal](https://listen.tidal.com/album/99556066), [Spotify](https://play.spotify.com/album/6vpvN8PtyRg7wYLUqIdlbI), [YouSee](https://musik.yousee.dk/album/202470120/vejle-idraetshojskoles-sange)."
  nav: "songs"
```

See this example for more info: https://mmistakes.github.io/minimal-mistakes/layout-sidebar-nav-list/
