### ISSUE TITLE
Enable dark skin

### ISSUE THREAD

**Issue by z0ph** [mmistakes/minimal-mistakes#2095]
Hello,

I'm facing an issue, trying to enable skin (`dark`) on my jekyll / minimal-mistakes blog.

I've added the following lines on my `_config.yml` file, but when I build locally, or remotly, the theme is still using the light theme (default)

```
theme                    : "minimal-mistakes-jekyll"
minimal_mistakes_skin    : "dark"
```

I'm using:
```
Using jekyll 3.8.5
Using jekyll-archives 2.1.1
Using jekyll-data 1.0.0
Using jekyll-feed 0.11.0
Using sawyer 0.8.1
Using octokit 4.13.0
Using jekyll-gist 1.5.0
Using jekyll-include-cache 0.1.0
Using jekyll-paginate 1.1.0
Using jekyll-sitemap 1.2.0
Using jekyll-twitter-plugin 2.0.0
Using jemoji 0.10.2
Using minimal-mistakes-jekyll 4.15.2
Bundle updated!
```

**Comment by z0ph** [comment]
Same issue, trying to add a link in the `author` section

```
  links:
    - label: "Resume"
      icon: "fas fa-fw fa-envelope-square"
      url: "./xx/"
```
