### ISSUE TITLE
How to make a fixed Navigation bar

### ISSUE THREAD

**Issue by LeducH** [mmistakes/minimal-mistakes#2133]
## Summary
The navigation shall remain visible even when scrolling down. similar to [html examle](https://www.w3schools.com/howto/howto_css_fixed_menu.asp)

## Motivation
when content is very long it would be beneficial to able to navigate around.

**Comment by mmistakes** [comment]
You'll need to [customize the theme's CSS](https://mmistakes.github.io/minimal-mistakes/docs/stylesheets/#customizing) to stick the navigation bar and add declarations like the following:

```css
.masthead {
  position: sticky;
  top: 0;
  background-color: #fff;
}
```
