### ISSUE TITLE
How to prevent it from creating local .html file when .md file is modified

### ISSUE THREAD

**Issue by deadlydog** [mmistakes/minimal-mistakes#2138]
I've just posed [this question on Stack Overflow](https://stackoverflow.com/questions/55895311/prevent-jekyll-from-creating-html-file-in-same-directory-as-md-file). Whenever I modify one of the .md files, it also creates a .html file in the same directory, as well as the `_site` directory.  I want the html file created int he `_site` directory, but not in the same directory as the .md file. The applies to the `ReadMe.md`, `_pages/about.md`, etc. How do I disable that so the files only get created in the `_site` directory? Sorry if this is an easy question to answer; I'm a bit of a Jekyll newb.

**Comment by mmistakes** [comment]
For Jekyll help use their forum. 

http://talk.jekyllrb.com/

**Comment by deadlydog** [comment]
Thanks for the link. I wasn't sure if this was a Jekyll issue, or something specific to your theme / starter repo, as when I create a new Jekyll site natively (i.e. `jekyll new MyBlog`) it doesn't have this problem. I'll see if somebody in their forum responds though. Thanks.

**Comment by mmistakes** [comment]
Something is definitely at play if you have files being created in the source directories. Jekyll only creates .html files in `_site` unless you configure it to use a different folder.

**Comment by deadlydog** [comment]
Here is my `_config.yml` file:

```yml
# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Daniel Schroeder's (aka deadlydog) Programming Blog
email: deadlydog@hotmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Sharing my tips, tricks, and code to help other developers be more productive.
baseurl: /DansBlog.Jekyll
url: https://deadlydog.github.io
twitter_username: deadlydog
github_username: deadlydog

minimal_mistakes_skin: default # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum" "sunrise"
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes

# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Daniel Schroeder"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "Developer and family man. Loves C#, .NET, PowerShell, AutoHotkey. Automate Everything!"
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/deadlydog"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/deadlydog"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/1danielschroeder/"

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/deadlydog"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/deadlydog"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/1danielschroeder/"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
```

and my `Gemfile` file:

``` yml
source "https://rubygems.org"

gem "github-pages", group: :jekyll_plugins

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem.
gem "tzinfo-data"

# Performance-booster for watching directories on Windows.
gem "wdm", "~> 0.1.0" if Gem.win_platform?

# If you have any plugins, put them here!
group :jekyll_plugins do
  gem "jekyll-paginate"
  gem "jekyll-sitemap"
  gem "jekyll-gist"
  gem "jekyll-feed"
  gem "jemoji"
  gem "jekyll-include-cache"
  gem "jekyll-algolia"
end

``

Do you notice anything amiss?
