### ISSUE TITLE
I am unable to get my author links to show up

### ISSUE THREAD

**Issue by drubio1989** [mmistakes/minimal-mistakes#2148]
I have installed the latest version of minimal-mistakes and am attempting to customize the `author_profile` portion of my web page. However, I am unable to generate the links array to display my email and github profile.

I have followed the directions as specified here [site author](https://mmistakes.github.io/minimal-mistakes/docs/configuration/#site-description) 

In my `_config.yml` file I have the following:

```yaml
author:
  name: "Daniel Rubio"
  avatar: "/assets/me.jpg"
  bio: "Hey, my name is Daniel. I'm a web developer, online course creator, and a VR enthusiast."
  links:
    - label: "Email"
      icon: "fas fa-envelope-square"
      url: "mailto:drubio1989@gmail.com"
```

The label nor the icon is displaying. I've restarted with `jekyll serve` and have execuged `jekyll build`. The icons are not displaying. Is there a known issue or perhaps I am overlooking something.
