### ISSUE TITLE
Replacing recent posts by about.md page 

### ISSUE THREAD

**Issue by fsalmasri** [mmistakes/minimal-mistakes#2191]
I changed config file to

```
# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: pages #posts
    values:
      layout: single
      author_profile: true
      # read_time: true
      # comments: # true
      # share: true
      # related: true
```
and index.html to

```
---
<!-- layout: home -->
author_profile: true
permanentlink: /_pages/about.md
---
```
and I added about.md in _pages

```
---
title:  "Welcome to Jekyll!"
---

# Welcome
```
Recent posts disappeared when I committed layout: home but I can't see about.md content in the page.
