### ISSUE TITLE
Adding header video 

### ISSUE THREAD

**Issue by pranav6670** [mmistakes/minimal-mistakes#2199]
How to add header video to index.html or any other page?

**Comment by mmistakes** [comment]
```yaml
header:
  video:
    id: VIDEOID
    provider: youtube
```

https://github.com/mmistakes/minimal-mistakes/blob/master/docs/_posts/2017-01-23-layout-header-video.md
https://mmistakes.github.io/minimal-mistakes/layout/uncategorized/layout-header-video/
