### ISSUE TITLE
Make it possible to add link to sidebar pictures

### ISSUE THREAD

**Issue by lsolesen** [mmistakes/minimal-mistakes#2221]
## Summary

Make it possible to add an url to the pictures in the sidebar.

## Motivation

It would be cool if it is possible to put small pictures with links in the sidebar.

## Drawbacks

This can be achieved doing like this: 

https://github.com/lsolesen/ifire-dk-jekyll/blob/gh-pages/_includes/sidebar.html

and using it like this:

https://github.com/lsolesen/ifire-dk-jekyll/blob/gh-pages/index.html#L6

I can prepare a proper pull request, if you will accept this enhancement?

**Comment by mmistakes** [comment]
What purpose does making the author image a link serve when they're are already author links below with labels?

**Comment by lsolesen** [comment]
It is not the author link. It is a sidebar picture link?

søn. 28. jul. 2019 23.44 skrev Michael Rose <notifications@github.com>:

**Comment by mmistakes** [comment]
Oh right. Sidebar images are something I've never been happy about how it's implemented. It's a mess of Liquid spaghetti code.

The better solution I think would be just use Markdown to include images. Then you get all the formatting and expanded support for images and/or linking them. And it wouldn't be predefined by the theme. You could do text followed by an image followed by more text. Instead of image, image, image, text.

```markdown
sidebar:
  text: >
    [![img](img.jpg)](http://x.com)
    [![img](img.jpg)](http://x.com)
```

**Comment by lsolesen** [comment]
Cool. I will use that technique instead.

**Comment by lsolesen** [comment]
@mmistakes Btw, is there a way to add sidebar content to an entire collection. I tried this: https://github.com/lsolesen/ifire-dk-jekyll/blob/gh-pages/_config.yml#L261, but it did not quite get through to the sidebar: https://www.ifire.dk/airbnb-anmeldelse/

**Comment by mmistakes** [comment]
Yes there is. I had a typo in my example above that's why it wasn't working for you. Follow how the documentation shows to [add custom sidebar content](https://mmistakes.github.io/minimal-mistakes/docs/layouts/#custom-sidebar-content)... it needs a `-` before the text.

```yaml
defaults:
  - scope:
      path: ""
      type: posts
    values:
      sidebar:
        - text: >
            ---
            [![Crowdlending på Mintos - få 11,6% p.a.](https://i1.wp.com/www.frinans.dk/wp-content/uploads/2018/08/Mintos-banner-300x250.png?resize=300%2C250&ssl=1)](/go/mintos/)
            ---
            [![Få gratis investeringsplan fra Nord.Investments](https://i2.wp.com/www.frinans.dk/wp-content/uploads/2018/07/Gratis-investeringsplan.jpg?w=552&ssl=1)](/go/nord/)
            ---
            [![Få Bitcoins til en værdi af $10](https://i1.wp.com/www.frinans.dk/wp-content/uploads/2018/01/Coinbase-banner_annonce-1024x333.png?resize=750%2C244&ssl=1)](/go/coinbase/)
            ---
```

**Comment by maxime-michel** [comment]
Thanks for the tip, that's great. Talking about documentation, I just tried the approach with the image from placehold.it, the image didn't show up at all. I thought it wasn't being loaded because served from HTTP over HTTPS, but it actually wasn't even showing up in the DOM.

Should we document your tip in the documentation while at the same time clean up the implementation you're not happy about? I can help with that if you sketch it out.

Also, one nice to have when it comes to sidebar images would be if the lowered opacity was applied to individual sidebar elements rather than to the sidebar as a whole. It's a great effect on somebody's avatar, not so much on ads such as in the screenshot above.

**Comment by mmistakes** [comment]
@maxime-michel As far as implementation cleanup, there really isn't anything to do. What I'm not happy with is the fact that I added YAML support for adding images in the first place. It's likely something I would deprecate in a future version, but it's not really hurting anything keeping it there... I just don't want to develop it further.

Adding sidebar content via Markdown as described above is superior in my opinion as you can pretty much do whatever you want. And if Markdown doesn't support it you can always dump in HTML.

As far as documentation, there's a note that the sidebar content field accepts Markdown. I suppose an example [could be added here](https://mmistakes.github.io/minimal-mistakes/docs/layouts/#custom-sidebar-content) to hammer home the idea that you can do more complex stuff than just a simple string of text.

I struggle with this sort of thing because it's not really a theme feature as much as it's an advanced Jekyll/Kramdown feature. These sorts of "pro-features" I've historically left to the Jekyll community to educate users on. If you're the sort of person to dig into this stuff you'd likely pour over the [YAML spec](https://yaml.org/spec/1.2/spec.html) or [Kramdown's syntax](https://kramdown.gettalong.org/syntax.html). Though judging by the comments above this sort of thing is likely unknown.

Perhaps a blog post on the subject would be warranted ;-)

**Comment by mmistakes** [comment]
@maxime-michel And RE: the opacity of the sidebar content. This is another one of those decisions that is part of the theme's design philosophy.

The sidebar is just that... a sidebar. It's ancillary content, not the main point of the page. This is why it is dimmed and reduced in prominence to put the emphasis on the main container.

The theme is customizable and it's easy enough to add a line of CSS to have it fully opaque all the time if you desire.

```css
.sidebar { opacity: 1; }
```

**Comment by maxime-michel** [comment]
Yes, fair enough, that's what I ended up doing. I just thought I'd mention that detail as well.

As far as cleanup is concerned, the most pressing issue I had in mind is that following the documentation didn't result in the placehold.it image being in the DOM. But I don't want to make this issue any longer, so I guess I'll try to reproduce on a public repository and log that in a separate ticket?

**Comment by mmistakes** [comment]
@maxime-michel Yes, share a public repo so I can see how you're doing it.

I just used the following YAML front matter on a post and it worked as expected so something must be off for you.

```yaml
sidebar:
  - text: |
      Below is an image from Placeholder.com.

      [![Test image from Placeholder](https://via.placeholder.com/100)](https://placeholder.com/)
```

![image](https://user-images.githubusercontent.com/1376749/62622200-c4cb6480-b8eb-11e9-86b9-c5372ab8e594.png)

![image](https://user-images.githubusercontent.com/1376749/62622226-d0b72680-b8eb-11e9-877d-de626ae1de25.png)

**Comment by maxime-michel** [comment]
That worked for me as well, what I meant was that before I stumbled upon this issue and your tip, I tried the snippet at https://mmistakes.github.io/minimal-mistakes/docs/layouts/#custom-sidebar-content

Which is:

    sidebar:
      - title: "Title"
        image: http://placehold.it/350x250
        image_alt: "image"
        text: "Some text here."

And while that produced a section with the title, the image never was in the DOM.

**Comment by mmistakes** [comment]
Not sure what else suggest or tell you. that snippet works fine on the demo site using the following YAML:

```yaml
---
title: "Layout: Sidebar Custom"
excerpt: "A post with custom sidebar content."
author_profile: false
sidebar:
  - title: "Title"
    image: http://placehold.it/350x250
    image_alt: "image"
    text: "Some text here."
  - title: "Another Title"
    text: "More text here."
    nav: sidebar-sample
---
```

Rendered post: https://mmistakes.github.io/minimal-mistakes/layout-sidebar-custom/
Post source code: https://github.com/mmistakes/minimal-mistakes/blob/master/docs/_posts/2012-03-15-layout-sidebar-custom.md
