### ISSUE TITLE
grid view: prevent cropping of teaser images

### ISSUE THREAD

**Issue by jrekier** [mmistakes/minimal-mistakes#2231]
I use the grid archive layout to display the elements of a collection of book reviews that I am currently assembling. I would like to use the cover of the books as teaser images. 

Is there a way to avoid the automatic cropping of the covers as in the figure below ? 

![Screen Shot 2019-08-12 at 15 40 10](https://user-images.githubusercontent.com/9407736/62869181-9ac4d880-bd17-11e9-97c8-1e746a1782de.png)

I have dabbled a bit into the `_archive.scss` and I understand that everything happens around here: 

```css
.archive__item-teaser {
  position: relative;
  border-radius: $border-radius;
  overflow: hidden;

  img {
    width: 100%;
  }
}
```
 but I haven't been able to make it work as I want. Ideally, I would like to keep an easy way to turn the cropping on and off.
