### ISSUE TITLE
Disable image feature at index page

### ISSUE THREAD

**Issue by ekremkaraca** [mmistakes/minimal-mistakes#224]
Hey @mmistakes,

Thanks for your Jekyll theme, I decided to use it on my site. I'd like to disable (or remove) image feature at index page, but I couldn't find how to do it. Each time i was at index, image feature is shown. Can you help me how to fix it?

**Comment by mmistakes** [comment]
You have to remove the feature image YAML from the post or pages you don't an image on. For example if you don't want a feature image on the home page, remove the following from [`index.md`](https://github.com/mmistakes/minimal-mistakes/blob/master/index.md)

``` yaml
image:
  feature: sample-image-1.jpg
  credit: WeGraphics
  creditlink: http://wegraphics.net/downloads/free-ultimate-blurred-background-pack/
```

This is all documented in the [Theme Setup](https://mmistakes.github.io/minimal-mistakes/theme-setup/#feature-images).
