### ISSUE TITLE
Sidebar use title from document file

### ISSUE THREAD

**Issue by hasezoey** [mmistakes/minimal-mistakes#2245]
Is it currently possible to use the title out of a Document / File instead of redundantly set the title in the _data's sidebars?

```yml
docs:
  - title: Start
    children:
      - title: 'Index' # use the title out of the file | insert title from a file
        url: /docs

  - title: Decorators
    children:
      - title: '' # use the title out of the file | insert title from a file
        url: /
```

example file / document

```md
---
title: "Index of Manual-Documentation" # to use this title instead of copy-pasting it manually
---

Something in here
```

---

(Second / alternative question)

Is it possible to generate a sidebar out of a folder, like permalinks: `/:collection/:path/`?
