### ISSUE TITLE
Updated OS (and Ruby and ...); rendering issues now: _config.yml defaults ignored?

### ISSUE THREAD

**Issue by Sciss** [mmistakes/minimal-mistakes#2247]
(Apologies if this is perhaps an issue with my Jekyll or Ruby, but I thought that many people are watching and may have encountered the same issue)

I have a fork of MM with version roughly at 4.9.0 (January 2018). I have updated my OS from Debian 9 to 10, part of which involved removing Ruby (I had a newer version installed than came with Debian 9), afterwards reinstalling it as standard package. In the process, something must have broken, but I can't find the issue.

__Situation:__ Jekyll seems to ignore the entire `defaults` section in `_config.yml`. It looks like [this](https://github.com/Sciss/minimal-mistakes/blob/906db943c1e7d0028732ead2354260731b92a4be/_config.yml#L121):

```yaml
# Defaults
defaults:
  # _posts
  - 
    scope:
      path: "_posts/"
      type: posts
    values:
      layout: single
      author_profile: false # true
      read_time: false # true
      comments: # true
      share: false # true
      related: true
  # _works
  - 
    scope:
      path: "_works/"
      type: works
    values:
      layout: piece
      permalink: /texts/:path:output_ext  # cf. https://github.com/jekyll/jekyll/issues/4145
```

In other words, I have two custom scopes `_works` and `_posts`.

__Observation:__ Everything renders fine as before, except everything in those two scopes, in the sense that the defaults are not picked up. So I get "plain body" renderings without header and footer, as the default `layout` is not used, and also the links are broken because `permalink` is not used.

As a workaround I can paste the defaults into each and every .md file, but of course that's just touching the symptom.

- has anyone experienced this? that the `defaults` are apparently ignored?
- is there a way to see if Jekyll has any parsing problems and just silently drops yaml from
  `_config.yml`? I tried running with `--verbose`, but there weren't any warnings or errors indicating such as problem.
- I also tried manually going back to an earlier Jekyll version; this didn't have any effect.
