### ISSUE TITLE
Change Font size: Missing _sass folder in mmistakes page starter repo.

### ISSUE THREAD

**Issue by Anamika255** [mmistakes/minimal-mistakes#2265]
I know that font size and types have been discussed in issues before. But all the solutions lead to changing the _sass/reset.scss file. However, i started building my site from the mm-github-pages-starter repo which didn't have _sass folder. And the minimal-mistakes repo has embedded folder layout which is confusing. Nonetheless, I copies the _sass folder into my repo and modified the _sass/reset.scss file, yet there is no change in font size. What am I doing wrong?

**Comment by mmistakes** [comment]
When using the theme as a `remote_theme` or gem, the Sass, layouts, and includes are bundled away and not directly visible... that's why you didn't find a `_sass` folder.

And because of how Jekyll deals with local overrides of theme files, you can't [customize a single `_sass` file](https://mmistakes.github.io/minimal-mistakes/docs/stylesheets/#customizing)... you need the entire folder. Which isn't that great since you'll have to manage it if the theme ever updates.

What I would suggest is copying [`/assets/css/main.scss`](https://github.com/mmistakes/minimal-mistakes/blob/master/assets/css/main.scss) to your repo (which imports all of the themes Sass partials). In this file you can add any custom CSS like changing the fonts or overriding Sass variables after the `@import` lines.

Example:

```scss
---
# Only the main Sass file needs front matter (the dashes are enough)
---

@charset "utf-8";

@import "minimal-mistakes/skins/{{ site.minimal_mistakes_skin | default: 'default' }}"; // skin
@import "minimal-mistakes"; // main partials

// custom CSS here
$global-font-family: Comic Sans;
$header-font-family: Comic Sans;
$caption-font-family: Comic Sans;

body { background: red; }
```

It's more future proof as you won't have to constantly merge in CSS changes the theme makes. You're only managing a single file instead of the entire [`_sass` folder](https://github.com/mmistakes/minimal-mistakes/tree/master/_sass).
