### ISSUE TITLE
Indentation of first paragraph

### ISSUE THREAD

**Issue by ekremkaraca** [mmistakes/minimal-mistakes#227]
Hi @mmistakes,

Is it possible to make first paragraph of posts and pages indented like other paragraphs? How can I do it?

**Comment by mmistakes** [comment]
Yes. You need to edit the CSS and apply a text-indent on all paragraphs.

In `/_sass/typography.scss` change the paragraph CSS starting @ [line 133](https://github.com/mmistakes/minimal-mistakes/blob/master/_sass/typography.scss#L133) to:

```scss
p {
  margin: 0 0 $indent-var;
  text-indent: $indent-var;
  // sibling indentation
  & + p {
    margin-top: -($indent-var);
  }
}
```
