### ISSUE TITLE
Portfolio with the author info

### ISSUE THREAD

**Issue by chenyx09** [mmistakes/minimal-mistakes#2291]
Hi Michael, thank you for your great theme. I had trouble using the collection layout. I want to create something like https://mmistakes.github.io/minimal-mistakes/portfolio/, but it turns out without the author information on the left and the navigation bar on the top. I've been playing around, and it turns out that when I include the _navigation.html and _author-bio.html, they don't show up in the right format. When I change head.html to _head.html, the author-bio and navigation are fine, but the portfolio listing got messed up. Can you help on this issue? Thanks.

**Comment by McSpooder** [comment]
How did you get it working at all? I cant get my /portfolio/ page to load. I followed the documentation exactly, including the jekyll documentation to no avail. I think I'm going crazy.

**Comment by mmistakes** [comment]
@McSpooder have a link to your repo so I can see what you've tried?

**Comment by McSpooder** [comment]
@mmistakes sorry for hijacking thread wasn't sure if it warrented a new one. 

Here's a link: https://github.com/McSpooder/McSpooder.github.io

I've made the _portfolio folder and added dummy posts into it.

Then edited the .yml config file.

Tried making a collection called "cookies" as well which didn't work.

**Comment by mmistakes** [comment]
@McSpooder couple of issues you have.

1. Remove `remote_theme: "mmistakes/minimal-mistakes@4.16.5"` from your [`Gemfile`](remote_theme: "mmistakes/minimal-mistakes@4.16.5") as that isn't valid.
2. Portfolio pages are being created but you don't have a `/portfolio/` page to list them. You need to create `_pages/portfolio.md` and add the following YAML front matter:
  ```yaml
  ---
  title: Portfolio
  layout: collection
  permalink: /portfolio/
  collection: portfolio
  entries_layout: grid
  classes: wide
  ---
  ```
3. You've misconfigured the `cookies` collection. Since you named the folder `_cookies` you have to match that name in the config. You have `cookie`, change that to `cookies`:
  ```yaml
  collection:
    cookies:
      output: true
  ```
4. You'll probably want to add ` /` to your collection [`permalink`](https://github.com/McSpooder/McSpooder.github.io/blob/master/_config.yml#L121-L127) so you get URLs like `/collection-name/foo/` instead of `/collection-name/foo.html`
  ```yaml
  collections:
    portfolio:
      output: true
      permalink: /:collection/:path/
    cookies:
      output: true
      permalink: /:collection/:path/
  ```
