### ISSUE TITLE
self-host or pick a CDN font-awesome webfont and css instead of using their JS and CDN

### ISSUE THREAD

**Issue by Sayrus** [mmistakes/minimal-mistakes#2298]
## Summary

Allow user to self-host or use a privacy oriented CDN for the woff/woff2/ttf/... file instead of using Javascript on Font Awesome CDN.
This could take the form of few values in `_config.yml`.
```yaml
font-awesome:
   webfont: true # Optional - use webfont instead of javascript
   cdn: "base_url" # Optional - use another CDN than Font Awesome (website URL or empty to self-serve)
```

## Motivation

Font Awesome icons won't load on any devices without Javascript (Tor Browser or Browser using NoScript)
Font Awesome does track every websites using minimal-mistakes without users (and often owners) knowing it (no opt-out, and they do NOT respect DNT):
```
Font Awesome collects data about you:
- when you use Font Awesome's content delivery networks, or visit websites that do
...
You can opt out of Google Analytics using a browser extension.
Font Awesome does not respond to the Do Not Track HTTP header.
```
Opt-out using an ad-blocker is kind of a joke ...
Do not wait for full page load to replace (Faster rendering, avoid recompiling 1MB of Javascript, avoid executing Javascript, and maybe better caching as extensions offers to cache the woff file if the name match to have your "own CDN" on localhost)

## Drawbacks

More traffic on your website? Usually cached anyway, especially if you are using your own CDN or something like Cloudflare.

No drawbacks if you just use a CDN that doesn't track you without consent.

Best regards,
