### ISSUE TITLE
customize colour and size of the font awesome icons for author panel?

### ISSUE THREAD

**Issue by mluerig** [mmistakes/minimal-mistakes#2369]
maybe not specific to this theme, but is it possible to customize colour and size of the font awesome icons for the author page (in config.yml or elsewhere)?
 
great theme, nice work!

**Comment by iBug** [comment]
For size, there are classes like `fa-xl` to adjust sizes for icons. See <https://fontawesome.com/how-to-use/on-the-web/styling/sizing-icons> for details.

For color, this section on the Basic Use page of Font Awesome would be helpful: <https://fontawesome.com/how-to-use/on-the-web/referencing-icons/basic-use#with-your-styling>

**Comment by mluerig** [comment]
thanks, super-easy for size. 

for colour, do you know where I would need to add that code snippet inside the theme?

**Comment by iBug** [comment]
If you just want to add color for one icon, you can write some HTML like this:

```html
<span style="color: red;">
  <i class="fas fa-clock"></i>
</span>
```

If you want to apply colors to multiple items or in `_config.yml`, adding some custom CSS would be easier:

```css
.icon-red {
  color: red !important;
}
```

And in `_config.yml`:

```yaml
author:
  links:
    - url: blah blah
      icon: "fab fa-github icon-red"
#                          ^^^^^^^^
```
