### ISSUE TITLE
Header image of diff. size between pages

### ISSUE THREAD

**Issue by ceso** [mmistakes/minimal-mistakes#2395]
# Environment

- Minimal Mistakes version: Think latest as is configured as remote theme
- Ruby gem or remote theme version: Remote theme method
- Jekyll version: Think latest as is configured as remote theme
- Git repository URL: https://github.ceso/ceso.github.io
- GitHub Pages hosted (if yes provide URL to site): yes, https://ceso.github.io/
- Operating system: Linux Manjaro

## Expected behavior

The default header of the site, configured in:

```
defaults:
  # _posts
--- CUTED ----
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
      header:
        overlay_image: "/assets/images/site/banner-site.jpg" 
--- CUTED ---
```
Appears in different size between the home page/404 vs /posts /tags /categories /about.html (in the last ones is a bit smaller).
None of those pages had over-writen the default header (yes the posts itself)

## Steps to reproduce the behavior

Example going to my blog:

https://ceso.github.io/
and jumping into https://ceso.github.io/about.html

they were took with google chrome, but is the same with any browser.

## Other

Here I leave 4 screenshots, comparing between the home page, a not found page, about, and posts:

![about](https://user-images.githubusercontent.com/5762221/74076657-dcf67a80-4a19-11ea-8b14-fd531d1c5a9c.png)
![home-page](https://user-images.githubusercontent.com/5762221/74076661-df58d480-4a19-11ea-9619-f9aabeea4cea.png)
![not-found](https://user-images.githubusercontent.com/5762221/74076662-e1bb2e80-4a19-11ea-9a8b-b1b9f9510bd8.png)
![posts-page](https://user-images.githubusercontent.com/5762221/74076664-e384f200-4a19-11ea-9118-198ee7466593.png)

they were took with chrome, but is the same behaviour with other browsers.
Is possible to notice the size on them changes.
