### ISSUE TITLE
I am not able to keep image and paragraph together (Splash layout)

### ISSUE THREAD

**Issue by edualvarado** [mmistakes/minimal-mistakes#2439]
Hello! 

I am very newbie with html, and using this theme, I am having a problem with the layout Splash.

I have the following feature: [link](https://i.imgur.com/fUpx7pt.jpg) written in my `index.html`

```
feature_row_background:
  - image_path: /assets/images/test_icon.png
    alt: "placeholder image 2"
    title: <font color="#4533AF ">Background</font>
    excerpt: "This is some sample content that goes here with **Markdown** formatting."
```

I want to take the image, make it quite smaller, close to the title, like this I did with paint: [link](https://i.imgur.com/KVuWAWe.jpg). 

I am able to manipulate more or less the margins, paddings and width in % to manipulate it, but I have two problems:
- It changes the features of all images since I am changing the whole class, I believe.
- When changing parameters and resizing the window, everthing gets started to get messy, if like title and image are not related anymore.

Is there any way just to make what I want in a simple way, only for that image instance?

Thank you very much!
