### ISSUE TITLE
Allow specifying navigation items target attribute

### ISSUE THREAD

**Issue by wildone** [mmistakes/minimal-mistakes#2445]
## Summary

When adding navigation items to external sources need to be able to open target URL in a new Tab.

## Motivation

Currently main navigation replaces current page which is fine for normal nav items, but when you have navigations items pointing to external sites need to be able to open them in a new tab.

## Updates needed

updating masthead.html allows this

```
<li class="masthead__menu-item">
    <a target="{{ link.target }}" href="{{ link.url | relative_url }}"{% if link.description %} title="{{ link.description }}"{% endif %}>{{ link.title }}</a>
</li>
```

This then can be activate using the navigation.yml

```
# main links
main:
  - title: "Home"
    url: /
  - title: "Tools"
    url: /tools/
  - title: "Blog"
    url: /blog/
  - title: "About"
    url: /about/
  - title: "GitHub"
    target: _blank
    url: https://github.com/wildone/maxbarrass.com
  - title: "Search"
    url: /search/
```
