### ISSUE TITLE
utterance comment does not appear working locally to me.

### ISSUE THREAD

**Issue by fdq09eca** [mmistakes/minimal-mistakes#2457]
I have followed the [instruction](https://mmistakes.github.io/minimal-mistakes/docs/configuration/#utterances-comments), installed utterance and run `JEKYLL_ENV=production jekyll s` in the terminal but the comment section does not appear locally. 

Moreover, although it serves successfully (the local serve is up), Jekyll cannot read the `_posts` folder (all posts become 404).. unless I running `jekyll s` without `JEKYLL_ENV=production`, any idea why? here is my `_config.yml` and installation of utterance:

```yml
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true

repository: "fdq09eca/Chris_personal"
comments:
  provider: "utterances"
  utterances:
    theme: "github-dark" # "github-dark"
    issue_term: "pathname"
```
![image](https://user-images.githubusercontent.com/51902242/77304473-74483080-6d2f-11ea-8952-92b6c6cb5f7e.png)
