### ISSUE TITLE
does frontmatter `author` work in 'single' layout or it only works in posts?

### ISSUE THREAD

**Issue by fdq09eca** [mmistakes/minimal-mistakes#2462]
I have different authors who is responsible for different `page`; however, the `author` frontmatter does not work unless it is `author_profile` but the latter it only a single author, which is me. any idea?

**Comment by fdq09eca** [comment]
ok, the solution is enable `author_profile` and override it by `author`
for example:
```yml
---
author_profile: true
author: somebody_in_authors.yml
---
```
