### ISSUE TITLE
Unable to integrate disqus comments

### ISSUE THREAD

**Issue by tranlyvu** [mmistakes/minimal-mistakes#2527]
Hi

I am not able to integrate the Disqus with my site, although all my configurations seem correct

source: https://github.com/tranlyvu/tranlyvu.github.io
host: https://www.netlify.com
site : https://distributedsystemsblog.com

 _config.yml

```
comments:
  provider               : "disqus" # false (default), "disqus", "discourse", "facebook", "staticman", "staticman_v2", "utterances", "custom"
  disqus:
    shortname            : distributedsystemsblog-com 
```

```
# Defaults
defaults:
  # _docs
  - scope:
      path: ""
      type: docs
    values:
      layout: single
      read_time: true
      share: true
      comments: true
      toc: true
      toc_label: "Table of Contents"
      sidebar:
        nav: "docs"

    # _posts
  - scope:
      path: ""  
      type: posts
    values:
      layout: single
      toc: true
      toc_label: "Table of Contents"
      author_profile: true
      author: Tran Ly Vu
      read_time: true
      comments: true
      share: true
      related: true
```
