### ISSUE TITLE
footer links nofollow

### ISSUE THREAD

**Issue by marcbompart** [mmistakes/minimal-mistakes#2530]
Would it be possible to have a new yaml boolean flag for the footer links; so we can decise if we want to follow or not the link.

**Comment by marcbompart** [comment]
...at the moment I've hardcoded some internal links by overriding the footer.html which is not ideal

**Comment by iBug** [comment]
It's all too common to override `footer.html` so I'd say it's better to keep your current setup.

**Comment by mmistakes** [comment]
Not in favor of more config flags but an option I'd entertain would be a check on `url`. If it's absolute (e.g. begins with `http(s)://` then treat the link as an external and apply `rel="nofollow noreferrer"`.

If it's a relative then treat as internal and allow it to be followed.

**Comment by iBug** [comment]
@mmistakes But how to insert links into footer? Then it still boils down to overriding the include file :)

**Comment by mmistakes** [comment]
@iBug Same way you do today using `site.footer` in _config.yml. These are added to the footer links section in [that include](https://github.com/mmistakes/minimal-mistakes/blob/master/_includes/footer.html#L7-L13). Only thing needed would be a check in that loop to see if `footer.links.url` are absolute/relative and then apply the appropriate `rel` attributs.

Example:

```
footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/"
```
