### ISSUE TITLE
Linkedin account URL munged

### ISSUE THREAD

**Issue by davekopecek** [mmistakes/minimal-mistakes#255]
My Linkedin URL ends in 054b4618 and was getting munged to '18/b46/54'. (Removing the 'b' makes it stop munging but that's not a fix.) This appears to be a liquid thing. Adding the cgi_escape filter to the liquid tag in _author-bio.html  resolves the issue:

    <a href="http://linkedin.com/in/{{ author.linkedin | cgi_escape }}" class="author-social" target="_blank">

**Comment by mmistakes** [comment]
Do you have a public repo experiencing the issue? I can't seem to reproduce it.

Adding this to my `_config.yml`

```yaml
author:
  linkedin: "054b4618"
```
Produces this hyperlink, which clearly isn't screwing with string like it is for you.

```html
<a href="http://linkedin.com/in/054b4618">
```

Maybe there's some sort of encoding issue going or malformed YAM in your fileL. I'd like to avoid adding the `cgi_escape` filter if it isn't necessary. What's the full LinkedIn URL you're trying to use?

**Comment by davekopecek** [comment]
Repo: https://bitbucket.org/davekopecek/davekopecek.com 
Linked In Public Profile https://www.linkedin.com/in/dave-kopecek-054b4618

I'm doing this with Jekyll installed on Windows. My system info is in the readme. Feels like an underlying data type issue.

**Comment by mmistakes** [comment]
Very strange. Maybe it's a Windows 10 issue. I just built from your Bitbucket repo on both a Windows 7 machine and Mac OS X and both worked just fine with the LinkedIn URL correctly resolving.

![image](https://cloud.githubusercontent.com/assets/1376749/14433253/96d93b8c-ffdb-11e5-92d1-c4fc57de284d.png)

It feels like an encoding thing to me but I'm at a loss as to what's causing it. What happens if you wrap all the YAML strings in quotes?
```yaml
owner:
  name: "Dave Kopecek
  avatar: "dave-kopecek.jpg"
  bio: "The Blog That Time Forgot."
  email: "dave.kopecek@gmail.com"
  disqus-shortname: "davekopecek"
  twitter: "davekopecek"
  facebook: "davekopecek"
  google:
    analytics: "UA-15854484-1"
  bing-verify:
  github: "davekopecek"
  bitbucket: "davekopecek"
  stackoverflow: "4730908/dave-kopecek"
  linkedin: "dave-kopecek-054b4618"
  instagram: "davekopecek"
  pinterest: "davekopecek"
```

If you open one of the HTML pages in `_site` can you paste in what the HTML is for the LinkedIn line? Curious if it's correct there and the HTML encoding is off and the browser is screwing around with things.

This is what I have:

```html
<a href="http://linkedin.com/in/dave-kopecek-054b4618" class="author-social" target="_blank"><i class="fa fa-fw fa-linkedin-square"></i> LinkedIn</a>
```

**Comment by mmistakes** [comment]
Theme has been substantially rebuilt. Try the latest update and if the issue is still present please reopen.

**Comment by davekopecek** [comment]
Will do. Sorry for the non-response. Lost track of this one.

**Comment by leojhernandez** [comment]
How can I add the LinkedIn link to the config file? I can't seem to find a definite answer for this.

**Comment by mmistakes** [comment]
@leojhernandez Check the author links examples in the theme docs. Just replace one of the other social media links with LinkedIn url, label, icon etc.

https://mmistakes.github.io/minimal-mistakes/docs/configuration/#site-author

**Comment by leojhernandez** [comment]
@mmistakes Hey there, couldn't make it work. I even copy the link for the icon from fontawesome.
This is what I did in the author links section: 
 ```
   - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
        url: "https://www.linkedin.com/in/leonardojhernandez/"
```
Any suggestion?

**Comment by mmistakes** [comment]
Check your spacing/indents. YAML is unforgiving if you don’t use the correct amount of spaces.

```yaml
- label: "LinkedIn"
  icon: "fab fa-fw fa-linkedin"
  url: "https://www.linkedin.com/in/leonardojhernandez"
```
