### ISSUE TITLE
how to show less number pages in the `paginate`?

### ISSUE THREAD

**Issue by typo3ua** [mmistakes/minimal-mistakes#2573]
In the moment i have that `pagination`...
![pag_full](https://user-images.githubusercontent.com/638022/85151649-b44e7f00-b25c-11ea-8a6b-099ce3f0a92b.png)
....that is not good for small device.
how to show less number pages in the `paginate`?
for example: 
![pag_3_center](https://user-images.githubusercontent.com/638022/85152185-5cfcde80-b25d-11ea-83af-669ee6f7fc09.png)
OR
![pag_3_dot](https://user-images.githubusercontent.com/638022/85152382-9cc3c600-b25d-11ea-96e7-e6af520c7736.png)
is there possible adaptation for small devices?

**Comment by iBug** [comment]
Use jekyll-paginate-v2 and you'll be able to specify this yourself:

```yaml
# Copied from https://github.com/iBug/iBug-source/blob/master/_config.yml
paginate: null
paginate_path: "/blog/:num/"
pagination:
  enabled: true
  per_page: 8
  permalink: "/:num/"
  title: ":title - Page :num of :max"
  limit: 0
  sort_field: "date"
  sort_reverse: true
  trail:
    before: 3
    after: 3
```
