### ISSUE TITLE
image: feature: won't accept hotlinked http:// https:// image

### ISSUE THREAD

**Issue by maxheld83** [mmistakes/minimal-mistakes#26]
```
image:
  feature: abstract-5.jpg
  credit: dargadgetz
  creditlink: http://www.dargadgetz.com/ios-7-abstract-wallpaper-pack-for-iphone-5-and-ipod-touch-retina/
```

... won't accept a hotlinked http:// or https:// image.

I think Robpol86@98ee44245f55afe56ab034671cc6e9499483b97a did a conditional thing for the https://github.com/mmistakes/hpstr-jekyll-theme, accepting a hotlink if the input includes http/s and otherwise look in /images, so I'm wondering whether the same couldn't be done for https://github.com/mmistakes/minimal-mistakes.
