### ISSUE TITLE
Unable to display hero image

### ISSUE THREAD

**Issue by siddharthram** [mmistakes/minimal-mistakes#2633]
I am unable to get minimal mistakes to display the hero image. Here is the relevant sections of my _config.yml

```
header:
  image                  : /assets/images/inflection-logo.jpg
```
```
# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      share: true
      related: true
      comments: true

```

I am using the default home.html. The output can be seen at blog.inflection.com. Inspector in chrome does not issue a call for the hero image. I assume I have somehow misconfigured the theme.

**Comment by iBug** [comment]
The header image should be specified in **page**, not site.

**Comment by mmistakes** [comment]
If you want to apply that header to multiple posts you can include it in the defaults you have above. For example to have it show on all posts...

```yaml
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      header:
        image: "/assets/images/inflection-logo.jpg"
      author_profile: true
      read_time: true
      share: true
      related: true
      comments: true
```

**Comment by siddharthram** [comment]
Thank you. Just to clarify: by page, do you mean home.html in _layouts? If not, could you just point me to the right section in the document?

**Comment by iBug** [comment]
By **page** I mean the front matter on each document (Markdown or HTML).

Check the Jekyll docs on this: <https://jekyllrb.com/docs/front-matter/>

You should have something like this at the very top of your source file (e.g. `example.md`):

```yaml
---
header:
  image: /assets/images/inflection-logo.jpg
---
```
