### ISSUE TITLE
writing of related_label

### ISSUE THREAD

**Issue by jphconstantin** [mmistakes/minimal-mistakes#2663]
Small details: if the string **related_label** in ui_text.yml is written in lower case, single.html display it in uppercase.
In fact the user has no choice.
Desired by the author ?

**Comment by mmistakes** [comment]
Feel free to submit a pull request to make them consistent.

**Comment by iBug** [comment]
It's controlled by CSS. Add the following CSS as your custom to override it and restore the default behavior:

```scss
.page__share-title {
  text-transform: initial;
}
```
