### ISSUE TITLE
How could I center the caption of an image?

### ISSUE THREAD

**Issue by hardianlawi** [mmistakes/minimal-mistakes#2682]
Hi, I am a noobie in both html and CSS. This [page](https://mmistakes.github.io/minimal-mistakes/docs/helpers/) shows how to add an image with caption, but I would like to position the caption in the middle of the image. What is the cleanest way to do that? A follow-up question, how could I create a reference of the image?

**Comment by iBug** [comment]
To center the image caption, the canonical way is via CSS:

```scss
figcaption {
  margin-left: auto;
  margin-right: auto;
}
```

For "reference", can you elaborate on what it exactly is?
