### ISSUE TITLE
Fix Follow button alignment in author profile

### ISSUE THREAD

**Issue by mmistakes** [mmistakes/minimal-mistakes#274]
Alignment looks off. Remove bottom margin on `.btn` and change vertical alignment to middle instead of top.

```css
.author__urls-wrapper {
  vertical-align: middle;
}
```

![screen shot 2016-04-17 at 11 24 02 am](https://cloud.githubusercontent.com/assets/1376749/14588130/c7543876-048f-11e6-8bff-0631af51d3f4.png)
