### ISSUE TITLE
author_info not working on posts

### ISSUE THREAD

**Issue by davidobrien1985** [mmistakes/minimal-mistakes#282]
Hi,

I'm really not an expert with all of this, so excuse me if this is a stupid one.

I managed to move my blog from Wordpress to github pages and I'm using this theme here.

https://davidobrien1985.github.io
https://github.com/davidobrien1985/davidobrien1985.github.io

Now my `_config.yml` has also this in it:
```
defaults:
  -
    scope:
      path: ""
      #type: posts
    values:
      layout: single
      read_time: true
      author_profile: true
      share: true
      comments: true
      related: true
```

However, the author_info only shows up on the `index.html` and on sites under `_pages` not on any of my posts.
I checked the source on the resulting websites (example: https://davidobrien1985.github.io/2016/02/conference-session-recordings-from-nicconf/ ) and it tries to display the author_info however all the variables seem to be empty?

What am I missing? 

Cheers
David

**Comment by hkalant** [comment]
Are you sure you have completed all the author info that is available in `_config.yml` (e.g. twitter username etc)?

**Comment by davidobrien1985** [comment]
@hkalant check https://github.com/davidobrien1985/davidobrien1985.github.io/blob/master/_config.yml

This post shows the author_info now:
https://raw.githubusercontent.com/davidobrien1985/davidobrien1985.github.io/master/blog/_posts/2016-02-26-conference-session-recordings-from-nicconf.md or https://davidobrien1985.github.io/2016/02/conference-session-recordings-from-nicconf/

All of the others don't, except for the `index.html` on https://davidobrien1985.github.io/

It's all the same _config.yml so no idea why it's not working on most files.

**Comment by mmistakes** [comment]
@davidobrien1985 You're pretty close to getting it working but I spotted one small thing.

In your posts you have `author: "David O'Brien"` which is enabling the [author override](https://mmistakes.github.io/minimal-mistakes/docs/authors/) feature. Essentially what's going on is in each post/page you have `author:` set with a string, the theme is looking for a corresponding key in `_data/authors.yml` to assign all of the sidebar stuff to. Since that doesn't exist for you, you get all the blank stuff.

To fix it you have a couple of options.

**1.** Create `authors.yml` with something like the following and place it in `_data`

```yaml
# authors.yml
David O'Brien:
  name             : "David O'Brien"
  avatar           : "me.png"
  bio              : "MVP for Cloud and Datacentre management. Interested in all things automation."
  location         : "Melbourne Australia"
  email            : "me@david-obrien.net"
  github           : "davidobrien1985"
  twitter          : "david_obrien"
```

**2.** Remove `author: "David O'Brien"` from your posts and pages. This will force things to default to the `site.author` and the strings in `_config.yml` will be used.

Hope this helps.
