### ISSUE TITLE
Question - Archive layout items

### ISSUE THREAD

**Issue by dpron** [mmistakes/minimal-mistakes#285]
I'm using jekyll-archives and am trying to get the archive-taxonomy layout to include the author sidebar as well as a default header image.

Unfortunately, when I set author_profile: true, it doesn't include the author sidebar.

I also tried adding the block of includes around page__hero that is present in other layouts, but it doesn't seem to pick up the values from adding header:/image: to the yaml of the archive-taxonomy.html layout.

Any hints?

**Comment by mmistakes** [comment]
Where were you adding `author_profile: true`? I just did a test and by changing `author_profile: false` to `true` in  [`_layouts/archive-taxonomy.html`](https://github.com/mmistakes/minimal-mistakes/blob/master/_layouts/archive-taxonomy.html), the side bar for all the pages Jekyll Archives creates shows up.

![jekyll-archives-author-sidebar](https://cloud.githubusercontent.com/assets/1376749/14791624/abb6ca6a-0ae4-11e6-9cda-a78289ae0e66.jpg)

To use the `page__hero` include with the `archive-taxonomy.html` layout you'll need to do some customizing. That include is pulling in values from a post/page's YAML Front Matter. If you add YAML Front Matter to the layout that's not really page data as far as Jekyll is concerned but `layout` data.

For example if in `archive-taxonomy.html` you have:

```yaml
layout: default
author_profile: true
your_variable: "Some data here."
```

To access it you'd use `{{ layout.your_variable }}`. So in theory you'd have to modify all of the `page.header` variables in the `page-hero.html` include to use `layout.header` instead.

I haven't worked much with layout variables but I have seen a lot of weird behaviors with them. Depending on which version of Jekyll you're using it [may or may not work](https://github.com/jekyll/jekyll/issues/4246)... and/or inherit properly in other layouts. Just something to be mindful of.

**Comment by dpron** [comment]
Yup, I changed author_profile from false to true and it doesn't seem to make a difference.  

If it matters, here's my archives section from _config.yml

```
# Archives
#  Type
#  - GitHub Pages compatible archive pages built with Liquid ~> type: liquid (default)
#  - Jekyll Archives plugin archive pages ~> type: jekyll-archives
#  Path (examples)
#  - Archive page should exist at path when using Liquid method or you can
#    expect broken links (especially with breadcrumbs enabled)
#  - <base_path>/tags/my-awesome-tag/index.html ~> path: /tags/
#  - <base_path/categories/my-awesome-category/index.html ~> path: /categories/
#  - <base_path/my-awesome-category/index.html ~> path: /
#categories:
#  type: jekyll-archives
#  path: /categories/
#tags:
#  type: jekyll-archives
#  path: /tags/
# https://github.com/jekyll/jekyll-archives
jekyll-archives:
  enabled:
    - categories
    - tags
  layouts:
    category: archive-taxonomy
    tag: archive-taxonomy
  permalinks:
    category: /categories/:name/
    tag: /tags/:name/
```

**Comment by dpron** [comment]
Also, if it matters - versions: jekyll 3.1.3, jekyll-archives 2.1.0

**Comment by mmistakes** [comment]
Not sure if this will make a difference but you forgot to uncomment a few things.. specifically the categories and tags options. This is what I used in my quick test. 

```yaml
# Archives
#  Type
#  - GitHub Pages compatible archive pages built with Liquid ~> type: liquid (default)
#  - Jekyll Archives plugin archive pages ~> type: jekyll-archives
#  Path (examples)
#  - Archive page should exist at path when using Liquid method or you can
#    expect broken links (especially with breadcrumbs enabled)
#  - <base_path>/tags/my-awesome-tag/index.html ~> path: /tags/
#  - <base_path/categories/my-awesome-category/index.html ~> path: /categories/
#  - <base_path/my-awesome-category/index.html ~> path: /
categories:
  type: jekyll-archives
  path: /categories/
tags:
  type: jekyll-archives
  path: /tags/
# https://github.com/jekyll/jekyll-archives
jekyll-archives:
  enabled:
    - categories
    - tags
  layouts:
    category: archive-taxonomy
    tag: archive-taxonomy
  permalinks:
    category: /categories/:name/
    tag: /tags/:name/
```

Do you have a public repo somewhere that I could look at? It's probably something simple you're missing as I was able to get it working without much effort.
