### ISSUE TITLE
How to make text more mobile-friendly?

### ISSUE THREAD

**Issue by Rainymood** [mmistakes/minimal-mistakes#3043]
Hi,

I love minimal mistakes and have been using it for multiple years.

I would love to know how to make the text more mobile-friendly. 

What I mean by this is illustrated in the next picture:

![image](https://user-images.githubusercontent.com/2186137/124494939-c04da600-ddb7-11eb-82f9-9b1bb15da14e.png)

On the left-hand side we see my website viewed on an iPhone X, on the right-hand side we see the website of [Brian Lovin](www.brianlovin.com). 

How do I make my text (only on mobile) look more like the text on the right?

I run minimal mistakes as a remote theme through Github pages and this is what my `assets/css/main.scss` looks like:

```css

html {
  font-size: 12px; // change to whatever

  @include breakpoint($small){
    font-size: 12px; // change to whatever
  }

  @include breakpoint($medium) {
    font-size: 14px; // change to whatever
  }

  @include breakpoint($large) {
    font-size: 16px; // change to whatever
  }

  @include breakpoint($x-large) {
    font-size: 18px; // change to whatever
  }
}
```
