### ISSUE TITLE
bar showing below google adsense

### ISSUE THREAD

**Issue by hoondy** [mmistakes/minimal-mistakes#306]
![screen shot 2016-05-05 at 12 45 22 pm](https://cloud.githubusercontent.com/assets/6531609/15050006/515c6c04-12bf-11e6-8fc5-00c0671db72a.png)

When you put an ad using google adsense, black bar below ad shows up and I don't know where it is coming from.

**Comment by mmistakes** [comment]
Cases like this is when your browsers web developer tools come in handy. You can right click an element and see all the styling attached to it.

In this case a 1px bolder is applied to `<u>` and `<ins>` elements. Google uses `<ins>` for some reason in their AdSense markup.

```css
u, ins {
  text-decoration: none;
  border-bottom: 1px solid #494e52;
}
```

To fix it add something like this to your stylesheet.

```css
ins.adsbygoogle {
  border-bottom: none !important;
}
```

![banner](https://cloud.githubusercontent.com/assets/1376749/15051477/cc7187a6-12c6-11e6-80f6-f0d8d45f37a3.jpg)
