### ISSUE TITLE
Multiple Navigations in Sidebar (mul-behavior showed by gif)

### ISSUE THREAD

**Issue by WhymustIhaveaname** [mmistakes/minimal-mistakes#3089]
## Environment

- Minimal Mistakes version: cloned from this repo's master 5 mins ago.
- Ruby gem or remote theme version: ruby 2.7.3p183 (2021-04-05 revision 6847ee089d) [x86_64-linux]
- Jekyll version: 4.2.0
- Operating system: Fedora 32

## Steps to reproduce the behavior

When the mouse hovering on the sidebar, the sidebar's opacity will change. However, when there are multiple nav's in the sidebar, their opacity will all changed or not changed. This is not beautiful. What's more, when the screen is small ("Toggle menu" appears), all the "toggle menu" buttons could only open the first nav. 

![minimal-mistake-issue1](https://user-images.githubusercontent.com/38423345/127449571-ed28bf8f-9a36-4480-b4ff-1905ddd7ec53.gif)
![minimal-mistake-issue2](https://user-images.githubusercontent.com/38423345/127449890-e966e2f4-efc5-4210-b4b9-9a2bdf4c8b53.gif)

The codes are as follows. 

`home.md`:
```
---
title: "Gauge Theory Workshop"
permalink: /home.html
layout: single
classes: wide
toc: false
sidebar:
    - nav: sitemap
    - nav: contact
---

* Dates: 24-26 Sept 2021
* Venue: Yau Mathematical Sciences Center, Tsinghua University
* Contact Information
    <ul>{% for child in site.data.navigation.contact[0].children %}
            <li><div>{{child.title}}</div><a href="mailto:{{ child.mail }}">{{ child.mail }}</a></li>
    {% endfor %} </ul>
```

`navigation.yml`:
```
sitemap:
    - title: "Sitemap"
      children:
          - title: "Home"
            url: /home.html
          - title: "Schedule"
            url: /schedule.html
          - title: "Speakers"
            url: /speakers.html
          - title: "Participants"
            url: /participants.html

contact:
    - title: "Contact Information"
      children:
          - title: "Person A"
            mail: "a@mail.com"
          - title: "Person B"
            mail: "b@mail.com"
```

This behavior is due to all the nav's are using the same CSS class or id. I cure the first issue by add `nav.title` to `id="ac-toc"` in _includes/nav_list.
```
<input id="ac-toc {{ nav.title }}" name="accordion-toc" type="checkbox" />
<label for="ac-toc {{ nav.title }}">{{ nav.title | site.data.ui-text[site.locale].menu_label | default: "Toggle Menu" }}</label>
<!--Original-->
<input id="ac-toc" name="accordion-toc" type="checkbox" />
<label for="ac-toc">{{ site.data.ui-text[site.locale].menu_label | default: "Toggle Menu" }}</label>
```

For the second issue, I disabled hover in the CSS class file and rewrite the behavior in _includes/nav_list. using inline js.
```
<nav class="nav__list" style="opacity:0.75" onMouseOver="this.style.opacity=1" onMouseOut="this.style.opacity=0.75">
<!--Original-->
<nav class="nav__list">
```

My repo with above changes is [ymsc-strings/gauge-theory-workshop-sept-2021](https://github.com/ymsc-strings/gauge-theory-workshop-sept-2021).

I did not submit a pull request because I think this is a mere ad-hoc solution and I believe you have better solutions. This repo is excellent! Thank you very much for your template anyhow.

**Comment by iBug** [comment]
This doesn't look like its intended usage.

**Comment by WhymustIhaveaname** [comment]
Thank you for so prompt reply! Indeed, I put together several Stackoverflows and finally made this Frankenstein. 

From the source code `_includes\sidebar.html` and `_includes\nav_list`, it seems that the author wanted to support this usage and it works. What's more, I want to show the two nav's on every page (there are and will be many pages) so this is the most convenient way.

**Comment by iBug** [comment]
Multiple `nav_list`s, however, is probably not intended. The ability to add multiple sidebar items allows you to add text, images, and up to one `nav_list`. If you want multiple menus in the navigation bar, do it this way instead:

```yaml
sitemap:
    - title: "Sitemap"
      children:
          - title: "Home"
            url: /home.html
          - title: "Schedule"
            url: /schedule.html
          - title: "Speakers"
            url: /speakers.html
          - title: "Participants"
            url: /participants.html
    - title: "Contact Information"
      children:
          - title: "Person A"
            mail: "a@mail.com"
          - title: "Person B"
            mail: "b@mail.com"
```
