### ISSUE TITLE
Comments not working (update - possible typo in original repo)

### ISSUE THREAD

**Issue by nickdex** [mmistakes/minimal-mistakes#318]
Comments are not visible on my website.
I created an account on disqus and added shortname to _config.yml thereafter, I tried setting comments to true as default in _config.yml and for individual post.
I also tried facebook, and goolge-plus as shown in guide but still not working.
How should I proceed from here? Any help is appreciated.
Its my first time working with jekyll and such.

**Update** - On line 19 in minimal-mistakes/_includes/comments-providers/disqus.html
it is   `}());` whereas it should be `})();` 
Im not sure if it is correct but I am getting error 
`Uncaught TypeError: Cannot read property 'appendChild' of null`

**Comment by mmistakes** [comment]
I don't think `}());` is wrong as the entire Disqus script came directly from them unmodified. 

It could be the fact that you have your post using `layout: splash` instead of `layout: single`.

Disqus is clearly working as I have it going on the demo site.

https://mmistakes.github.io/minimal-mistakes/layout/uncategorized/layout-comments/

and here's the source for that page https://github.com/mmistakes/minimal-mistakes/blob/gh-pages/_posts/2012-01-02-layout-comments.md

Looking at your repo you're missing `comments: true` in the post's YAML Front Matter. You can also apply it as a Front Matter default for all posts by adding the following to your `_config.yml`.

```yaml
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
```
