### ISSUE TITLE
Utterances not working on nomemory/andreinc-site

### ISSUE THREAD

**Issue by nomemory** [mmistakes/minimal-mistakes#3240]
### What happened?

- Minimal Mistakes version: 
- Ruby gem or remote theme version: gem 'minimal-mistakes-jekyll', '~> 4.24'
- Jekyll version:
- Git repository URL: https://github.com/nomemory/andreinc-site
- Hosted on GitHub Pages (if yes provide URL to site): www.andreinc.net
- Operating system: MACOS

### Expected behavior

I've added utterances support in the configuration:

```
repository: "nomemory/andreinc-site"
comments:
  provider: "utterances"
  utterances:
    repo:  "nomemory/andreinc-site"
    theme: "github-light" # "github-dark"
    issue_term: "pathname"
```

Also installed utterances app on github.

But the comments are not showing up on any of my articles, even if they are manually enabled.

### Steps to reproduce the behavior

Configuration:

```
repository: "nomemory/andreinc-site"
comments:
  provider: "utterances"
  utterances:
    repo:  "nomemory/andreinc-site"
    theme: "github-light" # "github-dark"
    issue_term: "pathname"
```

### Other

When analysing the HTML I can see the utterances script being present in the page:

```

  'use strict';

  (function() {
    var commentContainer = document.querySelector('#utterances-comments');

    if (!commentContainer) {
      return;
    }

    var script = document.createElement('script');
    script.setAttribute('src', 'https://utteranc.es/client.js');
    script.setAttribute('repo', 'nomemory/andreinc-site');
    script.setAttribute('issue-term', 'pathname');
    script.setAttribute('theme', 'github-light');
    script.setAttribute('crossorigin', 'anonymous');

    commentContainer.appendChild(script);
  })();

```

But I cannot find any div with `id="utterances-comments"` in the page.

If I add manually the div comments are showing.
