### ISSUE TITLE
Individual image captions?

### ISSUE THREAD

**Issue by jengalas** [mmistakes/minimal-mistakes#334]
- [x] This is a question about using the theme.

---
Two questions about image captions:

1. Does the theme provide a way to add captions to *individual* images (using either `<figure>` or gallery) rather than simply one caption for the entire group/gallery?

2. Is there a straightforward way to display the caption below the image in the popup/lightbox view? Any way to populate the div.mfp-title? Something like adding a `title:` or `caption:` attribute to each gallery image in the front matter, and then somehow setting that as the titleSrc in the Magnific Popup options.

**Comment by mmistakes** [comment]
1. No the theme only supports 1 caption per `<figure>` element. I couldn't find a consistent way of styling the grid with captions that may or may not be on every image.

2. the `gallery` helper could be modified to include a `title` attribute that I believe [Magnific Popup](http://dimsemenov.com/plugins/magnific-popup/) uses to populate the overlay caption. Other option would be to possibly [modify the JavaScript](http://dimsemenov.com/plugins/magnific-popup/documentation.html#image-type) to have MP use the `alt` attribute as the image's `titleSrc`.

I'm thinking enhancing the `gallery` helper might be the way to go. Could change [L#35 and 44](https://github.com/mmistakes/minimal-mistakes/blob/master/_includes/gallery#L35) to something like:

```html
alt="{% if img.alt %}{{ img.alt }}{% endif %}"
title="{% if img.title%}{{ img.title}}{% endif %}">
```

And then the title could be set in YAML like:

```yaml
gallery:
  - url: unsplash-gallery-image-1.jpg
    image_path: unsplash-gallery-image-1-th.jpg
    alt: "placeholder image 1"
    title: "Title for image 1"
  - url: unsplash-gallery-image-2.jpg
    image_path: unsplash-gallery-image-2-th.jpg
    alt: "placeholder image 2"
    title: "Title for image 2"
```
