### ISSUE TITLE
Author profile links' alignment are off in sidebar

### ISSUE THREAD

**Issue by mmistakes** [mmistakes/minimal-mistakes#341]
Icons are using `.fa-fw` class to apply fixed width styling but is overridden. Remove `initial` or reset back to `inline-block`.

```css
.social-icons .fa {
  display: initial;
}
```
