### ISSUE TITLE
No text displayed for 'Next' or 'Previous' for en-GB locale

### ISSUE THREAD

**Issue by russellseymour** [mmistakes/minimal-mistakes#377]
I have copied the `gh-pages` branch of the theme as an example to work with.

I have got the following configured in `ui-text.yml`:

```yml
en: &DEFAULT_EN
  page                  : "Page"
  pagination_previous   : "Previous"
  pagination_next       : "Next"
  breadcrumb_home_label : "Home"
  breadcrumb_separator  : "/"
```

But when I go to one of my `_docs` pages the Next and Previous is not dispayed:

![image](https://cloud.githubusercontent.com/assets/791658/16339681/d9880d30-3a1b-11e6-982a-3a9a5f4dcfce.png)

![image](https://cloud.githubusercontent.com/assets/791658/16339703/023dde3a-3a1c-11e6-9286-38174d413a4b.png)

I am not sure why may pages are not displaying this.  The link works, although there is no text to show that there is a link.  I assume I am missing something obvious but I cannot see it.
