### ISSUE TITLE
How to include collection posts in category-archive?

### ISSUE THREAD

**Issue by philectron** [mmistakes/minimal-mistakes#405]
- [x] This is a question about using the theme.
- [ ] I believe this to be a bug with the theme --- not Jekyll, GitHub Pages or one of the bundled plugins.
- [ ] This is a feature request.
- [x] I have updated all gems with `bundle update`.
- [x] I have tested locally with `bundle exec jekyll build`.

---

## Environment information

- **Minimal Mistakes version:** 3.3.3
- **`github-pages` or `jekyll` gem version:** jekyll 3.1.6
- **Operating system:** Windows

---

## Expected behavior

I assigned the same category for two posts. I set one post in the `_posts` folder, and the other post in the `_my-collection` folder. I have already setup the declaration and front matters for `my-collection`:

```yaml
# Collections
collections:
  my-collection:
    output: true
    permalink: /:collection/:path/

# Front Matter Defaults for _posts, _pages, and collections
defaults:
  # _my-collection
  - scope:
      path: ""
      type: my-collection
    values:
        layout: single
        author_profile: false
        share: true

```

I expected that once I go to `/categories/`, **I should see two posts appear at the same category list.**

## My Issue
However, I didn't see the post in `_my-collection` appear in the list but only the other post in the `_posts` folder

I use your [category-archive.html](https://github.com/mmistakes/minimal-mistakes/blob/gh-pages/_pages/category-archive.html) layout.

How should I edit the code so that it would search in `_my-collection` also? Thanks!
