### ISSUE TITLE
Translate UI text for new strings

### ISSUE THREAD

**Issue by mmistakes** [mmistakes/minimal-mistakes#449]
As part of #424 several new text strings need translating in [`/_data/ui-text.yml`](https://github.com/mmistakes/minimal-mistakes/blob/master/_data/ui-text.yml). Pull requests welcome :smile:
- [x] Spanish
- [x] Brazilian Portuguese
- [x] Turkish
- [x] Italian
- [x] French

``` yaml
comments_title             : "Comments"
comment_form_info          : "Your email address will not be published. Required fields are marked"
comment_form_comment_label : "Comment"
comment_form_md_info       : "Markdown is supported."
comment_form_name_label    : "Name"
comment_form_email_label   : "Email address"
comment_form_website_label : "Website (optional)"
comment_btn_submit         : "Submit Comment"
comment_btn_submitted      : "Submitted"
comment_success_msg        : "Thanks for your comment! It will show on the site once it has been approved."
comment_error_msg          : "Sorry, there was an error with your submission. Please make sure all required fields have been completed and try again."
loading_label              : "Loading..."
```
