### ISSUE TITLE
"You may also enjoy" recommends hidden posts, when it probably shouldn't

### ISSUE THREAD

**Issue by alichtman** [mmistakes/minimal-mistakes#4653]
### What happened?

- Minimal Mistakes version: `4.24.0`
- Ruby gem or remote theme version: `remote_theme: "mmistakes/minimal-mistakes"`
- Jekyll version: ` 3.9.3`
- Git repository URL: https://github.com/alichtman/alichtman.github.io (bad version isn't live though)
- Hosted on GitHub Pages: https://alichtman.github.io
- Operating system: Ubuntu 23.10, Linux

### Expected behavior

I have a hidden post in my repo. 

When I set `related: true` in my `_config.yml` file, like:

```
# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      show_date: true
      layout: single
      author_profile: true
      read_time: true
      comments: # true
      share: true
      related: true  ## Problem!
```

The hidden post is recommended. It probably shouldn't be!

### Steps to reproduce the behavior

- Add post that is set to `hidden`
- Enable recommended posts
- See that hidden post is recommended
