### ISSUE TITLE
Intro animation completely breaks Lighthouse

### ISSUE THREAD

**Issue by hschne** [mmistakes/minimal-mistakes#4698]
### What happened?

It's common practice to verify the performance of your page using Lighthouse/[Google Page Speed Insights](https://pagespeed.web.dev/). Unfortunately, the report is completely broken with the Minimal Mistakes theme. 

![minimalmistakes](https://github.com/mmistakes/minimal-mistakes/assets/5294464/35111333-0577-406a-ac04-76a211bb028b)

### Expected behavior

It would be nice to have this working. I'm pretty sure that wasn't always the case, and I assume that Google changed something or other 🤷

### Steps to reproduce the behavior

You can verify this easily enough with the [Minimal Mistakes homepage](https://mmistakes.github.io/minimal-mistakes/). 
1. Go to https://pagespeed.web.dev
2. Enter https://mmistakes.github.io/minimal-mistakes/ there
3. Wait
4. Receive a broken performance report. 
  ![Screen Shot 2024-02-20 at 09 25 06](https://github.com/mmistakes/minimal-mistakes/assets/5294464/90879b8b-8d68-499b-8b6f-61bc9b955be3)

### Other

I traced the issue to `$intro-animations` on `main`. Disabling the animation fixes the problem. 

```scss
$global-transition: none;
$intro-transition: none;

@import "minimal-mistakes/skins/{{ site.minimal_mistakes_skin | default: 'default' }}";
@import "minimal-mistakes";
```

I'm not sure what the best fix there is. Google uses page speed for SEO ranking, so this not working may be fairly impactful. However, I don't know if it warrants disabling animations altogether.
