### ISSUE TITLE
add sidebar nav instructions to documentation

### ISSUE THREAD

**Issue by bquast** [mmistakes/minimal-mistakes#476]
- [x] This is a question about using the theme.
- [ ] I believe this to be a bug with the theme --- not Jekyll, GitHub Pages or one of the bundled plugins.
- [ ] This is a feature request.
- [ ] I have updated all gems with `bundle update`.
- [ ] I have tested locally with `bundle exec jekyll build`.

---

## Environment informations

- **Minimal Mistakes version: 3.4.3** 
- **`github-pages`** 

---

**Comment by mmistakes** [comment]
Currently undocumented because I built it as a "one off" for the theme's documentation section. Wasn't really meant to be something as part of the theme as it's not the most straight forward thing to do. 

It involves manually listing out all of the links in a `_data` file and then referencing that set of navigation links with `sidebar: navName` in the YAML Front Matter of whatever post/page/collection you want it to appear on.

For example, the menu for the [theme's documentation](https://mmistakes.github.io/minimal-mistakes/docs/quick-start-guide/) was built by:

**`_data/navigation.yml`**

```yaml
# documentation links
docs:
  - title: Getting Started
    children:
      - title: "Quick-Start Guide"
        url: /docs/quick-start-guide/
      - title: "Structure"
        url: /docs/structure/
      - title: "Installation"
        url: /docs/installation/
      - title: "Upgrading"
        url: /docs/upgrading/

  - title: Customization
    children:
      - title: "Configuration"
        url: /docs/configuration/
      - title: "Navigation"
        url: /docs/navigation/
      - title: "UI Text"
        url: /docs/ui-text/
      - title: "Authors"
        url: /docs/authors/
      - title: "Layouts"
        url: /docs/layouts/

  - title: Content
    children:
      - title: "Working with Posts"
        url: /docs/posts/
      - title: "Working with Pages"
        url: /docs/pages/
      - title: "Working with Collections"
        url: /docs/collections/
      - title: "Helpers"
        url: /docs/helpers/
      - title: "Utility Classes"
        url: /docs/utility-classes/

  - title: Extras
    children:
      - title: "Stylesheets"
        url: /docs/stylesheets/
      - title: "JavaScript"
        url: /docs/javascript/

  - title: Meta
    children:
      - title: "History"
        url: /docs/history/
      - title: "Contributing"
        url: /docs/contributing/
      - title: "Old 2.2 Docs"
        url: /docs/docs-2-2/
      - title: "License"
        url: /docs/license/
      - title: "Terms &amp; Privacy Policy"
        url: /terms/
```

And then in each `_doc` collection page the following was added to the YAML Front Matter to pull in the navigation in the sidebar.

```yaml
sidebar:
  nav: "docs"
```

The better solution for adding the same YAML to multiple pages is with Front Matter Defaults in `_config.yml` like so:

```yaml
defaults:
  # _docs
  - scope:
      path: ""
      type: docs
    values:
      sidebar:
        nav: "docs"
```
