### ISSUE TITLE
Conflicting instructions about collections

### ISSUE THREAD

**Issue by asarkar** [mmistakes/minimal-mistakes#4982]
### Motivation

https://mmistakes.github.io/minimal-mistakes/docs/collections/

In `_pages/portfolio.md`
```
title: Portfolio
layout: collection
permalink: /portfolio/
collection: portfolio
entries_layout: grid
classes: wide
```

https://mmistakes.github.io/minimal-mistakes/docs/configuration/#paginate-v2

```
---
title: "Lovely pets"
layout: home
permalink: /pets/
pagination:
  enabled: true
  collection:
    - cat
    - dog
---
```

One uses a `collection` layout, and another `home`. Also, since each collection has its own page under `_pages`, how does the latter list two collections? What is the location and name of the file where the second front matter should go?

### Suggestion

Clarify.
