### ISSUE TITLE
Support for Bluesky in footer links

### ISSUE THREAD

**Issue by j2xl** [mmistakes/minimal-mistakes#5044]
### Theme version and system environment

- Minimal Mistakes version: 4.2.6
- Ruby gem or remote theme version: 3.3.7
- Jekyll version: 3.9.2
- Git repository URL: N/A
- URL to the page with the problem: N/A
- Operating system: macOS
- Browser version:

### What happened?

I tried adding info about my Bluesky social media account by adding configuration to my site author section in `_config.yml`. 
When I run Jekyll locally, other social media are displayed; Bluesky is not.

### Expected behavior

Bluesky link is displayed in the site footer.

### Steps to reproduce the behavior

I tried adding info about my Bluesky social media account by adding the following to my footer links section in `_config.yml`:

```
# Site Footer
footer:
  links:
    - label: "Bluesky"
      icon: "fab fa-fw fa-bluesky"
      url: "https://bsky.app/profile/weill.org"
```

When I run Jekyll locally, other social media are displayed; Bluesky is not. FontAwesome does have a Bluesky icon with the above class.

**Comment by iBug** [comment]
Please add a screenshot so I know how exactly "it's not displayed".

**Comment by j2xl** [comment]
The correct class sequence should be:

```
footer:
  links:
    - label: "Bluesky"
      icon: "fab fa-fw fa-bluesky"
      url: "https://bsky.app/profile/weill.org"
```

… but the Bluesky icon is only available in Font Awesome 6. This line suggests that we should be trying to load the latest version:

https://github.com/mmistakes/minimal-mistakes/blob/6f5e6f43911c0283bd029040a4b22d3d31fe3c30/_includes/head.html#L21C27-L21C108
