### ISSUE TITLE
author_profile not appearing on posts

### ISSUE THREAD

**Issue by twhite96** [mmistakes/minimal-mistakes#565]
Customized `_config.yml` to default to `author_profile: true` however it is not showing on the post pages, just the index.html. 

I found a closed issue but that does not seem to be the problem I am facing. You can find my `_config.yml` here: https://github.com/twhite96/twhite96.github.io/blob/master/_config.yml

Thanks for your help.

**Comment by mmistakes** [comment]
It's your defaults. You have a duplicate `defaults` key right before the pages scope. Remove that line. YAML is a picky thing.

**Comment by mmistakes** [comment]
Should read like this instead. The dupe `defaults` line  was replacing the first occurrence which is why none of your post defaults were taking.

```yaml
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
```
