### ISSUE TITLE
Site search

### ISSUE THREAD

**Issue by icicimov** [mmistakes/minimal-mistakes#588]
- [x] This is a question about using the theme.

---

Hi Michael,

I 'm thinking about setting up a site search function and came across this plugin https://github.com/slashdotdash/jekyll-lunr-js-search, that looks not too complicated to implement. Was wondering what are your thoughts on this and is there maybe a guide you would recommend for this functionality?

Thanks

**Comment by justinrummel** [comment]
I've got it running on my site. Warning, it doubles the time it takes to generate a site. I was finishing in 20s, but now with Lunt it takes over 40s. 

https://www.justinrummel.com/search/

**Comment by mmistakes** [comment]
@icicimov I don't have first-hand experience with Lunr but have used similar solutions. The instructions on  that repo seem pretty good but if you need more of a "tutorial" there's quite a few if you search around.

- http://jekyll.tips/jekyll-casts/jekyll-search-using-lunr-js/
- http://rayhightower.com/blog/2016/01/04/how-to-make-lunrjs-jekyll-work-together/
- http://katydecorah.com/code/lunr-and-jekyll/
- http://scotthorsfield.me/technology/2016/01/21/Searching-Jekyll-Post-and-Page-Content-with-lunr-js/

I'll echo what @justinrummel said about build times. I haven't read Lunr docs to know if this is true but I would assume it work by querying a `.json` index file with all of your post data in it. Depending on the complexity of that is what makes build times go up. 

Other Jekyll search solutions I've used had you build a `.json` file that loops over every post and then you can pull out things like post titles, post excerpts, etc. If Lunr is dumping the full content of every post that would certainly increase the bloat.

**Comment by justinrummel** [comment]
FYI; here are my commits for adding Lunr:

- [_config.yml](https://github.com/justinrummel/jr.com-mm/commit/da12b6944e4a7caf3965e443c1b16420e171d8ae)
- [A LOT MORE](https://github.com/justinrummel/jr.com-mm/commit/d2d0d620c5a5d0ddca283ecfe2eeb3b322f5b3b2)

**Comment by icicimov** [comment]
@mmistakes and @justinrummel, thank you both for your help and useful tips.

Pretty much following Justin's commit that he generously shared I have created the following structure:

_config.dev.yml:
```
# Plugins
gems:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - json
  - jekyll-lunr-js-search

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - json
  - jekyll-lunr-js-search

lunr_search:
  excludes: [rss.xml, atom.xml]
  stopwords: "stopwords.txt"
  min_length: 3
  js_dir: "/assets/js/lunr"
```

Gemfile:
group :jekyll_plugins do
  gem "jekyll-lunr-js-search"
end

_plugins/
├── jekyll_lunr_js_search.rb
└── related_posts.rb

assets/js/lunr/
├── date.format.js
├── jquery-1.12.4.min.js
├── jquery.lunr.search.js
├── lunr.min.js
├── mustache.min.js
├── search.min.js
└── URI.min.js

_includes/scripts.html

_includes/search.html

_pages/search.md:
```
---
author_profile: true
type: pages
layout: single
title: Search
permalink: /search/
exclude_from_search: true
---
{% include search.html %}
```

but during the local site build the **index.json** file is not being created and I get  ERROR `/blog/assets/js/lunr/index.json' not found.

To me it looks like the plugin is not working for some reason. Do I need to do anything else apart from the above to get the plugin activated?

Thanks again for your help, very much appreciated.
Igor
