### ISSUE TITLE
Language switcher ?

### ISSUE THREAD

**Issue by chrisvidal** [mmistakes/minimal-mistakes#612]
hi,

- [x] This is a question about using the theme.
- [x] This is a feature request.

how to internationalise the content (posts, pages and collections) and using a language switcher ?

**Comment by mmistakes** [comment]
This is out of scope for the theme.

You could use a plugin to do multi-language posts/pages/collections if you're not hosting with GitHub Pages.

- https://github.com/vwochnik/jekyll-language-plugin
- https://github.com/octopress/multilingual

Otherwise you can follow the advise of this tutorial to implement it.

- https://www.sylvaindurand.org/making-jekyll-multilingual/

**Comment by chrisvidal** [comment]
thanks for the pointers :)

**Comment by frankgerhardt** [comment]
Are the solutions at the given links known to work, or would I have to figure out myself if those solutions can be made to work?

**Comment by chrisvidal** [comment]
i implemented quite easily the method used in the 3rd link in my mm project
https://www.sylvaindurand.org/making-jekyll-multilingual/

**Comment by vlsi** [comment]
@chrisvidal , can you please give a hint how did you manage with `locale: ???` in `_config.yml`?
As far as I understand, minimal-mistakes has just a single configuration option for `locale`, so it is not clear how a single build would produce pages with different `locale:...` values.
`locale: ...` at page level does not seem to override `site.locale`.

**Comment by rriemann** [comment]
@chrisvidal, is your take on multi-language online? Maybe even the source?

**Comment by chrisvidal** [comment]
@rriemann not live yet, the client is still in UAT process, but the staging is available there mom-iali.design-voilaah.com/

@vlsi I have a file ui-text.yaml in the data folder which contains the locale
```yaml
# User interface text and labels

# English (default)
# -----------------
en: &DEFAULT_EN
  page                       : "Page"
  pagination_previous        : "Previous"
  pagination_next            : "Next"
  breadcrumb_home_label      : "Home"

es: &DEFAULT_ES
  page                       : "Página"
  pagination_previous        : "Anterior"
  pagination_next            : "Siguiente"
  breadcrumb_home_label      : "Inicio"
````
