### ISSUE TITLE
How do you customize the number of columns in the Archive grid view?

### ISSUE THREAD

**Issue by elipousson** [mmistakes/minimal-mistakes#623]
- [X] This is a question about using the theme.

---

This may be an obvious question (I haven't used Sass or Susy before trying to modify this theme) but I haven't been able to figure it out yet and didn't see any tips in the documentation.

How do you increase the width of archive items in the [Archive grid view](https://mmistakes.github.io/minimal-mistakes/docs/layouts/#grid-view) and/or limit the number of archive items that can appear in a single row?

[This is the page](https://localpreservation.github.io/resources/) that I am trying to customize – there are only three items displayed right now but I'm planning to add several more.

**Comment by mmistakes** [comment]
It's all done through CSS. More specifically Sass and a set of mixins provided by Susy. The best tip I can give you is turn on the web developer tools of whatever browser you're using and start inspecting elements on the page (right click... tap inspect element).

![web-dev-tools](https://cloud.githubusercontent.com/assets/1376749/19859107/8126f67a-9f5a-11e6-8c96-c77537ccefa7.jpg)

You'll quickly see what elements have what styles on them and then you can dig deeper into the `.scss` partials by searching by those class names.

In the case of the archive `grid__item` classes you can find them here in [**_sass/_archives.scss**](https://github.com/mmistakes/minimal-mistakes/blob/master/_sass/_archive.scss#L124-L145)

```scss
@include breakpoint($small) {
    @include gallery(5 of 10);
    .archive__item-teaser {
      max-height: 200px;
    }
  }

  @include breakpoint($medium) {
    margin-left: 0; /* reset before mixin does its thing*/
    margin-right: 0; /* reset before mixin does its thing*/
    @include gallery(2.5 of 10);

    .archive__item-teaser {
      max-height: 120px;
    }

    .archive__item-excerpt {
      display: block;
      font-size: $type-size-6;
    }
  }
```

What's going on here is, there are several breakpoints (starts with the smallest width and builds up) that use Susy's [`gallery` mixin](http://susydocs.oddbird.net/en/latest/toolkit/#gallery) to do some math and calculate the widths, add floats, margins, etc.

On [`$small`](https://github.com/mmistakes/minimal-mistakes/blob/master/_sass/_variables.scss#L106) screens: `@include gallery(5 of 10);` means span this element across 5 columns of a 10 column grid, eg. 1/2th of the parent container (2 items in a row).

On [`$medium`](https://github.com/mmistakes/minimal-mistakes/blob/master/_sass/_variables.scss#L107) and up screens: `@include gallery(2.5 of 10);` means span this element across 2.5 columns of a 10 column grid, eg. 1/4th of the parent container (4 items in a row)

If you want to fit more or less items in a row you'll need to change those values.
