### ISSUE TITLE
Add support for links/buttons in Sidebar

### ISSUE THREAD

**Issue by saguiitay** [mmistakes/minimal-mistakes#628]
- [x] This is a feature request.

---

## Steps to reproduce the behavior

I'd love to be able to do something like:

```
sidebar:
  - title: "Title"
    image: http://placehold.it/350x250
    image_alt: "image"
    text: "Some text here."
    url: http://www.google.com
    link-style: .btn .btn--success
```

**Comment by mmistakes** [comment]
`sidebar.text` fully supports Markdown so whatever you can do there you can add to that variable and it'll be parsed.

For example:

```yaml
sidebar:
  - title: "Title"
    image: http://placehold.it/350x250
    image_alt: "image"
    text: "If you put **Markdown** in here it will parse, so you can do things like [link out](http://www.google.com). If you want to break up a line you can do this\r\n\r\nto insert a hard return. And even apply a button style:\r\n\r\n[to a link](#){: .btn .btn--success}"
```

Will build as:

```html
<img src="http://placehold.it/350x250" alt="image">
<h3>Title</h3>
<p>If you put <strong>Markdown</strong> in here it will parse, so you can do things like <a href="http://www.google.com">link out</a>. If you want to break up a line you can do this</p>
<p>to insert a hard return. And even apply a button style:</p>
<p><a href="#" class="btn btn--success">to a link</a></p>
```

And look like:

![sidebar-md](https://cloud.githubusercontent.com/assets/1376749/19932534/d9d554be-a0e6-11e6-958b-35755a8b7bb0.jpg)
