### ISSUE TITLE
Layout 'single' does  not exist

### ISSUE THREAD

**Issue by bretonio** [mmistakes/minimal-mistakes#673]
```bash
Configuration file: /home/bretonio/Ao-Vivo/projetoengenhocas.github.io/_config.yml
Configuration file: /home/bretonio/Ao-Vivo/projetoengenhocas.github.io/_config.yml
            Source: /home/bretonio/Ao-Vivo/projetoengenhocas.github.io
       Destination: /home/bretonio/Ao-Vivo/projetoengenhocas.github.io/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
 [33m Error reading file /home/bretonio/Ao-Vivo/projetoengenhocas.github.io/index.html: (<unknown>): did not find expected key while parsing a block mapping at line 2 column 1  [0m
              Lunr: Creating search index...
 [33m     Build Warning: Layout 'single' requested in _pages/404.md does not exist. [0m
 [33m     Build Warning: Layout 'single' requested in _pages/contato.md does not exist. [0m
 [33m     Build Warning: Layout 'single' requested in _pages/index.html does not exist. [0m
 [33m     Build Warning: Layout 'single' requested in index.html does not exist. [0m
 [33m     Build Warning: Layout 'single' requested in _pages/inicio.md does not exist. [0m
 [33m     Build Warning: Layout 'single' requested in _pages/projetos.md does not exist. [0m
 [33m     Build Warning: Layout 'single' requested in _pages/recursos.md does not exist. [0m
 [33m     Build Warning: Layout 'single' requested in _pages/sobre.md does not exist. [0m
              Lunr: Index ready (lunr.js v0.4.5)
                    done in 7.954 seconds.
 Auto-regeneration: enabled for '/home/bretonio/Ao-Vivo/projetoengenhocas.github.io'
Configuration file: /home/bretonio/Ao-Vivo/projetoengenhocas.github.io/_config.yml
    Server address: http://127.0.0.1:4000/
  Server running... press ctrl-c to stop.
```
The layout `single.html` does, however, exist in `_layouts`. 

So far this is only a warning as to the `single` style pages. 

These  types of page render properly, except that `inicio.html`, the first inside page, is substituted for the `index.html` in my `_pages` folder. 

The latter should be a splash page named `index.html` and not a single page named `inicio.html`.  Splash is specified in the front matter correctly, I think?

```
---
layout: splash
permalink: 
date: 2016-03-23T11:48:41-04:00
header:
  overlay_image: https://raw.githubusercontent.com/bretonio/bretonio.github.io/master/images/infernalmachine.jpg
  overlay_filter: "0.7"
  cta_label: "Saiba Mais"	
  cta_url: https://Braytonio.github.io/aboutme
excerpt: "Admiráveis Engenhos Novos: A crescente caixa de ferramentos do desenvolvedor moderno."
```

The site as it should be rendered is [here](https://projetoengenhocas.github.io/index.html). When I try to `git pull` to see if I can restore the correct version, it it tells me "already up to date"  ...
