### ISSUE TITLE
Question: using liquid inside the navigation yml

### ISSUE THREAD

**Issue by chrisvidal** [mmistakes/minimal-mistakes#714]
- [x] This is a question about using the theme.
---

How could we be able to build dynamic label for the navigation based on the site local ?
im trying to do this but it does not compile

````yaml
# main links
main:
  - title: {{ site.data.ui-text[site.locale].about_label | default: "About" }}
  - url: "/about"
````
