### ISSUE TITLE
Wider text area in the blog posts/pages

### ISSUE THREAD

**Issue by frosenberg** [mmistakes/minimal-mistakes#74]
Great theme!! Is there an easy way to make the text area in the blog posts a litt wider and reduce the "white borders". I'm not a CSS expert and my attempts failed so far ;). Any hint appreciated.

**Comment by ultinomics** [comment]
Sorry to zombie an old post, but I wanted to clarify something. (I'm also a Jekyll and css noob, sorry :(.)

Is changing variable `$def_grid: 12` to something like `$def_grid: 16` in the file [grid.scss](https://github.com/mmistakes/minimal-mistakes/blob/master/_sass/grid.scss) the *only* thing that is required to make the text wider?

Or do we also need to update all the `grid(12,10)` values in [page.scss](https://github.com/mmistakes/minimal-mistakes/blob/master/_sass/page.scss) to match?

If I just change `$def_grid`, nothing seems to happen. But if I try to change the values in `pages.scss` to match `$def_grid`---say, `grid(16,14)` `prefix(16,1)` and `suffix(16,1)` to match `$def_grid: 16`---I get a "page failed" error from GitHub.

I sort of just gave up and reverted everything back. Would be great to fully understand how to shift the width.

Thanks!

**Comment by mmistakes** [comment]
Changing `$def_grid` probably won't help. All it's going to do is change the math slightly.

You need to play with the grid mixins found in `grid.scss`. They're all documented if you look at the comments for some guidance. Basically what's going on is with the `grid(x, x)` mixin it's saying make the element you apply it to x amount of columns wide.

`grid(12,10)` means 10 columns of 12 (12 being the same amount of columns as `$def_grid`) which is a width of about `83.33333%`. `12,12` would be 100%. The mixin isn't doing much other than to do some quick math to output the widths in percentages.

There's also some media queries mixed in there to change the amount of columns `#main .post` and `#main .page` span depending on the screen sizes. I'm guessing you want to make it wider on desktop screens. So you'll need to play with the grid mixin values at the `large` and `x-large` breakpoints.

You'll see below it goes from 10 columns on mobile to 6 columns, to 5 columns at the largest screen size. I did this to make the typographic measure shorter since long lines of text are harder for the eye to track and read.

```scss
#main {
	counter-reset: captions;
	@include container;
	@include clearfix;
	clear: both;
	margin-top: 2em;
	h1 {
		margin-top: 0;
	}
	.post,
	.page {
		@include container;
		@include grid(12,10);
		@include prefix(12,1);
		@include suffix(12,1);
		margin-bottom: 2em;
		@media #{$small} {
			@include grid(12,8);
			@include prefix(12,0);
			@include suffix(12,0);
		}
		@media #{$large} {
		@include grid(12,6); // increase 6 if you want to make it wider
		}
		@media #{$x-large} {
			@include grid(12,5); // increase 5 if you want to make it wider
		}
	}
}
```

The `prefix` and `suffix` mixins apply margin before and after to simulate a gutter. They work similar to the other mixin. The first value is the base grid (eg. 12 columns), the second is how many columns.

`prefix(12,0)` would remove any margin to the left, `prefix(12,1)` would add a column of margin before, `12,2` would add 2 columns, etc. etc. etc.
