### ISSUE TITLE
Add Nepal (Nepali) translated text

### ISSUE THREAD

**Issue by ritayadav** [mmistakes/minimal-mistakes#775]
Dear Developer,

Please add Nepali(Nepal) language, 
I can help to translate.

**Comment by mmistakes** [comment]
If you're comfortable with Git please edit [_data/ui-text.yml](https://github.com/mmistakes/minimal-mistakes/blob/develop/_data/ui-text.yml) to include a new locale and translated strings and submit a pull request against the `develop` branch. 

If not feel free to add the translations below for each of the following and I can take care of the rest.

```yaml
# Nepali (Nepal)
# -----------------
ne: &DEFAULT_NE
  page                       : "Page"
  pagination_previous        : "Previous"
  pagination_next            : "Next"
  breadcrumb_home_label      : "Home"
  breadcrumb_separator       : "/"
  menu_label                 : "Toggle Menu"
  toc_label                  : "On This Page"
  ext_link_label             : "Direct Link"
  less_than                  : "less than"
  minute_read                : "minute read"
  share_on_label             : "Share on"
  meta_label                 :
  tags_label                 : "Tags:"
  categories_label           : "Categories:"
  date_label                 : "Updated:"
  comments_label             : "Leave a Comment"
  comments_title             : "Comments"
  more_label                 : "Learn More"
  related_label              : "You May Also Enjoy"
  follow_label               : "Follow:"
  feed_label                 : "Feed"
  powered_by                 : "Powered by"
  website_label              : "Website"
  email_label                : "Email"
  recent_posts               : "Recent Posts"
  undefined_wpm              : "Undefined parameter words_per_minute at _config.yml"
  comment_form_info          : "Your email address will not be published. Required fields are marked"
  comment_form_comment_label : "Comment"
  comment_form_md_info       : "Markdown is supported."
  comment_form_name_label    : "Name"
  comment_form_email_label   : "Email address"
  comment_form_website_label : "Website (optional)"
  comment_btn_submit         : "Submit Comment"
  comment_btn_submitted      : "Submitted"
  comment_success_msg        : "Thanks for your comment! It will show on the site once it has been approved."
  comment_error_msg          : "Sorry, there was an error with your submission. Please make sure all required fields have been completed and try again."
  loading_label              : "Loading..."
ne-NP:
  <<: *DEFAULT_NE
```
