### ISSUE TITLE
Same font-size displays differently for tables and divs

### ISSUE THREAD

**Issue by desilinguist** [mmistakes/minimal-mistakes#800]
- [x] This is a question about using the theme.
- [ ] I believe this to be a bug with the theme --- not Jekyll, GitHub Pages or one of the bundled plugins.
- [ ] This is a feature request.
- [ ] I have updated all gems with `bundle update`.
- [x] I have tested locally with `bundle exec jekyll build`.

---

## Environment informations

- **Minimal Mistakes version:** 3.3.3
- **`github-pages` or `jekyll` gem version:** 3.1.6
- **Operating system:** MacOS 10.12.2

---

## Expected behavior

I first wrote an HTML page using tables but then wasn't happy with it and realized that I could use Susy to do a better job so I switched to using DIVs. However, I am completely flummoxed in that I am seeing larger font-sizes when I use DIVs even though I have explicitly set them to be exactly the same.

Here's the HTML and the SCSS for the tables version:

```html
<table class="confprogram">
    <thead>
        <tr>
            <th colspan="3">Sunday, June 12</th>
        </tr>
    </thead>
</table>
```

```css
table.confprogram {
 width: 100%
  th {
    font-size: $type-size-2;
  }
}
```
and here's the output:

<img width="987" alt="screen shot 2017-01-27 at 1 58 20 pm" src="https://cloud.githubusercontent.com/assets/161680/22383661/b07327a4-e498-11e6-830f-79dc8a341ea4.png">

And here is HTML, SCSS, and output for the div version:

```html
<div>
    <div class="day" id="first-day">Sunday, June 12</div>
</div>
```

```css
div.day {
    @include span(12);
    padding: 0.5em;
    font-family: $serif;
    font-weight: bold;
    text-align: left;
    vertical-align: middle;
    font-size: $type-size-2;
    background-color: $lighter-gray;
    border: 1px solid $light-gray;
}
```
<img width="983" alt="screen shot 2017-01-27 at 2 00 02 pm" src="https://cloud.githubusercontent.com/assets/161680/22383725/ec723290-e498-11e6-8779-08a7f01562b7.png">

Note that I have taken most of the SCSS for `div.day` from `_tables.scss` in order to try and match them perfectly. I also looked in the developer tools in the elements tab and all of the fields looked identical to me. I would appreciate any suggestion or thoughts you might have about this.
