### ISSUE TITLE
How to customize the category/tag pages generated by jekyll-archive?

### ISSUE THREAD

**Issue by billgarrison** [mmistakes/minimal-mistakes#832]
- [x] This is a question about using the theme.
- [ ] I believe this to be a bug with the theme --- not Jekyll, GitHub Pages or one of the bundled plugins.
- [ ] This is a feature request.
- [x] I have updated all gems with `bundle update`.
- [x] I have tested locally with `bundle exec jekyll build`.

---

## Environment informations

- **Minimal Mistakes version:*4.2.1* 
- **`jekyll` gem version:*3.4.0* 
- **Operating system:*Mac OS 10.11.6* 
---

## Expected behavior

I'd like to add an overlay header to the pages generated by the jekyll-archive plugin. My approach has been to override the theme's `archive-taxonomy.html` layout and add the relevant overlay image config to the front matter.  It's not working for me.

A whack with a clue stick would be appreciated.

### jekyll-archive config

I have jekyll-archive installed and it is generating a page for each tag and category as expected, just not with the header image I'd like. Here's the relevant section of `_config.yml`

```
category_archive:
  type: jekyll-archives
  path: /categories/
tag_archive:
  type: jekyll-archives
  path: /tags/
jekyll-archives:
  enabled:
    - year
    - categories
    - tags
  layouts:
    category: archive-taxonomy
    tag: archive-taxonomy
  permalinks:
    year: /year
    category: /categories/:name/
    tag: /tags/:name/
```

### theme layout override 

To override the theme, made a local copy of `archive-taxonomy.html`, and added `header:` info to the layout's front matter.

```
---
layout: default
author_profile: false

header: 
       overlay_image: "/assets/images/brick-banner-3.png"
       overlay_filter: rgba(0, 0, 0, 0.15)
       cta_label: "Book Now"
       cta_url: "/booknow"
---
```

**Comment by mmistakes** [comment]
That layout doesn't have the Liquid code for headers. Take a look at the standard archive.html to see what code you'd need to add to the taxonomy for then to work. 

The YAML you're using is fine it just needs the layout code to make it show up.

**Comment by billgarrison** [comment]
OK. I did that, pulling in

```
{% if page.header.overlay_color or page.header.overlay_image or page.header.image %}
  {% include page__hero.html %}
{% elsif page.header.video.id and page.header.video.provider %}
  {% include page__hero_video.html %}
{% endif %}
```

No go. In doing some caveman debugging, it looks like the`page` object doesn't have any header info in it. The generated category/tag pages have the following info for `page`:

<p>page: {{ page }}</p>

```
page: {"layout"=>"archive-taxonomy", "posts"=>[#], "type"=>"tag", "title"=>"coupons", "date"=>nil, "name"=>"index", "path"=>"tags/coupons/index.html", "url"=>"/tags/coupons/"}
```

If I explicitly ask for `page.header.overlay_image`, I get nothing back in the generated page.

**Comment by mmistakes** [comment]
Think that's a causality of using Jekyll Archives. It has access to certain objects, `page` likely isn't one of them, at least not in the way you're trying to access it. I'm sure there's a way to do it but you might need to get creative.

I'd inquire with that plugin as I don't really know much more about it other than what they've [documented here](https://github.com/jekyll/jekyll-archives/blob/master/docs/layouts.md).

**Comment by billgarrison** [comment]
Thanks! I think you're right. Digging through the plugin code, it restricts Liquid to a fixed set of attributes on page, and doesn't pay any attention to extra data in the layout front matter.

That's fine. I spent a few hours learning how plugins work and how to debug Ruby. So, +1 for that! :-)

**Comment by billgarrison** [comment]
I solved this finally, by copying the relevant layout code from page__hero.html into a custom layout file for jekyll-archive to use. The generated category/tag pages match the styling of the rest of my site. 

Thanks very much for the help. :-)

**Comment by billgarrison** [comment]
Captain's Log: Supplemental

After closing this issue, I read somewhere else that since Jekyll 3, layout front matter is no longer made accessible to Liquid via the `page` variable, but through `layout`.

So, I tried the approach of customizing `archive.html` to access the `header` front matter info through `layout.header` in the Liquid. Changing the jekyll-archive config to use my customized layout, that approach worked fine. I had to pull in `sidebar.html` and tweak it to access sidebar definitions through `layout` also.

Ultimately, it was a "6 of one, half dozen of the other" solution. Copying pieces of Liquid code out of `archive.html` & `sidebar.html` into new layout, versus copying layout files and modifying them to access info through the `layout` variable, both required about the same amount of work.

Just wanted to offer this up as a viable alternative solution to customizing pages generated by jekyll-archive.

**Comment by mmistakes** [comment]
There's probably some Liquid voodoo that might be possible to determine what layout is in use and then apply `page.` or `layout.` accordingly. Versus duplicating all of the includes into the Jekyll Archives just to make that minor change.

Would DRY things up some too. All hypothetical though as I haven't tested it :wink:

**Comment by ohadschn** [comment]
I wonder, has there been any news on this? Is there some simpler way to customize the category/tag pages generated by `jekyll-archives` (e.g. add a header image)?

**Comment by mmistakes** [comment]
@ohadschn Your best bet is opening a feature request on jekyll-archives to allow for it. There's really only a few variables exposed at the archive page level through the plugin... all of which are related to getting the title.

As I mentioned above, if you're properly motivated you can come up with some custom Liquid to do it. I did just this on one project.

For example say you're creating a set of tag archives and what a header image on them that corresponds with the current tag... let's call that `foo`.

What you can do is in your tag archive layout add something like:

```
{% assign taxonomy = page.title | downcase | slugify %}
{% assign tag = site.data.taxonomy[taxonomy] %}
```

What this does is take the `page.title`, which in this case will be `Foo` and does some normalizing (lowercase, replace spaces with `-`, etc.). If the title was "Foo Bar" you'd get `foo-bar`. This gives you a predictable value you can use as a "key" in a data file. In this case `_data/taxonomy.yml`.

Which looks something like:

```
foo:
  description: "Foo is an example of foo."
  image: /path-to-image-foo.jpg

foo-bar:
  description: "Foo Bar is an example of foo + bar."
  image: /path-to-image-foo-bar.jpg
```

Through the assigns above you can easily pull in this data into the tag archive layout now:

```
{% if tag.image %}
  <img src="{{ tag.image }}" alt="">
{% endif %}
```

I used this method to add detailed descriptions for each tag archive page. But you can use it to assign images and any other data you can dream up. You can see examples of my old [tag archive layout](https://github.com/mmistakes/made-mistakes-jekyll/blob/5ab74389e49fe38c86a327898f223a8fa2e79abe/src/_layouts/tag_index.html) and [taxonomy.yml](https://github.com/mmistakes/made-mistakes-jekyll/blob/5ab74389e49fe38c86a327898f223a8fa2e79abe/src/_data/taxonomy.yml) files here.
