### ISSUE TITLE
index.html files are not generated when using jekyll-archives 

### ISSUE THREAD

**Issue by LutherDiaz** [mmistakes/minimal-mistakes#879]
- [x] This is a question about using the theme.
- [ ] I believe this to be a bug with the theme --- not Jekyll, GitHub Pages or one of the bundled plugins.
- [ ] This is a feature request.
- [x] I have updated all gems with `bundle update`.
- [x] I have tested locally with `bundle exec jekyll build`.

---

## Environment informations

- **Minimal Mistakes version:** 4.2.2
- **`jekyll` gem version:** 3.3.1

Configuration
```
category_archive:
  type: jekyll-archives
  path: /categories/
tag_archive:
  type: jekyll-archives
  path: /tags/
jekyll-archives:
  enabled:
    - categories
    - tags
  layouts:
    category: archive-taxonomy
    tag: archive-taxonomy
  permalinks:
    category: /categories/:name/
    tag: /tags/:name/
```
---

## Expected behavior

There should be an index.html in /tags/ and /categories/

## Steps to reproduce the behavior

When I view with the browser, /tag/ and /categories shows a WEBBrick index.
The index.html files are not generated with jekyll build as well.
