### ISSUE TITLE
Archives not working on github-pages

### ISSUE THREAD

**Issue by satwikkansal** [mmistakes/minimal-mistakes#974]
I'm trying to add archives to my blog following the instructions at https://mmistakes.github.io/minimal-mistakes/docs/configuration/ but couldn't get them working in github-pages with either of `liquid` and `jekyll-archives`. 

Some of my findings:
1. Using liquid in both
```
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
```
tags work as expected locally, but on gh-pages I get random error
`Github pages is down for maintainence` which disappears after I reload.

categories show the error:
 `/categories/ not found` locally
and `404 not found error` on gh-pages

2. Using `jekyll-archive` for both
```
category_archive:
  type: jekyll-archives
  path: /categories/
tag_archive:
  type: jekyll-archives
  path: /tags/
jekyll-archives:
  enabled:
    - categories
    - tags
  layouts:
    category: archive-taxonomy
    tag: archive-taxonomy
  permalinks:
    category: /categories/:name/
    tag: /tags/:name/
```
Both work fine locally, but on github-pages I get the `404 not found error` for both of them.

Here's my _config.yml https://github.com/satwikkansal/satwikkansal.github.io/blob/master/_config.yml, and http://blog.satwikkansal.xyz is where the site is deployed.
