### ISSUE TITLE
Disqus not working 

### ISSUE THREAD

**Issue by banpie** [mmistakes/minimal-mistakes#979]
Hi：

Love Minimal-mistakes，Awesome theme for jekyll！

I have some trouble with setting up comment in my site, and I have search all kinds of method, but still get it work. So ask for some help...

-----

- **Minimal Mistakes version:** 4.4.1
- **`github-pages` or `jekyll` gem version:** jekyll 3.4.3
- **Operating system:**  Mac 10.12.4

---

## Expected behavior

Disqus show in my the footer of the post 

## Steps to reproduce the behavior

I have try all the method in the troubleshooting guide for "disqus do not show" including:
- check shortname
- delete disqus account and create a new account
- recreate a new jekyll site

but comment still do not show.

there is my config setting:
```
comments:
  provider               : “disqus”
  disqus:
    shortname            : banpie 

````
```
# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
```

My site is ： banpie.github.io, here is the post: [https://banpie.github.io/college](https://banpie.github.io/college)

Thanks ！
